<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see AgentTaxIdentificationNumberTaxIdentificationNumber}.
 */
final class AgentTaxIdentificationNumberTaxIdentificationNumberBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $iDNumberIssuingCntryCd
     * @param Option<string>           $iDNumberRequestingCntryCd
     * @param Option<string>           $includeIDNumberOnShippingBrokerageDocs
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $identificationNumber,
        private string $iDNumberCustomerRole,
        private string $iDNumberEncryptionIndicator,
        private string $iDNumberPurposeCode,
        private string $iDNumberTypeCode,
        private Option $iDNumberIssuingCntryCd,
        private Option $iDNumberRequestingCntryCd,
        private Option $includeIDNumberOnShippingBrokerageDocs,
        private array $additionalProperties,
    ) {
    }

    /**
     * The code or number that a shipper or consignee has registered with a particular country’s
     * authority for doing business, or for identification purposes.
     */
    public function setIdentificationNumber(string $identificationNumber): self
    {
        $this->identificationNumber = $identificationNumber;

        return $this;
    }

    /**
     * A business or individual identification type description (Future Use).specifies the
     * relationship of the customer/ID Number to the shipment 05 =importer Address, 06=Exporter
     * Address , 18=DeliverTo/Consignee/Reciever Address, 37= Shipper Address.
     */
    public function setIDNumberCustomerRole(string $iDNumberCustomerRole): self
    {
        $this->iDNumberCustomerRole = $iDNumberCustomerRole;

        return $this;
    }

    /**
     * to determine if decryption is required. 0 = Identification number is not Encrypted 1 =
     * Identification number is Encrypted.
     */
    public function setIDNumberEncryptionIndicator(string $iDNumberEncryptionIndicator): self
    {
        $this->iDNumberEncryptionIndicator = $iDNumberEncryptionIndicator;

        return $this;
    }

    /**
     * Code that specifies the purpose of the Identification Number. For all tax ID that are not
     * EORI = ‘01’ Valid values: 00/ Spaces = Unknown 01= Customs/Brokerage (Default) 02=
     * Customs/Brokerage EORI 99= Other.
     */
    public function setIDNumberPurposeCode(string $iDNumberPurposeCode): self
    {
        $this->iDNumberPurposeCode = $iDNumberPurposeCode;

        return $this;
    }

    /**
     * Valid Values are: 0000 = Unknown IDNumberTypeCode equal to ‘0000’ (unknown) is to be used
     * when an ‘ID Number Type’ is not applicable, or when the front-end/client system cannot
     * determine the type of IdentificationNumber (for any reason). 0001 = Exporter Tax ID Number
     * 0002 = Importer Tax ID Number or EORI Number – When IdentificationNumberPurposeCode = 02 0005
     * = Personal Tax ID Number 1001 = Other / Free Form 1002 = Company/Business Tax ID Number 1003
     * = National ID Number 1004 = Passport Number 1005 = Personal ID Number 1006 = Phone Number.
     */
    public function setIDNumberTypeCode(string $iDNumberTypeCode): self
    {
        $this->iDNumberTypeCode = $iDNumberTypeCode;

        return $this;
    }

    /**
     * The ISO-defined country code of the country where the Identification Number was issued, when
     * applicable (as per business requirements). Needed for certain types of Identification Numbers
     * (e.g., Passport Number). Sample Values: 'ID' = Indonesia, 'VN' = Vietnam, 'DE' = Germany.
     */
    public function setIDNumberIssuingCntryCd(string $iDNumberIssuingCntryCd): self
    {
        $this->iDNumberIssuingCntryCd = Some::create($iDNumberIssuingCntryCd);

        return $this;
    }

    /**
     * The ISO-defined country code of the country whose regulatory agency is requesting the
     * Identification Number. Typically for Import, the Consignee ID is requested by the Ship To
     * country For export, the Shipper ID is requested by the Ship From country.
     *
     * Required when a country (e.g., Origin country, Destination country) is requesting an ID
     * Number for a shipment.
     */
    public function setIDNumberRequestingCntryCd(string $iDNumberRequestingCntryCd): self
    {
        $this->iDNumberRequestingCntryCd = Some::create($iDNumberRequestingCntryCd);

        return $this;
    }

    /**
     * field to determine if the Identification Number should be excluded from Shipping/Brokerage
     * documents (not be passed to Document Services) ‘00’ -> Do Not include 01-> Include.
     */
    public function setIncludeIDNumberOnShippingBrokerageDocs(string $includeIDNumberOnShippingBrokerageDocs): self
    {
        $this->includeIDNumberOnShippingBrokerageDocs = Some::create($includeIDNumberOnShippingBrokerageDocs);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): AgentTaxIdentificationNumberTaxIdentificationNumber
    {
        return new AgentTaxIdentificationNumberTaxIdentificationNumber(
            $this->identificationNumber,
            $this->iDNumberCustomerRole,
            $this->iDNumberEncryptionIndicator,
            $this->iDNumberPurposeCode,
            $this->iDNumberTypeCode,
            $this->iDNumberIssuingCntryCd,
            $this->iDNumberRequestingCntryCd,
            $this->includeIDNumberOnShippingBrokerageDocs,
            $this->additionalProperties,
        );
    }
}
