<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see AlternateDeliveryAddressAddress}.
 */
final class AlternateDeliveryAddressAddressBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param list<string>             $addressLine
     * @param Option<string>           $stateProvinceCode
     * @param Option<string>           $postalCode
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private array $addressLine,
        private string $city,
        private string $countryCode,
        private Option $stateProvinceCode,
        private Option $postalCode,
        private array $additionalProperties,
    ) {
    }

    /**
     * Address Line of the Retail Location.
     *
     * @param list<string> $addressLine
     */
    public function setAddressLine(array $addressLine): self
    {
        $this->addressLine = $addressLine;

        return $this;
    }

    /**
     * Retail Location City.
     */
    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Retail Location country or territory code.
     */
    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = $countryCode;

        return $this;
    }

    /**
     * Retail Location state or province code. Required for US, Canada, and Vietnam (VN).
     *
     * - For US or Canada, the value must be a valid US state or Canadian province code.
     * - For Vietnam (VN), the value must be a valid province code (for example, VN-44).
     * - If the country or territory is Ireland, the StateProvinceCode must contain the county.
     */
    public function setStateProvinceCode(string $stateProvinceCode): self
    {
        $this->stateProvinceCode = Some::create($stateProvinceCode);

        return $this;
    }

    /**
     * If the Alternate Delivery Address country or territory is US or Puerto Rico, 5 or 9 digits
     * are required. The character - may be used to separate the first five digits and the last four
     * digits. If the Alternate Delivery Address country or territory is CA, then the postal code is
     * required and must be 6 alphanumeric characters whose format is A#A#A# where A is an uppercase
     * letter and # is a digit. Otherwise optional. For all other countries or territories the
     * postal code is optional and must be no more than 9 alphanumeric characters long.
     */
    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = Some::create($postalCode);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): AlternateDeliveryAddressAddress
    {
        return new AlternateDeliveryAddressAddress(
            $this->addressLine,
            $this->city,
            $this->countryCode,
            $this->stateProvinceCode,
            $this->postalCode,
            $this->additionalProperties,
        );
    }
}
