<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see BillShipperCreditCard}.
 */
final class BillShipperCreditCardBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<CreditCardAddress> $address
     * @param array<int|string, mixed>  $additionalProperties
     */
    public function __construct(
        private string $type,
        private string $number,
        private string $expirationDate,
        private string $securityCode,
        private Option $address,
        private array $additionalProperties,
    ) {
    }

    /**
     * Valid values:
     * - 01 = American Express
     * - 03 = Discover
     * - 04 = MasterCard
     * - 05 = Optima
     * - 06 = VISA
     * - 07 = Bravo
     * - 08 = Diners Club
     * - 13 = Dankort
     * - 14 = Hipercard
     * - 15 = JCB
     * - 17 = Postepay
     * - 18 = UnionPay/ExpressPay
     * - 19 = Visa Electron
     * - 20 = VPAY
     * - 21 = Carte Bleue.
     */
    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Credit Card number.
     */
    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    /**
     * Format is MMYYYY where MM is the 2 digit month and YYYY is the 4 digit year. Valid month
     * values are 01-12 and valid year values are Present Year - (Present Year + 10 years).
     */
    public function setExpirationDate(string $expirationDate): self
    {
        $this->expirationDate = $expirationDate;

        return $this;
    }

    /**
     * Three or four digits that can be found either on top of credit card number or on the back of
     * credit card. Number of digits varies for different type of credit card. Valid values are 3 or
     * 4 digits. It is required to provide the security code if credit card information is provided
     * and when the ShipFrom countries or territories are other than the below mentioned countries
     * or territories. Argentina, Bahamas, Costa Rica, Dominican Republic, Guatemala, Panama, Puerto
     * Rico and Russia.
     */
    public function setSecurityCode(string $securityCode): self
    {
        $this->securityCode = $securityCode;

        return $this;
    }

    /**
     * Container to hold the Credit card Billing Address. It is required to provide billing address
     * if credit card information is provided and when the ShipFrom country or territory is the US,
     * PR, and CA.
     */
    public function setAddress(CreditCardAddress $address): self
    {
        $this->address = Some::create($address);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): BillShipperCreditCard
    {
        return new BillShipperCreditCard(
            $this->type,
            $this->number,
            $this->expirationDate,
            $this->securityCode,
            $this->address,
            $this->additionalProperties,
        );
    }
}
