<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

/**
 * Builds a {@see CODCODAmount}.
 */
final class CODCODAmountBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $currencyCode,
        private string $monetaryValue,
        private array $additionalProperties,
    ) {
    }

    /**
     * COD amount currency code type.
     */
    public function setCurrencyCode(string $currencyCode): self
    {
        $this->currencyCode = $currencyCode;

        return $this;
    }

    /**
     * COD Amount monetary value.
     */
    public function setMonetaryValue(string $monetaryValue): self
    {
        $this->monetaryValue = $monetaryValue;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): CODCODAmount
    {
        return new CODCODAmount($this->currencyCode, $this->monetaryValue, $this->additionalProperties);
    }
}
