<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see ControlLogReceiptImageFormat}.
 */
final class ControlLogReceiptImageFormatBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $description
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private string $code, private Option $description, private array $additionalProperties)
    {
    }

    /**
     * Code for the type of Graphic Image for the High Value Report.
     *
     * Valid values:
     * - EPL = EPL2 (when user requests label in EPL2 format)
     * - SPL = SPL (when user requests label in SPL format)
     * - ZPL = ZPL (when user requests label in ZPL format)
     * - HTML= HTML (when user requests label in HTML format)
     */
    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Description of the format code.
     */
    public function setDescription(string $description): self
    {
        $this->description = Some::create($description);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ControlLogReceiptImageFormat
    {
        return new ControlLogReceiptImageFormat($this->code, $this->description, $this->additionalProperties);
    }
}
