<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see CreditCardAddress}.
 */
final class CreditCardAddressBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param list<string>             $addressLine
     * @param Option<string>           $stateProvinceCode
     * @param Option<string>           $postalCode
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private array $addressLine,
        private string $city,
        private string $countryCode,
        private Option $stateProvinceCode,
        private Option $postalCode,
        private array $additionalProperties,
    ) {
    }

    /**
     * Address Line 1 of the credit card billing address. Usually Street address information.
     *
     * @param list<string> $addressLine
     */
    public function setAddressLine(array $addressLine): self
    {
        $this->addressLine = $addressLine;

        return $this;
    }

    /**
     * City of the credit card billing address.
     */
    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Credit card billing address country or territory code. Must be a valid UPS Billing country or
     * territory code.
     */
    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = $countryCode;

        return $this;
    }

    /**
     * State or province code of the credit card billing address. Required for US, Canada, and
     * Vietnam (VN).
     *
     * - For US or Canada, the value must be a valid US state or Canadian province code.
     * - For Vietnam (VN), the value must be a valid province code (for example, VN-44).
     * - If the country or territory is Ireland, the StateProvinceCode must contain the county.
     */
    public function setStateProvinceCode(string $stateProvinceCode): self
    {
        $this->stateProvinceCode = Some::create($stateProvinceCode);

        return $this;
    }

    /**
     * Credit card billing addressee postal code.
     */
    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = Some::create($postalCode);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): CreditCardAddress
    {
        return new CreditCardAddress(
            $this->addressLine,
            $this->city,
            $this->countryCode,
            $this->stateProvinceCode,
            $this->postalCode,
            $this->additionalProperties,
        );
    }
}
