<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

/**
 * Builds a {@see DryIceDryIceWeight}.
 */
final class DryIceDryIceWeightBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private DryIceWeightUnitOfMeasurement $unitOfMeasurement,
        private string $weight,
        private array $additionalProperties,
    ) {
    }

    /**
     * Container for Unit of measurement for Dry Ice Weight.
     */
    public function setUnitOfMeasurement(DryIceWeightUnitOfMeasurement $unitOfMeasurement): self
    {
        $this->unitOfMeasurement = $unitOfMeasurement;

        return $this;
    }

    /**
     * Dry Ice Weight. Cannot be more than package weight. Should be more than 0.0. Valid characters
     * are 0-9 and "." (Decimal point). Limit to 1 digit after the decimal. The maximum length of
     * the field is 5 including "." and can hold up to 1 decimal place.
     */
    public function setWeight(string $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): DryIceDryIceWeight
    {
        return new DryIceDryIceWeight($this->unitOfMeasurement, $this->weight, $this->additionalProperties);
    }
}
