<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class ErrorResponse implements SelfNormalizingModel
{
    /**
     * @param Option<CommonErrorResponse> $response
     * @param array<int|string, mixed>    $additionalProperties
     */
    public function __construct(private Option $response, private array $additionalProperties)
    {
    }

    public static function builder(): ErrorResponseBuilder
    {
        return new ErrorResponseBuilder(None::create(), []);
    }

    /**
     * The error response containing any errors that occurred.
     *
     * @return Option<CommonErrorResponse>
     */
    public function getResponse(): Option
    {
        return $this->response;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $response = None::create();
        if (array_key_exists('response', $data) && $data['response'] !== null) {
            $responseRaw = $data['response'];
            if (!is_array($responseRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "response" must be object, got %s.', get_debug_type($responseRaw)),
                );
            }
            /** @var array<string, mixed> $responseRawTyped */
            $responseRawTyped = $responseRaw;
            $response = Some::create(CommonErrorResponse::fromArray($responseRawTyped));
        }
        $additionalProperties = array_diff_key($data, ['response' => true]);

        return new self($response, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $responseOption = $this->response;
        if ($responseOption->isDefined()) {
            $response = $responseOption->get();
            $dataArray['response'] = $normalizationTarget->model($response);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ErrorResponseBuilder
    {
        return new ErrorResponseBuilder($this->response, $this->additionalProperties);
    }
}
