<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see FreightShipmentInformationFreightDensityInfo}.
 */
final class FreightShipmentInformationFreightDensityInfoBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>                                $adjustedHeightIndicator
     * @param Option<FreightDensityInfoAdjustedHeight>      $adjustedHeight
     * @param Option<list<FreightDensityInfoHandlingUnits>> $handlingUnits
     * @param array<int|string, mixed>                      $additionalProperties
     */
    public function __construct(
        private Option $adjustedHeightIndicator,
        private Option $adjustedHeight,
        private Option $handlingUnits,
        private array $additionalProperties,
    ) {
    }

    /**
     * The presence of the AdjustedHeightIndicator indicates that allow the height reduction
     * adjustment for density based rate request.
     */
    public function setAdjustedHeightIndicator(string $adjustedHeightIndicator): self
    {
        $this->adjustedHeightIndicator = Some::create($adjustedHeightIndicator);

        return $this;
    }

    /**
     * Container for the adjusted height. Required if AdjustedHeightIndicator is present.
     */
    public function setAdjustedHeight(FreightDensityInfoAdjustedHeight $adjustedHeight): self
    {
        $this->adjustedHeight = Some::create($adjustedHeight);

        return $this;
    }

    /** @param list<FreightDensityInfoHandlingUnits> $handlingUnits */
    public function setHandlingUnits(array $handlingUnits): self
    {
        $this->handlingUnits = Some::create($handlingUnits);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): FreightShipmentInformationFreightDensityInfo
    {
        return new FreightShipmentInformationFreightDensityInfo(
            $this->adjustedHeightIndicator,
            $this->adjustedHeight,
            $this->handlingUnits,
            $this->additionalProperties,
        );
    }
}
