<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

/**
 * Builds a {@see FreightDensityInfoAdjustedHeight}.
 */
final class FreightDensityInfoAdjustedHeightBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $value,
        private AdjustedHeightUnitOfMeasurement $unitOfMeasurement,
        private array $additionalProperties,
    ) {
    }

    /**
     * Adjusted height value.
     */
    public function setValue(string $value): self
    {
        $this->value = $value;

        return $this;
    }

    /**
     * Container for UnitOfMeasurement for the adjusted height.
     */
    public function setUnitOfMeasurement(AdjustedHeightUnitOfMeasurement $unitOfMeasurement): self
    {
        $this->unitOfMeasurement = $unitOfMeasurement;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): FreightDensityInfoAdjustedHeight
    {
        return new FreightDensityInfoAdjustedHeight(
            $this->value,
            $this->unitOfMeasurement,
            $this->additionalProperties,
        );
    }
}
