<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

/**
 * Builds a {@see FreightDensityInfoHandlingUnits}.
 */
final class FreightDensityInfoHandlingUnitsBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $quantity,
        private HandlingUnitsType $type,
        private HandlingUnitsDimensions $dimensions,
        private array $additionalProperties,
    ) {
    }

    /**
     * Handling Unit Quantity for Density based rating.
     */
    public function setQuantity(string $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * Handling Unit Type for Density based rating.
     */
    public function setType(HandlingUnitsType $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Dimension of the HandlingUnit container for density based pricing.
     */
    public function setDimensions(HandlingUnitsDimensions $dimensions): self
    {
        $this->dimensions = $dimensions;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): FreightDensityInfoHandlingUnits
    {
        return new FreightDensityInfoHandlingUnits(
            $this->quantity,
            $this->type,
            $this->dimensions,
            $this->additionalProperties,
        );
    }
}
