<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class FRSShipmentDataFreightDensityRate implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(
        private string $density,
        private string $totalCubicFeet,
        private array $additionalProperties,
    ) {
    }

    public static function builder(string $density, string $totalCubicFeet): FRSShipmentDataFreightDensityRateBuilder
    {
        return new FRSShipmentDataFreightDensityRateBuilder($density, $totalCubicFeet, []);
    }

    /**
     * Density is returned if the Shipper is eligible for Density based rate. Valid values are 0 to
     * 999.9.
     */
    public function getDensity(): string
    {
        return $this->density;
    }

    /**
     * Total Cubic feet is returned if the Shipper is eligible for Density based rate. Valid values
     * are 0 to 99999.999.
     */
    public function getTotalCubicFeet(): string
    {
        return $this->totalCubicFeet;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $density = null;
        $totalCubicFeet = null;
        if (array_key_exists('Density', $data)) {
            $densityRaw = $data['Density'];
            if (!is_string($densityRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Density" must be string, got %s.', get_debug_type($densityRaw)),
                );
            }
            $density = $densityRaw;
        }
        if (array_key_exists('TotalCubicFeet', $data)) {
            $totalCubicFeetRaw = $data['TotalCubicFeet'];
            if (!is_string($totalCubicFeetRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "TotalCubicFeet" must be string, got %s.', get_debug_type($totalCubicFeetRaw)),
                );
            }
            $totalCubicFeet = $totalCubicFeetRaw;
        }
        $additionalProperties = array_diff_key($data, ['Density' => true, 'TotalCubicFeet' => true]);
        if ($density === null) {
            throw new MalformedDataException('Required property "Density" is missing from the document.');
        }
        if ($totalCubicFeet === null) {
            throw new MalformedDataException('Required property "TotalCubicFeet" is missing from the document.');
        }

        return new self($density, $totalCubicFeet, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['Density'] = $this->density;
        $dataArray['TotalCubicFeet'] = $this->totalCubicFeet;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): FRSShipmentDataFreightDensityRateBuilder
    {
        return new FRSShipmentDataFreightDensityRateBuilder(
            $this->density,
            $this->totalCubicFeet,
            $this->additionalProperties,
        );
    }
}
