<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

/**
 * Builds a {@see InternationalFormsOtherCharges}.
 */
final class InternationalFormsOtherChargesBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $monetaryValue,
        private string $description,
        private array $additionalProperties,
    ) {
    }

    /**
     * The Monetary value of Other Charges. Applies to Invoice and Partial Invoice forms only.
     * Required for Invoice forms and optional for Partial Invoice. Valid characters are 0-9 and '.'
     * (Decimal point). Limit to 2 digit after the decimal. The maximum length of the field is 15
     * including '.' and can hold up to 2 decimal places.
     */
    public function setMonetaryValue(string $monetaryValue): self
    {
        $this->monetaryValue = $monetaryValue;

        return $this;
    }

    /**
     * Description of what the other charges are for. Applies to Invoice and Partial Invoice forms
     * only. Required for Complete Invoice and Optional for Partial Invoice forms.
     */
    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): InternationalFormsOtherCharges
    {
        return new InternationalFormsOtherCharges(
            $this->monetaryValue,
            $this->description,
            $this->additionalProperties,
        );
    }
}
