<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class InternationalFormsBlanketPeriod implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(private string $beginDate, private string $endDate, private array $additionalProperties)
    {
    }

    public static function builder(string $beginDate, string $endDate): InternationalFormsBlanketPeriodBuilder
    {
        return new InternationalFormsBlanketPeriodBuilder($beginDate, $endDate, []);
    }

    /**
     * Begin date of the blanket period. It is the date upon which the Certificate becomes
     * applicable to the good covered by the blanket Certificate (it may be prior to the date of
     * signing this Certificate). Applies to USMCA form only. Required for USMCA. Format is
     * yyyyMMdd. This is not valid for a paperless shipment.
     */
    public function getBeginDate(): string
    {
        return $this->beginDate;
    }

    /**
     * End Date of the blanket period. It is the date upon which the blanket period expires. Applies
     * to USMCA form only. Required for USMCA CO. Format is yyyyMMdd. This is not valid for a
     * paperless shipment.
     */
    public function getEndDate(): string
    {
        return $this->endDate;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $beginDate = null;
        $endDate = null;
        if (array_key_exists('BeginDate', $data)) {
            $beginDateRaw = $data['BeginDate'];
            if (!is_string($beginDateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "BeginDate" must be string, got %s.', get_debug_type($beginDateRaw)),
                );
            }
            $beginDate = $beginDateRaw;
        }
        if (array_key_exists('EndDate', $data)) {
            $endDateRaw = $data['EndDate'];
            if (!is_string($endDateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "EndDate" must be string, got %s.', get_debug_type($endDateRaw)),
                );
            }
            $endDate = $endDateRaw;
        }
        $additionalProperties = array_diff_key($data, ['BeginDate' => true, 'EndDate' => true]);
        if ($beginDate === null) {
            throw new MalformedDataException('Required property "BeginDate" is missing from the document.');
        }
        if ($endDate === null) {
            throw new MalformedDataException('Required property "EndDate" is missing from the document.');
        }

        return new self($beginDate, $endDate, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['BeginDate'] = $this->beginDate;
        $dataArray['EndDate'] = $this->endDate;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): InternationalFormsBlanketPeriodBuilder
    {
        return new InternationalFormsBlanketPeriodBuilder(
            $this->beginDate,
            $this->endDate,
            $this->additionalProperties,
        );
    }
}
