<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class LABELRECOVERYRequestWrapper implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(private LabelRecoveryRequest $labelRecoveryRequest, private array $additionalProperties)
    {
    }

    public static function builder(LabelRecoveryRequest $labelRecoveryRequest): LABELRECOVERYRequestWrapperBuilder
    {
        return new LABELRECOVERYRequestWrapperBuilder($labelRecoveryRequest, []);
    }

    /**
     * Request for obtaining the Label for the return shipment.
     */
    public function getLabelRecoveryRequest(): LabelRecoveryRequest
    {
        return $this->labelRecoveryRequest;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $labelRecoveryRequest = null;
        if (array_key_exists('LabelRecoveryRequest', $data)) {
            $labelRecoveryRequestRaw = $data['LabelRecoveryRequest'];
            if (!is_array($labelRecoveryRequestRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "LabelRecoveryRequest" must be object, got %s.',
                        get_debug_type($labelRecoveryRequestRaw),
                    ),
                );
            }
            /** @var non-empty-array<string, mixed> $labelRecoveryRequestRawTyped */
            $labelRecoveryRequestRawTyped = $labelRecoveryRequestRaw;
            $labelRecoveryRequest = LabelRecoveryRequest::fromArray($labelRecoveryRequestRawTyped);
        }
        $additionalProperties = array_diff_key($data, ['LabelRecoveryRequest' => true]);
        if ($labelRecoveryRequest === null) {
            throw new MalformedDataException('Required property "LabelRecoveryRequest" is missing from the document.');
        }

        return new self($labelRecoveryRequest, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['LabelRecoveryRequest'] = $normalizationTarget->model($this->labelRecoveryRequest);
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): LABELRECOVERYRequestWrapperBuilder
    {
        return new LABELRECOVERYRequestWrapperBuilder($this->labelRecoveryRequest, $this->additionalProperties);
    }
}
