<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

/**
 * Builds a {@see LabelRecoveryResponseForm}.
 */
final class LabelRecoveryResponseFormBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private LabelRecoveryFormImage $image, private array $additionalProperties)
    {
    }

    /**
     * Container tag for the International Forms image.
     */
    public function setImage(LabelRecoveryFormImage $image): self
    {
        $this->image = $image;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): LabelRecoveryResponseForm
    {
        return new LabelRecoveryResponseForm($this->image, $this->additionalProperties);
    }
}
