<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class LabelRecoveryResponseLabelResults implements SelfNormalizingModel
{
    /**
     * @param Option<string>                                $trackingNumber
     * @param Option<LabelResultsLabelImage>                $labelImage
     * @param Option<string>                                $mailInnovationsTrackingNumber
     * @param Option<LabelResultsMailInnovationsLabelImage> $mailInnovationsLabelImage
     * @param Option<LabelResultsReceipt>                   $receipt
     * @param Option<LabelResultsForm>                      $form
     * @param array<int|string, mixed>                      $additionalProperties
     */
    public function __construct(
        private Option $trackingNumber,
        private Option $labelImage,
        private Option $mailInnovationsTrackingNumber,
        private Option $mailInnovationsLabelImage,
        private Option $receipt,
        private Option $form,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): LabelRecoveryResponseLabelResultsBuilder
    {
        return new LabelRecoveryResponseLabelResultsBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Package Tracking number. Package 1Z number. Returned only if TrackingNumber or Combination of
     * Reference Number and Shipper Number present in request.
     *
     * @return Option<string>
     */
    public function getTrackingNumber(): Option
    {
        return $this->trackingNumber;
    }

    /**
     * The elements needed to render a label on a printer or in a browser. Specifies the format in
     * which GraphicImage is represented. If LabelImageFormat is GIF, LabelImage contains
     * GraphicImage and HTMLImage. Otherwise, it contains only GraphicImage. If LabelImageFormat is
     * PDF, LabelImage is only returned at the first package result. If entered in the request, the
     * response mirrors, else the default values are returned. Returned only if TrackingNumber or
     * Combination of Reference Number and Shipper Number present in request.
     *
     * @return Option<LabelResultsLabelImage>
     */
    public function getLabelImage(): Option
    {
        return $this->labelImage;
    }

    /**
     * Mail Innovations Tracking Number. Applicable for Single Mail Innovations Returns and Dual
     * Mail Innovations Returns shipment. Returned only if MailInnovationsTrackingNumber is provided
     * in request.
     *
     * @return Option<string>
     */
    public function getMailInnovationsTrackingNumber(): Option
    {
        return $this->mailInnovationsTrackingNumber;
    }

    /**
     * Container to hold Mail Innovations shipments label. The elements needed to render a label on
     * a printer or in a browser. Specifies the format in which GraphicImage is represented. If
     * LabelImageFormat is GIF, LabelImage contains GraphicImage and HTMLImage. Otherwise, it
     * contains only GraphicImage. Applicable for Single Mail Innovations Returns and Dual Mail
     * Innovations Returns shipment. Returned only if MailInnovationsTrackingNumber is provided in
     * request. If LabelImageFormat requested was PDF and TrackingNumber was present along with
     * MailInnovationsTrackingNumber in the request, only LabelImage container is returned.
     * MailInnovationsLabelImage will not be returned. In that case, the labels for Small Package
     * Tracking Number and Mail Innovations Tracking Number will be stitched in single PDF file.
     *
     * @return Option<LabelResultsMailInnovationsLabelImage>
     */
    public function getMailInnovationsLabelImage(): Option
    {
        return $this->mailInnovationsLabelImage;
    }

    /**
     * Container for the HTML receipt and the receipt link.
     *
     * @return Option<LabelResultsReceipt>
     */
    public function getReceipt(): Option
    {
        return $this->receipt;
    }

    /**
     * Container tag for the International Forms. Currently, represents UPS Premium Care Form for
     * Electronic Returns Label and Electronic Import Control Label. UPS Premium Care Form for
     * Forward shipment if Subverion is 1903 or greater Applicable for Electronic Return Label and
     * Electronic Import Control Label shipments only. Applies only for Canada domestic shipments.
     * Returned for request with SubVersion greater than or equal to 1707. UPS Premium Care Form for
     * Forward shipment if Subverion is 1903 or greater.
     *
     * @return Option<LabelResultsForm>
     */
    public function getForm(): Option
    {
        return $this->form;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $trackingNumber = None::create();
        $labelImage = None::create();
        $mailInnovationsTrackingNumber = None::create();
        $mailInnovationsLabelImage = None::create();
        $receipt = None::create();
        $form = None::create();
        if (array_key_exists('TrackingNumber', $data) && $data['TrackingNumber'] !== null) {
            $trackingNumberRaw = $data['TrackingNumber'];
            if (!is_string($trackingNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "TrackingNumber" must be string, got %s.', get_debug_type($trackingNumberRaw)),
                );
            }
            $trackingNumber = Some::create($trackingNumberRaw);
        }
        if (array_key_exists('LabelImage', $data) && $data['LabelImage'] !== null) {
            $labelImageRaw = $data['LabelImage'];
            if (!is_array($labelImageRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "LabelImage" must be object, got %s.', get_debug_type($labelImageRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $labelImageRawTyped */
            $labelImageRawTyped = $labelImageRaw;
            $labelImage = Some::create(LabelResultsLabelImage::fromArray($labelImageRawTyped));
        }
        if (
            array_key_exists('MailInnovationsTrackingNumber', $data)
            && $data['MailInnovationsTrackingNumber'] !== null
        ) {
            $mailInnovationsTrackingNumberRaw = $data['MailInnovationsTrackingNumber'];
            if (!is_string($mailInnovationsTrackingNumberRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "MailInnovationsTrackingNumber" must be string, got %s.',
                        get_debug_type($mailInnovationsTrackingNumberRaw),
                    ),
                );
            }
            $mailInnovationsTrackingNumber = Some::create($mailInnovationsTrackingNumberRaw);
        }
        if (array_key_exists('MailInnovationsLabelImage', $data) && $data['MailInnovationsLabelImage'] !== null) {
            $mailInnovationsLabelImageRaw = $data['MailInnovationsLabelImage'];
            if (!is_array($mailInnovationsLabelImageRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "MailInnovationsLabelImage" must be object, got %s.',
                        get_debug_type($mailInnovationsLabelImageRaw),
                    ),
                );
            }
            /** @var non-empty-array<string, mixed> $mailInnovationsLabelImageRawTyped */
            $mailInnovationsLabelImageRawTyped = $mailInnovationsLabelImageRaw;
            $mailInnovationsLabelImage = Some::create(
                LabelResultsMailInnovationsLabelImage::fromArray($mailInnovationsLabelImageRawTyped),
            );
        }
        if (array_key_exists('Receipt', $data) && $data['Receipt'] !== null) {
            $receiptRaw = $data['Receipt'];
            if (!is_array($receiptRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Receipt" must be object, got %s.', get_debug_type($receiptRaw)),
                );
            }
            /** @var array<string, mixed> $receiptRawTyped */
            $receiptRawTyped = $receiptRaw;
            $receipt = Some::create(LabelResultsReceipt::fromArray($receiptRawTyped));
        }
        if (array_key_exists('Form', $data) && $data['Form'] !== null) {
            $formRaw = $data['Form'];
            if (!is_array($formRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Form" must be object, got %s.', get_debug_type($formRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $formRawTyped */
            $formRawTyped = $formRaw;
            $form = Some::create(LabelResultsForm::fromArray($formRawTyped));
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'TrackingNumber' => true,
                'LabelImage' => true,
                'MailInnovationsTrackingNumber' => true,
                'MailInnovationsLabelImage' => true,
                'Receipt' => true,
                'Form' => true,
            ],
        );

        return new self(
            $trackingNumber,
            $labelImage,
            $mailInnovationsTrackingNumber,
            $mailInnovationsLabelImage,
            $receipt,
            $form,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $trackingNumberOption = $this->trackingNumber;
        if ($trackingNumberOption->isDefined()) {
            $trackingNumber = $trackingNumberOption->get();
            $dataArray['TrackingNumber'] = $trackingNumber;
        }
        $labelImageOption = $this->labelImage;
        if ($labelImageOption->isDefined()) {
            $labelImage = $labelImageOption->get();
            $dataArray['LabelImage'] = $normalizationTarget->model($labelImage);
        }
        $mailInnovationsTrackingNumberOption = $this->mailInnovationsTrackingNumber;
        if ($mailInnovationsTrackingNumberOption->isDefined()) {
            $mailInnovationsTrackingNumber = $mailInnovationsTrackingNumberOption->get();
            $dataArray['MailInnovationsTrackingNumber'] = $mailInnovationsTrackingNumber;
        }
        $mailInnovationsLabelImageOption = $this->mailInnovationsLabelImage;
        if ($mailInnovationsLabelImageOption->isDefined()) {
            $mailInnovationsLabelImage = $mailInnovationsLabelImageOption->get();
            $dataArray['MailInnovationsLabelImage'] = $normalizationTarget->model($mailInnovationsLabelImage);
        }
        $receiptOption = $this->receipt;
        if ($receiptOption->isDefined()) {
            $receipt = $receiptOption->get();
            $dataArray['Receipt'] = $normalizationTarget->model($receipt);
        }
        $formOption = $this->form;
        if ($formOption->isDefined()) {
            $form = $formOption->get();
            $dataArray['Form'] = $normalizationTarget->model($form);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): LabelRecoveryResponseLabelResultsBuilder
    {
        return new LabelRecoveryResponseLabelResultsBuilder(
            $this->trackingNumber,
            $this->labelImage,
            $this->mailInnovationsTrackingNumber,
            $this->mailInnovationsLabelImage,
            $this->receipt,
            $this->form,
            $this->additionalProperties,
        );
    }
}
