<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

/**
 * Builds a {@see LabelImageLabelImageFormat}.
 */
final class LabelImageLabelImageFormatBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private string $code, private array $additionalProperties)
    {
    }

    /**
     * The format of a label image byte stream. Code type that the label image is to be generated
     * in. Valid value returned is GIF or PDF.
     */
    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): LabelImageLabelImageFormat
    {
        return new LabelImageLabelImageFormat($this->code, $this->additionalProperties);
    }
}
