<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

/**
 * Builds a {@see LabelRecoveryRequestReferenceValues}.
 */
final class LabelRecoveryRequestReferenceValuesBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private ReferenceValuesReferenceNumber $referenceNumber,
        private string $shipperNumber,
        private array $additionalProperties,
    ) {
    }

    /**
     * Container for reference number.
     */
    public function setReferenceNumber(ReferenceValuesReferenceNumber $referenceNumber): self
    {
        $this->referenceNumber = $referenceNumber;

        return $this;
    }

    /**
     * Required if ReferenceNumber/Value is populated. Shipper's six digit account number. Must be
     * six alphanumeric characters. Must be associated with the Internet account used to login.
     */
    public function setShipperNumber(string $shipperNumber): self
    {
        $this->shipperNumber = $shipperNumber;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): LabelRecoveryRequestReferenceValues
    {
        return new LabelRecoveryRequestReferenceValues(
            $this->referenceNumber,
            $this->shipperNumber,
            $this->additionalProperties,
        );
    }
}
