<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see LabelRecoveryRequestLabelSpecification}.
 */
final class LabelRecoveryRequestLabelSpecificationBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>                                          $hTTPUserAgent
     * @param Option<LabelRecoveryLabelSpecificationLabelImageFormat> $labelImageFormat
     * @param Option<LabelRecoveryLabelSpecificationLabelStockSize>   $labelStockSize
     * @param array<int|string, mixed>                                $additionalProperties
     */
    public function __construct(
        private Option $hTTPUserAgent,
        private Option $labelImageFormat,
        private Option $labelStockSize,
        private array $additionalProperties,
    ) {
    }

    /**
     * Browser HTTPUserAgent String. This is the preferred way of identifying GIF image type to be
     * generated. Required if <Root node>/ LabelSpecification/LabelImageFormat/Code = Gif. Default
     * to Mozilla/4.5 if this field is missing or has invalid value.
     */
    public function setHTTPUserAgent(string $hTTPUserAgent): self
    {
        $this->hTTPUserAgent = Some::create($hTTPUserAgent);

        return $this;
    }

    /**
     * The file format of the label and receipt. Defaults to HTML format if this node does not
     * exist.
     */
    public function setLabelImageFormat(LabelRecoveryLabelSpecificationLabelImageFormat $labelImageFormat): self
    {
        $this->labelImageFormat = Some::create($labelImageFormat);

        return $this;
    }

    /**
     * Container to hold Label Height and Width information. Applicable if Label Image Code is ZPL,
     * EPL and SPL. Ignored for other Label Image Code types.
     */
    public function setLabelStockSize(LabelRecoveryLabelSpecificationLabelStockSize $labelStockSize): self
    {
        $this->labelStockSize = Some::create($labelStockSize);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): LabelRecoveryRequestLabelSpecification
    {
        return new LabelRecoveryRequestLabelSpecification(
            $this->hTTPUserAgent,
            $this->labelImageFormat,
            $this->labelStockSize,
            $this->additionalProperties,
        );
    }
}
