<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see LabelRecoveryImageImageFormat}.
 */
final class LabelRecoveryImageImageFormatBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $description
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private string $code, private Option $description, private array $additionalProperties)
    {
    }

    /**
     * Code representing the format in which the Forms are generated. Valid values: PDF = pdf.
     */
    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Description of the form image format code.
     */
    public function setDescription(string $description): self
    {
        $this->description = Some::create($description);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): LabelRecoveryImageImageFormat
    {
        return new LabelRecoveryImageImageFormat($this->code, $this->description, $this->additionalProperties);
    }
}
