<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class LabelDeliveryEMail implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(private string $eMailAddress, private array $additionalProperties)
    {
    }

    public static function builder(string $eMailAddress): LabelDeliveryEMailBuilder
    {
        return new LabelDeliveryEMailBuilder($eMailAddress, []);
    }

    /**
     * The destination eMail address for the Label Delivery.
     */
    public function getEMailAddress(): string
    {
        return $this->eMailAddress;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $eMailAddress = null;
        if (array_key_exists('EMailAddress', $data)) {
            $eMailAddressRaw = $data['EMailAddress'];
            if (!is_string($eMailAddressRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "EMailAddress" must be string, got %s.', get_debug_type($eMailAddressRaw)),
                );
            }
            $eMailAddress = $eMailAddressRaw;
        }
        $additionalProperties = array_diff_key($data, ['EMailAddress' => true]);
        if ($eMailAddress === null) {
            throw new MalformedDataException('Required property "EMailAddress" is missing from the document.');
        }

        return new self($eMailAddress, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['EMailAddress'] = $this->eMailAddress;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): LabelDeliveryEMailBuilder
    {
        return new LabelDeliveryEMailBuilder($this->eMailAddress, $this->additionalProperties);
    }
}
