<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see LabelResultsMailInnovationsLabelImage}.
 */
final class LabelResultsMailInnovationsLabelImageBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $hTMLImage
     * @param Option<string>           $pDF417
     * @param Option<string>           $internationalSignatureGraphicImage
     * @param Option<string>           $uRL
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private MailInnovationsLabelImageLabelImageFormat $labelImageFormat,
        private string $graphicImage,
        private Option $hTMLImage,
        private Option $pDF417,
        private Option $internationalSignatureGraphicImage,
        private Option $uRL,
        private array $additionalProperties,
    ) {
    }

    /**
     * The format of a label image byte stream.
     */
    public function setLabelImageFormat(MailInnovationsLabelImageLabelImageFormat $labelImageFormat): self
    {
        $this->labelImageFormat = $labelImageFormat;

        return $this;
    }

    /**
     * Base 64 encoded graphic image.
     */
    public function setGraphicImage(string $graphicImage): self
    {
        $this->graphicImage = $graphicImage;

        return $this;
    }

    /**
     * Base 64 encoded html browser image rendering software. This is only returned for GIF image
     * formats.
     */
    public function setHTMLImage(string $hTMLImage): self
    {
        $this->hTMLImage = Some::create($hTMLImage);

        return $this;
    }

    /**
     * PDF-417 is a two-dimensional barcode, which can store up to about 1,800 printable ASCII
     * characters or 1,100 binary characters per symbol. The symbol is rectangular. The PDF417 image
     * will be returned when the shipment is trans-border and the service option is one of the
     * following: Standard, Express Saver or Express Plus. The image is Base 64 encoded and only
     * returned for GIF image format.
     */
    public function setPDF417(string $pDF417): self
    {
        $this->pDF417 = Some::create($pDF417);

        return $this;
    }

    /**
     * Base 64 encoded graphic image of the Warsaw text and signature box. EPL2, ZPL and SPL labels.
     * The image will be returned for non-US based shipments. One image will be given per shipment
     * and it will be in the first PackageResults container.
     */
    public function setInternationalSignatureGraphicImage(string $internationalSignatureGraphicImage): self
    {
        $this->internationalSignatureGraphicImage = Some::create($internationalSignatureGraphicImage);

        return $this;
    }

    /**
     * This is only returned if the label link is requested to be returned and only at the first
     * package result Applicable for following types of shipments: Print/Electronic Return Label.
     */
    public function setURL(string $uRL): self
    {
        $this->uRL = Some::create($uRL);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): LabelResultsMailInnovationsLabelImage
    {
        return new LabelResultsMailInnovationsLabelImage(
            $this->labelImageFormat,
            $this->graphicImage,
            $this->hTMLImage,
            $this->pDF417,
            $this->internationalSignatureGraphicImage,
            $this->uRL,
            $this->additionalProperties,
        );
    }
}
