<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class LabelRecoveryRequestUPSPremiumCareForm implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(
        private string $pageSize,
        private string $printType,
        private array $additionalProperties,
    ) {
    }

    public static function builder(string $pageSize, string $printType): LabelRecoveryRequestUPSPremiumCareFormBuilder
    {
        return new LabelRecoveryRequestUPSPremiumCareFormBuilder($pageSize, $printType, []);
    }

    /**
     * Size of UPS Premium Care Form. Valid values: 01 = A4 Size 02 = Letter Size.
     */
    public function getPageSize(): string
    {
        return $this->pageSize;
    }

    /**
     * Format of UPS Premium Care Form. Valid values: 01 = PNG 02 = PDF.
     */
    public function getPrintType(): string
    {
        return $this->printType;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $pageSize = null;
        $printType = null;
        if (array_key_exists('PageSize', $data)) {
            $pageSizeRaw = $data['PageSize'];
            if (!is_string($pageSizeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "PageSize" must be string, got %s.', get_debug_type($pageSizeRaw)),
                );
            }
            $pageSize = $pageSizeRaw;
        }
        if (array_key_exists('PrintType', $data)) {
            $printTypeRaw = $data['PrintType'];
            if (!is_string($printTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "PrintType" must be string, got %s.', get_debug_type($printTypeRaw)),
                );
            }
            $printType = $printTypeRaw;
        }
        $additionalProperties = array_diff_key($data, ['PageSize' => true, 'PrintType' => true]);
        if ($pageSize === null) {
            throw new MalformedDataException('Required property "PageSize" is missing from the document.');
        }
        if ($printType === null) {
            throw new MalformedDataException('Required property "PrintType" is missing from the document.');
        }

        return new self($pageSize, $printType, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['PageSize'] = $this->pageSize;
        $dataArray['PrintType'] = $this->printType;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): LabelRecoveryRequestUPSPremiumCareFormBuilder
    {
        return new LabelRecoveryRequestUPSPremiumCareFormBuilder(
            $this->pageSize,
            $this->printType,
            $this->additionalProperties,
        );
    }
}
