<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class LabelRecoveryResponseTrackingCandidate implements SelfNormalizingModel
{
    /**
     * @param Option<string>                           $destinationPostalCode
     * @param Option<string>                           $destinationCountryCode
     * @param Option<TrackingCandidatePickupDateRange> $pickupDateRange
     * @param array<int|string, mixed>                 $additionalProperties
     */
    public function __construct(
        private string $trackingNumber,
        private Option $destinationPostalCode,
        private Option $destinationCountryCode,
        private Option $pickupDateRange,
        private array $additionalProperties,
    ) {
    }

    public static function builder(string $trackingNumber): LabelRecoveryResponseTrackingCandidateBuilder
    {
        return new LabelRecoveryResponseTrackingCandidateBuilder(
            $trackingNumber,
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Packaging Tracking Number Only supported for the web small package shipment so only supported
     * 18 digit.
     */
    public function getTrackingNumber(): string
    {
        return $this->trackingNumber;
    }

    /**
     * Destination postal code candidate.
     *
     * @return Option<string>
     */
    public function getDestinationPostalCode(): Option
    {
        return $this->destinationPostalCode;
    }

    /**
     * Destination country or territory code candidate, like US = USA, CA = Canada Must be valid ups
     * country or territory code. This is required, if MasterEUConsolidationIndicator is "1".
     *
     * @return Option<string>
     */
    public function getDestinationCountryCode(): Option
    {
        return $this->destinationCountryCode;
    }

    /**
     * A range of time the package was picked up.
     *
     * @return Option<TrackingCandidatePickupDateRange>
     */
    public function getPickupDateRange(): Option
    {
        return $this->pickupDateRange;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $trackingNumber = null;
        $destinationPostalCode = None::create();
        $destinationCountryCode = None::create();
        $pickupDateRange = None::create();
        if (array_key_exists('TrackingNumber', $data)) {
            $trackingNumberRaw = $data['TrackingNumber'];
            if (!is_string($trackingNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "TrackingNumber" must be string, got %s.', get_debug_type($trackingNumberRaw)),
                );
            }
            $trackingNumber = $trackingNumberRaw;
        }
        if (array_key_exists('DestinationPostalCode', $data) && $data['DestinationPostalCode'] !== null) {
            $destinationPostalCodeRaw = $data['DestinationPostalCode'];
            if (!is_string($destinationPostalCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "DestinationPostalCode" must be string, got %s.',
                        get_debug_type($destinationPostalCodeRaw),
                    ),
                );
            }
            $destinationPostalCode = Some::create($destinationPostalCodeRaw);
        }
        if (array_key_exists('DestinationCountryCode', $data) && $data['DestinationCountryCode'] !== null) {
            $destinationCountryCodeRaw = $data['DestinationCountryCode'];
            if (!is_string($destinationCountryCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "DestinationCountryCode" must be string, got %s.',
                        get_debug_type($destinationCountryCodeRaw),
                    ),
                );
            }
            $destinationCountryCode = Some::create($destinationCountryCodeRaw);
        }
        if (array_key_exists('PickupDateRange', $data) && $data['PickupDateRange'] !== null) {
            $pickupDateRangeRaw = $data['PickupDateRange'];
            if (!is_array($pickupDateRangeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "PickupDateRange" must be object, got %s.', get_debug_type($pickupDateRangeRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $pickupDateRangeRawTyped */
            $pickupDateRangeRawTyped = $pickupDateRangeRaw;
            $pickupDateRange = Some::create(TrackingCandidatePickupDateRange::fromArray($pickupDateRangeRawTyped));
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'TrackingNumber' => true,
                'DestinationPostalCode' => true,
                'DestinationCountryCode' => true,
                'PickupDateRange' => true,
            ],
        );
        if ($trackingNumber === null) {
            throw new MalformedDataException('Required property "TrackingNumber" is missing from the document.');
        }

        return new self(
            $trackingNumber,
            $destinationPostalCode,
            $destinationCountryCode,
            $pickupDateRange,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['TrackingNumber'] = $this->trackingNumber;
        $destinationPostalCodeOption = $this->destinationPostalCode;
        if ($destinationPostalCodeOption->isDefined()) {
            $destinationPostalCode = $destinationPostalCodeOption->get();
            $dataArray['DestinationPostalCode'] = $destinationPostalCode;
        }
        $destinationCountryCodeOption = $this->destinationCountryCode;
        if ($destinationCountryCodeOption->isDefined()) {
            $destinationCountryCode = $destinationCountryCodeOption->get();
            $dataArray['DestinationCountryCode'] = $destinationCountryCode;
        }
        $pickupDateRangeOption = $this->pickupDateRange;
        if ($pickupDateRangeOption->isDefined()) {
            $pickupDateRange = $pickupDateRangeOption->get();
            $dataArray['PickupDateRange'] = $normalizationTarget->model($pickupDateRange);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): LabelRecoveryResponseTrackingCandidateBuilder
    {
        return new LabelRecoveryResponseTrackingCandidateBuilder(
            $this->trackingNumber,
            $this->destinationPostalCode,
            $this->destinationCountryCode,
            $this->pickupDateRange,
            $this->additionalProperties,
        );
    }
}
