<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class LRResponseResponseStatus implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(private string $code, private string $description, private array $additionalProperties)
    {
    }

    public static function builder(string $code, string $description): LRResponseResponseStatusBuilder
    {
        return new LRResponseResponseStatusBuilder($code, $description, []);
    }

    /**
     * Identifies the success status of the transaction. 1= Success.
     */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * Describes Response Status Code. Returns the text "Success".
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $code = null;
        $description = null;
        if (array_key_exists('Code', $data)) {
            $codeRaw = $data['Code'];
            if (!is_string($codeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Code" must be string, got %s.', get_debug_type($codeRaw)),
                );
            }
            $code = $codeRaw;
        }
        if (array_key_exists('Description', $data)) {
            $descriptionRaw = $data['Description'];
            if (!is_string($descriptionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Description" must be string, got %s.', get_debug_type($descriptionRaw)),
                );
            }
            $description = $descriptionRaw;
        }
        $additionalProperties = array_diff_key($data, ['Code' => true, 'Description' => true]);
        if ($code === null) {
            throw new MalformedDataException('Required property "Code" is missing from the document.');
        }
        if ($description === null) {
            throw new MalformedDataException('Required property "Description" is missing from the document.');
        }

        return new self($code, $description, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['Code'] = $this->code;
        $dataArray['Description'] = $this->description;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): LRResponseResponseStatusBuilder
    {
        return new LRResponseResponseStatusBuilder($this->code, $this->description, $this->additionalProperties);
    }
}
