<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class LTLOtherCharges implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(
        private string $monetaryValue,
        private string $chargeDescription,
        private array $additionalProperties,
    ) {
    }

    public static function builder(string $monetaryValue, string $chargeDescription): LTLOtherChargesBuilder
    {
        return new LTLOtherChargesBuilder($monetaryValue, $chargeDescription, []);
    }

    /**
     * The amount the shipper or receiver pays to cover the cost associated with the LTL Charges.
     */
    public function getMonetaryValue(): string
    {
        return $this->monetaryValue;
    }

    /**
     * Description of what the other charges are for.
     */
    public function getChargeDescription(): string
    {
        return $this->chargeDescription;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $monetaryValue = null;
        $chargeDescription = null;
        if (array_key_exists('MonetaryValue', $data)) {
            $monetaryValueRaw = $data['MonetaryValue'];
            if (!is_string($monetaryValueRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "MonetaryValue" must be string, got %s.', get_debug_type($monetaryValueRaw)),
                );
            }
            $monetaryValue = $monetaryValueRaw;
        }
        if (array_key_exists('ChargeDescription', $data)) {
            $chargeDescriptionRaw = $data['ChargeDescription'];
            if (!is_string($chargeDescriptionRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "ChargeDescription" must be string, got %s.',
                        get_debug_type($chargeDescriptionRaw),
                    ),
                );
            }
            $chargeDescription = $chargeDescriptionRaw;
        }
        $additionalProperties = array_diff_key($data, ['MonetaryValue' => true, 'ChargeDescription' => true]);
        if ($monetaryValue === null) {
            throw new MalformedDataException('Required property "MonetaryValue" is missing from the document.');
        }
        if ($chargeDescription === null) {
            throw new MalformedDataException('Required property "ChargeDescription" is missing from the document.');
        }

        return new self($monetaryValue, $chargeDescription, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['MonetaryValue'] = $this->monetaryValue;
        $dataArray['ChargeDescription'] = $this->chargeDescription;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): LTLOtherChargesBuilder
    {
        return new LTLOtherChargesBuilder($this->monetaryValue, $this->chargeDescription, $this->additionalProperties);
    }
}
