<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see MasterSoldTo}.
 */
final class MasterSoldToBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $attentionName
     * @param Option<string>           $taxIdentificationNumber
     * @param Option<TradeDirectPhone> $phone
     * @param Option<string>           $option
     * @param Option<string>           $accountNumber
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $name,
        private TradeDirectAddress $address,
        private string $emailAddress,
        private Option $attentionName,
        private Option $taxIdentificationNumber,
        private Option $phone,
        private Option $option,
        private Option $accountNumber,
        private array $additionalProperties,
    ) {
    }

    /**
     * Master Sold To Company Name.
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Contains the address details including street address, city, state or province code, postal
     * code, and country code.
     */
    public function setAddress(TradeDirectAddress $address): self
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Master Sold To Email Address.
     */
    public function setEmailAddress(string $emailAddress): self
    {
        $this->emailAddress = $emailAddress;

        return $this;
    }

    /**
     * Master Sold to Contact Name.
     */
    public function setAttentionName(string $attentionName): self
    {
        $this->attentionName = Some::create($attentionName);

        return $this;
    }

    /**
     * Master Sold To Tax Identification Number. This element has been deprecated, replacement can
     * be found in the GlobalTaxInformation container.
     *
     * @deprecated
     */
    public function setTaxIdentificationNumber(string $taxIdentificationNumber): self
    {
        $this->taxIdentificationNumber = Some::create($taxIdentificationNumber);

        return $this;
    }

    /**
     * Contains the phone details including the phone number and extension.
     */
    public function setPhone(TradeDirectPhone $phone): self
    {
        $this->phone = Some::create($phone);

        return $this;
    }

    /**
     * The text associated with the code will be printed in the sold to section of the USMCA form.
     * The values indicate the following: 01 – Unknown. Applies to USMCA form. Possible Values are
     * 01 and 02.
     */
    public function setOption(string $option): self
    {
        $this->option = Some::create($option);

        return $this;
    }

    /**
     * Master Sold To Account Number.
     */
    public function setAccountNumber(string $accountNumber): self
    {
        $this->accountNumber = Some::create($accountNumber);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): MasterSoldTo
    {
        return new MasterSoldTo(
            $this->name,
            $this->address,
            $this->emailAddress,
            $this->attentionName,
            $this->taxIdentificationNumber,
            $this->phone,
            $this->option,
            $this->accountNumber,
            $this->additionalProperties,
        );
    }
}
