<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class MasterTradeComplianceDetails implements SelfNormalizingModel
{
    /**
     * @param Option<MasterTradeComplianceDetailsTermsOfShipment|UnknownEnumValue<string>>      $termsOfShipment
     * @param Option<string>                                                                    $reasonForExport
     * @param Option<string>                                                                    $comments
     * @param Option<MasterTradeComplianceDetailsDeclarationStatement|UnknownEnumValue<string>> $declarationStatement
     * @param array<int|string, mixed>                                                          $additionalProperties
     */
    public function __construct(
        private Option $termsOfShipment,
        private Option $reasonForExport,
        private Option $comments,
        private Option $declarationStatement,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): MasterTradeComplianceDetailsBuilder
    {
        return new MasterTradeComplianceDetailsBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * The terms of sale for the invoice.
     *
     * Valid values:
     *
     * - CFR = Cost and Freight
     * - CIF = Cost Insurance and Freight
     * - CIP = Carriage and Insurance Paid
     * - CPT = Carriage Paid To
     * - DAF = Delivered at Frontier
     * - DAP = Delivered at Place
     * - DAT = Delivered at Terminal
     * - DDP = Delivery Duty Paid
     * - DDU = Delivery Duty Unpaid
     * - DEQ = Delivered Ex Quay
     * - DES = Delivered Ex Ship
     * - EXW = Ex Works
     * - FAS = Free Alongside Ship
     * - FCA = Free Carrier
     * - FOB = Free On Board
     *
     * @return Option<MasterTradeComplianceDetailsTermsOfShipment|UnknownEnumValue<string>>
     */
    public function getTermsOfShipment(): Option
    {
        return $this->termsOfShipment;
    }

    /**
     * The reason for export to go on the invoice.
     *
     * @return Option<string>
     */
    public function getReasonForExport(): Option
    {
        return $this->reasonForExport;
    }

    /**
     * Additional comments to be included on the invoice.
     *
     * @return Option<string>
     */
    public function getComments(): Option
    {
        return $this->comments;
    }

    /**
     * The type of declaration statement. Can be invoice or USMCA.
     *
     * Valid values:
     *
     * - Invoice = Invoice declaration
     * - USMCA = USMCA declaration
     *
     * @return Option<MasterTradeComplianceDetailsDeclarationStatement|UnknownEnumValue<string>>
     */
    public function getDeclarationStatement(): Option
    {
        return $this->declarationStatement;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $termsOfShipment = None::create();
        $reasonForExport = None::create();
        $comments = None::create();
        $declarationStatement = None::create();
        if (array_key_exists('TermsOfShipment', $data) && $data['TermsOfShipment'] !== null) {
            $termsOfShipmentRaw = $data['TermsOfShipment'];
            if (!is_string($termsOfShipmentRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "TermsOfShipment" must be string, got %s.', get_debug_type($termsOfShipmentRaw)),
                );
            }
            $termsOfShipment = Some::create(
                MasterTradeComplianceDetailsTermsOfShipment::tryFrom($termsOfShipmentRaw)
                    ?? UnknownEnumValue::of($termsOfShipmentRaw),
            );
        }
        if (array_key_exists('ReasonForExport', $data) && $data['ReasonForExport'] !== null) {
            $reasonForExportRaw = $data['ReasonForExport'];
            if (!is_string($reasonForExportRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "ReasonForExport" must be string, got %s.', get_debug_type($reasonForExportRaw)),
                );
            }
            $reasonForExport = Some::create($reasonForExportRaw);
        }
        if (array_key_exists('Comments', $data) && $data['Comments'] !== null) {
            $commentsRaw = $data['Comments'];
            if (!is_string($commentsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Comments" must be string, got %s.', get_debug_type($commentsRaw)),
                );
            }
            $comments = Some::create($commentsRaw);
        }
        if (array_key_exists('DeclarationStatement', $data) && $data['DeclarationStatement'] !== null) {
            $declarationStatementRaw = $data['DeclarationStatement'];
            if (!is_string($declarationStatementRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "DeclarationStatement" must be string, got %s.',
                        get_debug_type($declarationStatementRaw),
                    ),
                );
            }
            $declarationStatement = Some::create(
                MasterTradeComplianceDetailsDeclarationStatement::tryFrom($declarationStatementRaw)
                    ?? UnknownEnumValue::of($declarationStatementRaw),
            );
        }
        $additionalProperties = array_diff_key(
            $data,
            ['TermsOfShipment' => true, 'ReasonForExport' => true, 'Comments' => true, 'DeclarationStatement' => true],
        );

        return new self($termsOfShipment, $reasonForExport, $comments, $declarationStatement, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $termsOfShipmentOption = $this->termsOfShipment;
        if ($termsOfShipmentOption->isDefined()) {
            $termsOfShipment = $termsOfShipmentOption->get();
            $dataArray['TermsOfShipment'] = $termsOfShipment->value;
        }
        $reasonForExportOption = $this->reasonForExport;
        if ($reasonForExportOption->isDefined()) {
            $reasonForExport = $reasonForExportOption->get();
            $dataArray['ReasonForExport'] = $reasonForExport;
        }
        $commentsOption = $this->comments;
        if ($commentsOption->isDefined()) {
            $comments = $commentsOption->get();
            $dataArray['Comments'] = $comments;
        }
        $declarationStatementOption = $this->declarationStatement;
        if ($declarationStatementOption->isDefined()) {
            $declarationStatement = $declarationStatementOption->get();
            $dataArray['DeclarationStatement'] = $declarationStatement->value;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): MasterTradeComplianceDetailsBuilder
    {
        return new MasterTradeComplianceDetailsBuilder(
            $this->termsOfShipment,
            $this->reasonForExport,
            $this->comments,
            $this->declarationStatement,
            $this->additionalProperties,
        );
    }
}
