<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

/**
 * Builds a {@see NegotiatedRateChargesTaxCharges}.
 */
final class NegotiatedRateChargesTaxChargesBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $type,
        private string $monetaryValue,
        private array $additionalProperties,
    ) {
    }

    /**
     * Tax Type code. The code represents the type of Tax applied to a shipment. Refer to Tax Type
     * Values/Abbreviations in the Appendix for valid values.
     */
    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Tax Monetary Value represent the Tax amount. Valid values are from 0 to 99999999999999.99.
     */
    public function setMonetaryValue(string $monetaryValue): self
    {
        $this->monetaryValue = $monetaryValue;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): NegotiatedRateChargesTaxCharges
    {
        return new NegotiatedRateChargesTaxCharges($this->type, $this->monetaryValue, $this->additionalProperties);
    }
}
