<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

/**
 * Builds a {@see NotificationVoiceMessage}.
 */
final class NotificationVoiceMessageBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private string $phoneNumber, private array $additionalProperties)
    {
    }

    /**
     * Phone number for receiving Voice Alternate Delivery Location notification and UAP Shipper
     * notification.
     */
    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): NotificationVoiceMessage
    {
        return new NotificationVoiceMessage($this->phoneNumber, $this->additionalProperties);
    }
}
