<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class PackageServiceOptionsHazMat implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $packagingTypeQuantity
     * @param Option<string>           $recordIdentifier1
     * @param Option<string>           $recordIdentifier2
     * @param Option<string>           $recordIdentifier3
     * @param Option<string>           $subRiskClass
     * @param Option<string>           $aDRItemNumber
     * @param Option<string>           $aDRPackingGroupLetter
     * @param Option<string>           $technicalName
     * @param Option<string>           $hazardLabelRequired
     * @param Option<string>           $classDivisionNumber
     * @param Option<string>           $referenceNumber
     * @param Option<string>           $quantity
     * @param Option<string>           $uOM
     * @param Option<string>           $packagingType
     * @param Option<string>           $iDNumber
     * @param Option<string>           $additionalDescription
     * @param Option<string>           $packagingGroupType
     * @param Option<string>           $packagingInstructionCode
     * @param Option<string>           $emergencyPhone
     * @param Option<string>           $emergencyContact
     * @param Option<string>           $reportableQuantity
     * @param Option<string>           $commodityRegulatedLevelCode
     * @param Option<string>           $transportCategory
     * @param Option<string>           $tunnelRestrictionCode
     * @param Option<string>           $chemicalRecordIdentifier
     * @param Option<string>           $localTechnicalName
     * @param Option<string>           $localProperShippingName
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $properShippingName,
        private string $regulationSet,
        private string $transportationMode,
        private Option $packagingTypeQuantity,
        private Option $recordIdentifier1,
        private Option $recordIdentifier2,
        private Option $recordIdentifier3,
        private Option $subRiskClass,
        private Option $aDRItemNumber,
        private Option $aDRPackingGroupLetter,
        private Option $technicalName,
        private Option $hazardLabelRequired,
        private Option $classDivisionNumber,
        private Option $referenceNumber,
        private Option $quantity,
        private Option $uOM,
        private Option $packagingType,
        private Option $iDNumber,
        private Option $additionalDescription,
        private Option $packagingGroupType,
        private Option $packagingInstructionCode,
        private Option $emergencyPhone,
        private Option $emergencyContact,
        private Option $reportableQuantity,
        private Option $commodityRegulatedLevelCode,
        private Option $transportCategory,
        private Option $tunnelRestrictionCode,
        private Option $chemicalRecordIdentifier,
        private Option $localTechnicalName,
        private Option $localProperShippingName,
        private array $additionalProperties,
    ) {
    }

    public static function builder(
        string $properShippingName,
        string $regulationSet,
        string $transportationMode,
    ): PackageServiceOptionsHazMatBuilder {
        return new PackageServiceOptionsHazMatBuilder(
            $properShippingName,
            $regulationSet,
            $transportationMode,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * The number of pieces of the specific commodity. Required if CommodityRegulatedLevelCode = LQ
     * or FR. Valid values are 1 to 999.
     *
     * @return Option<string>
     */
    public function getPackagingTypeQuantity(): Option
    {
        return $this->packagingTypeQuantity;
    }

    /**
     * Reserved for future use.
     *
     * @return Option<string>
     */
    public function getRecordIdentifier1(): Option
    {
        return $this->recordIdentifier1;
    }

    /**
     * Reserved for future use.
     *
     * @return Option<string>
     */
    public function getRecordIdentifier2(): Option
    {
        return $this->recordIdentifier2;
    }

    /**
     * Reserved for future use.
     *
     * @return Option<string>
     */
    public function getRecordIdentifier3(): Option
    {
        return $this->recordIdentifier3;
    }

    /**
     * Recommended if CommodityRegulatedLevelCode = LQ or FR and if the field applies to the
     * material by regulation.
     *
     * Secondary hazardous characteristics of a package. (There can be more than one – separate each
     * with a comma).
     *
     * @return Option<string>
     */
    public function getSubRiskClass(): Option
    {
        return $this->subRiskClass;
    }

    /**
     * The type of regulated good for an ADR package where ADR is for Europe to Europe ground
     * movement.
     *
     * @return Option<string>
     */
    public function getADRItemNumber(): Option
    {
        return $this->aDRItemNumber;
    }

    /**
     * Required if the field applies to the material by regulation. Field input is Arabic numerals,
     * output is Roman numerals. Will be shown in Roman Numerals. Valid values:
     * - "1" = "I",
     * - "2" = "II",
     * - "3" = "III",
     * - and blank.
     *
     * @return Option<string>
     */
    public function getADRPackingGroupLetter(): Option
    {
        return $this->aDRPackingGroupLetter;
    }

    /**
     * The technical name (when required) for the specified commodity. Recommended if
     * CommodityRegulatedLevelCode = LQ or FR and if the field applies to the material by
     * regulation.
     *
     * @return Option<string>
     */
    public function getTechnicalName(): Option
    {
        return $this->technicalName;
    }

    /**
     * Defines the type of label that is required on the package for the commodity.
     *
     * Not applicable if CommodityRegulatedLevelCode = LR or EQ.
     *
     * @return Option<string>
     */
    public function getHazardLabelRequired(): Option
    {
        return $this->hazardLabelRequired;
    }

    /**
     * This is the hazard class associated to the specified commodity.
     *
     * Required if CommodityRegulatedLevelCode is 'EQ', 'LQ' or 'FR'
     *
     * @return Option<string>
     */
    public function getClassDivisionNumber(): Option
    {
        return $this->classDivisionNumber;
    }

    /**
     * Optional reference number. It will be displayed only on label.
     *
     * @return Option<string>
     */
    public function getReferenceNumber(): Option
    {
        return $this->referenceNumber;
    }

    /**
     * Required if CommodityRegulatedLevelCode = EQ, LQ or FR. The numerical value of the mass
     * capacity of the regulated good. Should be more than 0.0. Valid characters are 0-9 and "."
     * (Decimal point). Limit to 1 digit after the decimal. The maximum length of the field is 5
     * including "." (Decimal point) and can hold up to 1 decimal place.
     *
     * @return Option<string>
     */
    public function getQuantity(): Option
    {
        return $this->quantity;
    }

    /**
     * Required if CommodityRegulatedLevelCode = LQ, EQ or FR. The unit of measure used for the mass
     * capacity of the regulated good.
     *
     * For Example: ml, L, g, mg, kg, cylinder, pound, pint, quart, gallon, ounce etc.
     *
     * @return Option<string>
     */
    public function getUOM(): Option
    {
        return $this->uOM;
    }

    /**
     * The type of package used to contain the regulated good. (Ex: Fiberboard Box). Required if
     * CommodityRegulatedLevelCode = LQ or FR. Ex. FIBERBOARD BOX, WOOD(EN) BOX, PLASTIC JERRICAN,
     * METAL BOX, STEEL DRUM, OTHER, PLASTIC BOX, PLASTIC DRUM, STYROFOAM BOX, CYLINDERS,
     * ENVIROTAINER, PLYWOOD BOX, ALUMINUM DRUM, ALUMINUM CYLINDERS, PLASTIC PAIL, PLYWOOD DRUM,
     * FIBER DRUM, STEEL JERRICAN, ALUMINUM JERRICAN, STEEL BOX, CARTON, ALUMINUM BOX.
     *
     * @return Option<string>
     */
    public function getPackagingType(): Option
    {
        return $this->packagingType;
    }

    /**
     * This is the ID number (UN/NA/ID) for the specified commodity. Required if
     * CommodityRegulatedLevelCode = LR, LQ or FR and if the field applies to the material by
     * regulation. UN/NA/ID Identification Number assigned to the specified regulated good. (Include
     * the UN/NA/ID as part of the entry).
     *
     * @return Option<string>
     */
    public function getIDNumber(): Option
    {
        return $this->iDNumber;
    }

    /**
     * The Proper Shipping Name assigned by ADR, CFR or IATA. Required if
     * CommodityRegulatedLevelCode = LR, LQ or FR.
     */
    public function getProperShippingName(): string
    {
        return $this->properShippingName;
    }

    /**
     * Additional remarks or special provision information. Recommended if
     * CommodityRegulatedLevelCode = LQ or FR and if the field applies to the material by
     * regulation.
     *
     * Additional information that may be required by regulation about a hazardous material, such
     * as, "Limited Quantity", DOT-SP numbers, EX numbers.
     *
     * @return Option<string>
     */
    public function getAdditionalDescription(): Option
    {
        return $this->additionalDescription;
    }

    /**
     * This is the packing group category associated to the specified commodity. Recommended if
     * CommodityRegulatedLevelCode = LQ or FR and if the field applies to the material by
     * regulation. Must be shown in Roman Numerals. Valid values: I II III blank.
     *
     * @return Option<string>
     */
    public function getPackagingGroupType(): Option
    {
        return $this->packagingGroupType;
    }

    /**
     * The packing instructions related to the chemical record. Required if
     * CommodityRegulatedLevelCode = LQ or FR and if the field applies to the material by
     * regulation.
     *
     * @return Option<string>
     */
    public function getPackagingInstructionCode(): Option
    {
        return $this->packagingInstructionCode;
    }

    /**
     * 24 Hour Emergency Phone Number of the shipper. Valid values for this field are (0) through
     * (9) with trailing blanks. For numbers within the U.S., the layout is 1, area code, 7-digit
     * number. For all other countries or territories the layout is country or territory code, area
     * code, number.
     *
     * The following are restricted in the phone number period ".", dash "-", plus sign "+" and
     * conventional parentheses "(" and ")", "EXT" or "OPT"
     *
     * @return Option<string>
     */
    public function getEmergencyPhone(): Option
    {
        return $this->emergencyPhone;
    }

    /**
     * The emergency information, contact name and/or contract number, required to be communicated
     * when a call is placed to the EmergencyPhoneNumber. The information is required if there is a
     * value in the EmergencyPhoneNumber field above and the shipment is with a US50 or PR origin
     * and/or destination and the RegulationSet is IATA.
     *
     * @return Option<string>
     */
    public function getEmergencyContact(): Option
    {
        return $this->emergencyContact;
    }

    /**
     * Recommended if CommodityRegulatedLevelCode = LQ or FR and if the field applies to the
     * material by regulation. If reportable quantity is met, 'RQ' should be entered.
     *
     * @return Option<string>
     */
    public function getReportableQuantity(): Option
    {
        return $this->reportableQuantity;
    }

    /**
     * The Regulatory set associated with every regulated shipment. It must be same across the
     * shipment. Valid values: ADR = Europe to Europe Ground Movement CFR = HazMat regulated by US
     * Dept. of Transportation within the U.S. or ground shipments to Canada IATA= Worldwide Air
     * movement TDG= Canada to Canada ground movement or Canada to U.S. standard movement. Valid
     * values are ADR, CFR, IATA and TDG. For multiple Chemical Records per package or multiple
     * packages containing different RegulationSet, RegulationSet of first Chemical Record would be
     * considered for validating and rating the entire shipment.
     */
    public function getRegulationSet(): string
    {
        return $this->regulationSet;
    }

    /**
     * Not applicable for ADR regulation set. Required for any other regulation set. Declares that a
     * package was prepared according to ground passenger aircraft or cargo aircraft only. Valid
     * values: Highway=Highway Ground=Ground PAX=Passenger Aircraft Passenger Aircraft=Passenger
     * Aircraft CAO=Cargo Aircraft Only Cargo Aircraft Only=Cargo Aircraft Only Valid entries
     * include: Highway, Ground, PAX, Passenger Aircraft, CAO and Cargo Aircraft Only.
     */
    public function getTransportationMode(): string
    {
        return $this->transportationMode;
    }

    /**
     * Indicates the type of commodity - Fully Regulated (FR), Limited Quantity (LQ), Excepted
     * Quantity (EQ) or Lightly Regulated (LR). Valid values are LR, FR, LQ and EQ. Required for
     * subversion 1701 or greater. LR and EQ are validated if subversion is 1701 or greater. FR, LQ
     * will be validated if subversion is 1807 or greater.
     *
     * @return Option<string>
     */
    public function getCommodityRegulatedLevelCode(): Option
    {
        return $this->commodityRegulatedLevelCode;
    }

    /**
     * Transport Category. Valid values are 0 to 4.
     *
     * @return Option<string>
     */
    public function getTransportCategory(): Option
    {
        return $this->transportCategory;
    }

    /**
     * Defines what is restricted to pass through a tunnel.
     *
     * @return Option<string>
     */
    public function getTunnelRestrictionCode(): Option
    {
        return $this->tunnelRestrictionCode;
    }

    /**
     * Identifies the Chemical Record. Required if SubVersion is greater than or equal to 1701.
     *
     * @return Option<string>
     */
    public function getChemicalRecordIdentifier(): Option
    {
        return $this->chemicalRecordIdentifier;
    }

    /**
     * Technical name in local language.
     *
     * @return Option<string>
     */
    public function getLocalTechnicalName(): Option
    {
        return $this->localTechnicalName;
    }

    /**
     * Proper shipping name in local langauge.
     *
     * @return Option<string>
     */
    public function getLocalProperShippingName(): Option
    {
        return $this->localProperShippingName;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $packagingTypeQuantity = None::create();
        $recordIdentifier1 = None::create();
        $recordIdentifier2 = None::create();
        $recordIdentifier3 = None::create();
        $subRiskClass = None::create();
        $aDRItemNumber = None::create();
        $aDRPackingGroupLetter = None::create();
        $technicalName = None::create();
        $hazardLabelRequired = None::create();
        $classDivisionNumber = None::create();
        $referenceNumber = None::create();
        $quantity = None::create();
        $uOM = None::create();
        $packagingType = None::create();
        $iDNumber = None::create();
        $properShippingName = null;
        $additionalDescription = None::create();
        $packagingGroupType = None::create();
        $packagingInstructionCode = None::create();
        $emergencyPhone = None::create();
        $emergencyContact = None::create();
        $reportableQuantity = None::create();
        $regulationSet = null;
        $transportationMode = null;
        $commodityRegulatedLevelCode = None::create();
        $transportCategory = None::create();
        $tunnelRestrictionCode = None::create();
        $chemicalRecordIdentifier = None::create();
        $localTechnicalName = None::create();
        $localProperShippingName = None::create();
        if (array_key_exists('PackagingTypeQuantity', $data) && $data['PackagingTypeQuantity'] !== null) {
            $packagingTypeQuantityRaw = $data['PackagingTypeQuantity'];
            if (!is_string($packagingTypeQuantityRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "PackagingTypeQuantity" must be string, got %s.',
                        get_debug_type($packagingTypeQuantityRaw),
                    ),
                );
            }
            $packagingTypeQuantity = Some::create($packagingTypeQuantityRaw);
        }
        if (array_key_exists('RecordIdentifier1', $data) && $data['RecordIdentifier1'] !== null) {
            $recordIdentifier1Raw = $data['RecordIdentifier1'];
            if (!is_string($recordIdentifier1Raw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "RecordIdentifier1" must be string, got %s.',
                        get_debug_type($recordIdentifier1Raw),
                    ),
                );
            }
            $recordIdentifier1 = Some::create($recordIdentifier1Raw);
        }
        if (array_key_exists('RecordIdentifier2', $data) && $data['RecordIdentifier2'] !== null) {
            $recordIdentifier2Raw = $data['RecordIdentifier2'];
            if (!is_string($recordIdentifier2Raw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "RecordIdentifier2" must be string, got %s.',
                        get_debug_type($recordIdentifier2Raw),
                    ),
                );
            }
            $recordIdentifier2 = Some::create($recordIdentifier2Raw);
        }
        if (array_key_exists('RecordIdentifier3', $data) && $data['RecordIdentifier3'] !== null) {
            $recordIdentifier3Raw = $data['RecordIdentifier3'];
            if (!is_string($recordIdentifier3Raw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "RecordIdentifier3" must be string, got %s.',
                        get_debug_type($recordIdentifier3Raw),
                    ),
                );
            }
            $recordIdentifier3 = Some::create($recordIdentifier3Raw);
        }
        if (array_key_exists('SubRiskClass', $data) && $data['SubRiskClass'] !== null) {
            $subRiskClassRaw = $data['SubRiskClass'];
            if (!is_string($subRiskClassRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "SubRiskClass" must be string, got %s.', get_debug_type($subRiskClassRaw)),
                );
            }
            $subRiskClass = Some::create($subRiskClassRaw);
        }
        if (array_key_exists('aDRItemNumber', $data) && $data['aDRItemNumber'] !== null) {
            $aDRItemNumberRaw = $data['aDRItemNumber'];
            if (!is_string($aDRItemNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "aDRItemNumber" must be string, got %s.', get_debug_type($aDRItemNumberRaw)),
                );
            }
            $aDRItemNumber = Some::create($aDRItemNumberRaw);
        }
        if (array_key_exists('aDRPackingGroupLetter', $data) && $data['aDRPackingGroupLetter'] !== null) {
            $aDRPackingGroupLetterRaw = $data['aDRPackingGroupLetter'];
            if (!is_string($aDRPackingGroupLetterRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "aDRPackingGroupLetter" must be string, got %s.',
                        get_debug_type($aDRPackingGroupLetterRaw),
                    ),
                );
            }
            $aDRPackingGroupLetter = Some::create($aDRPackingGroupLetterRaw);
        }
        if (array_key_exists('TechnicalName', $data) && $data['TechnicalName'] !== null) {
            $technicalNameRaw = $data['TechnicalName'];
            if (!is_string($technicalNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "TechnicalName" must be string, got %s.', get_debug_type($technicalNameRaw)),
                );
            }
            $technicalName = Some::create($technicalNameRaw);
        }
        if (array_key_exists('HazardLabelRequired', $data) && $data['HazardLabelRequired'] !== null) {
            $hazardLabelRequiredRaw = $data['HazardLabelRequired'];
            if (!is_string($hazardLabelRequiredRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "HazardLabelRequired" must be string, got %s.',
                        get_debug_type($hazardLabelRequiredRaw),
                    ),
                );
            }
            $hazardLabelRequired = Some::create($hazardLabelRequiredRaw);
        }
        if (array_key_exists('ClassDivisionNumber', $data) && $data['ClassDivisionNumber'] !== null) {
            $classDivisionNumberRaw = $data['ClassDivisionNumber'];
            if (!is_string($classDivisionNumberRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "ClassDivisionNumber" must be string, got %s.',
                        get_debug_type($classDivisionNumberRaw),
                    ),
                );
            }
            $classDivisionNumber = Some::create($classDivisionNumberRaw);
        }
        if (array_key_exists('ReferenceNumber', $data) && $data['ReferenceNumber'] !== null) {
            $referenceNumberRaw = $data['ReferenceNumber'];
            if (!is_string($referenceNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "ReferenceNumber" must be string, got %s.', get_debug_type($referenceNumberRaw)),
                );
            }
            $referenceNumber = Some::create($referenceNumberRaw);
        }
        if (array_key_exists('Quantity', $data) && $data['Quantity'] !== null) {
            $quantityRaw = $data['Quantity'];
            if (!is_string($quantityRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Quantity" must be string, got %s.', get_debug_type($quantityRaw)),
                );
            }
            $quantity = Some::create($quantityRaw);
        }
        if (array_key_exists('UOM', $data) && $data['UOM'] !== null) {
            $uOMRaw = $data['UOM'];
            if (!is_string($uOMRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "UOM" must be string, got %s.', get_debug_type($uOMRaw)),
                );
            }
            $uOM = Some::create($uOMRaw);
        }
        if (array_key_exists('PackagingType', $data) && $data['PackagingType'] !== null) {
            $packagingTypeRaw = $data['PackagingType'];
            if (!is_string($packagingTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "PackagingType" must be string, got %s.', get_debug_type($packagingTypeRaw)),
                );
            }
            $packagingType = Some::create($packagingTypeRaw);
        }
        if (array_key_exists('IDNumber', $data) && $data['IDNumber'] !== null) {
            $iDNumberRaw = $data['IDNumber'];
            if (!is_string($iDNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "IDNumber" must be string, got %s.', get_debug_type($iDNumberRaw)),
                );
            }
            $iDNumber = Some::create($iDNumberRaw);
        }
        if (array_key_exists('ProperShippingName', $data)) {
            $properShippingNameRaw = $data['ProperShippingName'];
            if (!is_string($properShippingNameRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "ProperShippingName" must be string, got %s.',
                        get_debug_type($properShippingNameRaw),
                    ),
                );
            }
            $properShippingName = $properShippingNameRaw;
        }
        if (array_key_exists('AdditionalDescription', $data) && $data['AdditionalDescription'] !== null) {
            $additionalDescriptionRaw = $data['AdditionalDescription'];
            if (!is_string($additionalDescriptionRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "AdditionalDescription" must be string, got %s.',
                        get_debug_type($additionalDescriptionRaw),
                    ),
                );
            }
            $additionalDescription = Some::create($additionalDescriptionRaw);
        }
        if (array_key_exists('PackagingGroupType', $data) && $data['PackagingGroupType'] !== null) {
            $packagingGroupTypeRaw = $data['PackagingGroupType'];
            if (!is_string($packagingGroupTypeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "PackagingGroupType" must be string, got %s.',
                        get_debug_type($packagingGroupTypeRaw),
                    ),
                );
            }
            $packagingGroupType = Some::create($packagingGroupTypeRaw);
        }
        if (array_key_exists('PackagingInstructionCode', $data) && $data['PackagingInstructionCode'] !== null) {
            $packagingInstructionCodeRaw = $data['PackagingInstructionCode'];
            if (!is_string($packagingInstructionCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "PackagingInstructionCode" must be string, got %s.',
                        get_debug_type($packagingInstructionCodeRaw),
                    ),
                );
            }
            $packagingInstructionCode = Some::create($packagingInstructionCodeRaw);
        }
        if (array_key_exists('EmergencyPhone', $data) && $data['EmergencyPhone'] !== null) {
            $emergencyPhoneRaw = $data['EmergencyPhone'];
            if (!is_string($emergencyPhoneRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "EmergencyPhone" must be string, got %s.', get_debug_type($emergencyPhoneRaw)),
                );
            }
            $emergencyPhone = Some::create($emergencyPhoneRaw);
        }
        if (array_key_exists('EmergencyContact', $data) && $data['EmergencyContact'] !== null) {
            $emergencyContactRaw = $data['EmergencyContact'];
            if (!is_string($emergencyContactRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "EmergencyContact" must be string, got %s.',
                        get_debug_type($emergencyContactRaw),
                    ),
                );
            }
            $emergencyContact = Some::create($emergencyContactRaw);
        }
        if (array_key_exists('ReportableQuantity', $data) && $data['ReportableQuantity'] !== null) {
            $reportableQuantityRaw = $data['ReportableQuantity'];
            if (!is_string($reportableQuantityRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "ReportableQuantity" must be string, got %s.',
                        get_debug_type($reportableQuantityRaw),
                    ),
                );
            }
            $reportableQuantity = Some::create($reportableQuantityRaw);
        }
        if (array_key_exists('RegulationSet', $data)) {
            $regulationSetRaw = $data['RegulationSet'];
            if (!is_string($regulationSetRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "RegulationSet" must be string, got %s.', get_debug_type($regulationSetRaw)),
                );
            }
            $regulationSet = $regulationSetRaw;
        }
        if (array_key_exists('TransportationMode', $data)) {
            $transportationModeRaw = $data['TransportationMode'];
            if (!is_string($transportationModeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "TransportationMode" must be string, got %s.',
                        get_debug_type($transportationModeRaw),
                    ),
                );
            }
            $transportationMode = $transportationModeRaw;
        }
        if (array_key_exists('CommodityRegulatedLevelCode', $data) && $data['CommodityRegulatedLevelCode'] !== null) {
            $commodityRegulatedLevelCodeRaw = $data['CommodityRegulatedLevelCode'];
            if (!is_string($commodityRegulatedLevelCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "CommodityRegulatedLevelCode" must be string, got %s.',
                        get_debug_type($commodityRegulatedLevelCodeRaw),
                    ),
                );
            }
            $commodityRegulatedLevelCode = Some::create($commodityRegulatedLevelCodeRaw);
        }
        if (array_key_exists('TransportCategory', $data) && $data['TransportCategory'] !== null) {
            $transportCategoryRaw = $data['TransportCategory'];
            if (!is_string($transportCategoryRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "TransportCategory" must be string, got %s.',
                        get_debug_type($transportCategoryRaw),
                    ),
                );
            }
            $transportCategory = Some::create($transportCategoryRaw);
        }
        if (array_key_exists('TunnelRestrictionCode', $data) && $data['TunnelRestrictionCode'] !== null) {
            $tunnelRestrictionCodeRaw = $data['TunnelRestrictionCode'];
            if (!is_string($tunnelRestrictionCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "TunnelRestrictionCode" must be string, got %s.',
                        get_debug_type($tunnelRestrictionCodeRaw),
                    ),
                );
            }
            $tunnelRestrictionCode = Some::create($tunnelRestrictionCodeRaw);
        }
        if (array_key_exists('ChemicalRecordIdentifier', $data) && $data['ChemicalRecordIdentifier'] !== null) {
            $chemicalRecordIdentifierRaw = $data['ChemicalRecordIdentifier'];
            if (!is_string($chemicalRecordIdentifierRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "ChemicalRecordIdentifier" must be string, got %s.',
                        get_debug_type($chemicalRecordIdentifierRaw),
                    ),
                );
            }
            $chemicalRecordIdentifier = Some::create($chemicalRecordIdentifierRaw);
        }
        if (array_key_exists('LocalTechnicalName', $data) && $data['LocalTechnicalName'] !== null) {
            $localTechnicalNameRaw = $data['LocalTechnicalName'];
            if (!is_string($localTechnicalNameRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "LocalTechnicalName" must be string, got %s.',
                        get_debug_type($localTechnicalNameRaw),
                    ),
                );
            }
            $localTechnicalName = Some::create($localTechnicalNameRaw);
        }
        if (array_key_exists('LocalProperShippingName', $data) && $data['LocalProperShippingName'] !== null) {
            $localProperShippingNameRaw = $data['LocalProperShippingName'];
            if (!is_string($localProperShippingNameRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "LocalProperShippingName" must be string, got %s.',
                        get_debug_type($localProperShippingNameRaw),
                    ),
                );
            }
            $localProperShippingName = Some::create($localProperShippingNameRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'PackagingTypeQuantity' => true,
                'RecordIdentifier1' => true,
                'RecordIdentifier2' => true,
                'RecordIdentifier3' => true,
                'SubRiskClass' => true,
                'aDRItemNumber' => true,
                'aDRPackingGroupLetter' => true,
                'TechnicalName' => true,
                'HazardLabelRequired' => true,
                'ClassDivisionNumber' => true,
                'ReferenceNumber' => true,
                'Quantity' => true,
                'UOM' => true,
                'PackagingType' => true,
                'IDNumber' => true,
                'ProperShippingName' => true,
                'AdditionalDescription' => true,
                'PackagingGroupType' => true,
                'PackagingInstructionCode' => true,
                'EmergencyPhone' => true,
                'EmergencyContact' => true,
                'ReportableQuantity' => true,
                'RegulationSet' => true,
                'TransportationMode' => true,
                'CommodityRegulatedLevelCode' => true,
                'TransportCategory' => true,
                'TunnelRestrictionCode' => true,
                'ChemicalRecordIdentifier' => true,
                'LocalTechnicalName' => true,
                'LocalProperShippingName' => true,
            ],
        );
        if ($properShippingName === null) {
            throw new MalformedDataException('Required property "ProperShippingName" is missing from the document.');
        }
        if ($regulationSet === null) {
            throw new MalformedDataException('Required property "RegulationSet" is missing from the document.');
        }
        if ($transportationMode === null) {
            throw new MalformedDataException('Required property "TransportationMode" is missing from the document.');
        }

        return new self(
            $properShippingName,
            $regulationSet,
            $transportationMode,
            $packagingTypeQuantity,
            $recordIdentifier1,
            $recordIdentifier2,
            $recordIdentifier3,
            $subRiskClass,
            $aDRItemNumber,
            $aDRPackingGroupLetter,
            $technicalName,
            $hazardLabelRequired,
            $classDivisionNumber,
            $referenceNumber,
            $quantity,
            $uOM,
            $packagingType,
            $iDNumber,
            $additionalDescription,
            $packagingGroupType,
            $packagingInstructionCode,
            $emergencyPhone,
            $emergencyContact,
            $reportableQuantity,
            $commodityRegulatedLevelCode,
            $transportCategory,
            $tunnelRestrictionCode,
            $chemicalRecordIdentifier,
            $localTechnicalName,
            $localProperShippingName,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $packagingTypeQuantityOption = $this->packagingTypeQuantity;
        if ($packagingTypeQuantityOption->isDefined()) {
            $packagingTypeQuantity = $packagingTypeQuantityOption->get();
            $dataArray['PackagingTypeQuantity'] = $packagingTypeQuantity;
        }
        $recordIdentifier1Option = $this->recordIdentifier1;
        if ($recordIdentifier1Option->isDefined()) {
            $recordIdentifier1 = $recordIdentifier1Option->get();
            $dataArray['RecordIdentifier1'] = $recordIdentifier1;
        }
        $recordIdentifier2Option = $this->recordIdentifier2;
        if ($recordIdentifier2Option->isDefined()) {
            $recordIdentifier2 = $recordIdentifier2Option->get();
            $dataArray['RecordIdentifier2'] = $recordIdentifier2;
        }
        $recordIdentifier3Option = $this->recordIdentifier3;
        if ($recordIdentifier3Option->isDefined()) {
            $recordIdentifier3 = $recordIdentifier3Option->get();
            $dataArray['RecordIdentifier3'] = $recordIdentifier3;
        }
        $subRiskClassOption = $this->subRiskClass;
        if ($subRiskClassOption->isDefined()) {
            $subRiskClass = $subRiskClassOption->get();
            $dataArray['SubRiskClass'] = $subRiskClass;
        }
        $aDRItemNumberOption = $this->aDRItemNumber;
        if ($aDRItemNumberOption->isDefined()) {
            $aDRItemNumber = $aDRItemNumberOption->get();
            $dataArray['aDRItemNumber'] = $aDRItemNumber;
        }
        $aDRPackingGroupLetterOption = $this->aDRPackingGroupLetter;
        if ($aDRPackingGroupLetterOption->isDefined()) {
            $aDRPackingGroupLetter = $aDRPackingGroupLetterOption->get();
            $dataArray['aDRPackingGroupLetter'] = $aDRPackingGroupLetter;
        }
        $technicalNameOption = $this->technicalName;
        if ($technicalNameOption->isDefined()) {
            $technicalName = $technicalNameOption->get();
            $dataArray['TechnicalName'] = $technicalName;
        }
        $hazardLabelRequiredOption = $this->hazardLabelRequired;
        if ($hazardLabelRequiredOption->isDefined()) {
            $hazardLabelRequired = $hazardLabelRequiredOption->get();
            $dataArray['HazardLabelRequired'] = $hazardLabelRequired;
        }
        $classDivisionNumberOption = $this->classDivisionNumber;
        if ($classDivisionNumberOption->isDefined()) {
            $classDivisionNumber = $classDivisionNumberOption->get();
            $dataArray['ClassDivisionNumber'] = $classDivisionNumber;
        }
        $referenceNumberOption = $this->referenceNumber;
        if ($referenceNumberOption->isDefined()) {
            $referenceNumber = $referenceNumberOption->get();
            $dataArray['ReferenceNumber'] = $referenceNumber;
        }
        $quantityOption = $this->quantity;
        if ($quantityOption->isDefined()) {
            $quantity = $quantityOption->get();
            $dataArray['Quantity'] = $quantity;
        }
        $uOMOption = $this->uOM;
        if ($uOMOption->isDefined()) {
            $uOM = $uOMOption->get();
            $dataArray['UOM'] = $uOM;
        }
        $packagingTypeOption = $this->packagingType;
        if ($packagingTypeOption->isDefined()) {
            $packagingType = $packagingTypeOption->get();
            $dataArray['PackagingType'] = $packagingType;
        }
        $iDNumberOption = $this->iDNumber;
        if ($iDNumberOption->isDefined()) {
            $iDNumber = $iDNumberOption->get();
            $dataArray['IDNumber'] = $iDNumber;
        }
        $dataArray['ProperShippingName'] = $this->properShippingName;
        $additionalDescriptionOption = $this->additionalDescription;
        if ($additionalDescriptionOption->isDefined()) {
            $additionalDescription = $additionalDescriptionOption->get();
            $dataArray['AdditionalDescription'] = $additionalDescription;
        }
        $packagingGroupTypeOption = $this->packagingGroupType;
        if ($packagingGroupTypeOption->isDefined()) {
            $packagingGroupType = $packagingGroupTypeOption->get();
            $dataArray['PackagingGroupType'] = $packagingGroupType;
        }
        $packagingInstructionCodeOption = $this->packagingInstructionCode;
        if ($packagingInstructionCodeOption->isDefined()) {
            $packagingInstructionCode = $packagingInstructionCodeOption->get();
            $dataArray['PackagingInstructionCode'] = $packagingInstructionCode;
        }
        $emergencyPhoneOption = $this->emergencyPhone;
        if ($emergencyPhoneOption->isDefined()) {
            $emergencyPhone = $emergencyPhoneOption->get();
            $dataArray['EmergencyPhone'] = $emergencyPhone;
        }
        $emergencyContactOption = $this->emergencyContact;
        if ($emergencyContactOption->isDefined()) {
            $emergencyContact = $emergencyContactOption->get();
            $dataArray['EmergencyContact'] = $emergencyContact;
        }
        $reportableQuantityOption = $this->reportableQuantity;
        if ($reportableQuantityOption->isDefined()) {
            $reportableQuantity = $reportableQuantityOption->get();
            $dataArray['ReportableQuantity'] = $reportableQuantity;
        }
        $dataArray['RegulationSet'] = $this->regulationSet;
        $dataArray['TransportationMode'] = $this->transportationMode;
        $commodityRegulatedLevelCodeOption = $this->commodityRegulatedLevelCode;
        if ($commodityRegulatedLevelCodeOption->isDefined()) {
            $commodityRegulatedLevelCode = $commodityRegulatedLevelCodeOption->get();
            $dataArray['CommodityRegulatedLevelCode'] = $commodityRegulatedLevelCode;
        }
        $transportCategoryOption = $this->transportCategory;
        if ($transportCategoryOption->isDefined()) {
            $transportCategory = $transportCategoryOption->get();
            $dataArray['TransportCategory'] = $transportCategory;
        }
        $tunnelRestrictionCodeOption = $this->tunnelRestrictionCode;
        if ($tunnelRestrictionCodeOption->isDefined()) {
            $tunnelRestrictionCode = $tunnelRestrictionCodeOption->get();
            $dataArray['TunnelRestrictionCode'] = $tunnelRestrictionCode;
        }
        $chemicalRecordIdentifierOption = $this->chemicalRecordIdentifier;
        if ($chemicalRecordIdentifierOption->isDefined()) {
            $chemicalRecordIdentifier = $chemicalRecordIdentifierOption->get();
            $dataArray['ChemicalRecordIdentifier'] = $chemicalRecordIdentifier;
        }
        $localTechnicalNameOption = $this->localTechnicalName;
        if ($localTechnicalNameOption->isDefined()) {
            $localTechnicalName = $localTechnicalNameOption->get();
            $dataArray['LocalTechnicalName'] = $localTechnicalName;
        }
        $localProperShippingNameOption = $this->localProperShippingName;
        if ($localProperShippingNameOption->isDefined()) {
            $localProperShippingName = $localProperShippingNameOption->get();
            $dataArray['LocalProperShippingName'] = $localProperShippingName;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): PackageServiceOptionsHazMatBuilder
    {
        return new PackageServiceOptionsHazMatBuilder(
            $this->properShippingName,
            $this->regulationSet,
            $this->transportationMode,
            $this->packagingTypeQuantity,
            $this->recordIdentifier1,
            $this->recordIdentifier2,
            $this->recordIdentifier3,
            $this->subRiskClass,
            $this->aDRItemNumber,
            $this->aDRPackingGroupLetter,
            $this->technicalName,
            $this->hazardLabelRequired,
            $this->classDivisionNumber,
            $this->referenceNumber,
            $this->quantity,
            $this->uOM,
            $this->packagingType,
            $this->iDNumber,
            $this->additionalDescription,
            $this->packagingGroupType,
            $this->packagingInstructionCode,
            $this->emergencyPhone,
            $this->emergencyContact,
            $this->reportableQuantity,
            $this->commodityRegulatedLevelCode,
            $this->transportCategory,
            $this->tunnelRestrictionCode,
            $this->chemicalRecordIdentifier,
            $this->localTechnicalName,
            $this->localProperShippingName,
            $this->additionalProperties,
        );
    }
}
