<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class PackagePackaging implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $description
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private string $code, private Option $description, private array $additionalProperties)
    {
    }

    public static function builder(string $code): PackagePackagingBuilder
    {
        return new PackagePackagingBuilder($code, None::create(), []);
    }

    /**
     * Package types. Values are: 01 = UPS Letter 02 = Customer Supplied Package 03 = Tube 04 = PAK
     * 21 = UPS Express Box 24 = UPS 25KG Box 25 = UPS 10KG Box 30 = Pallet 2a = Small Express Box
     * 2b = Medium Express Box 2c = Large Express Box 56 = Flats 57 = Parcels 58 = BPM 59 = First
     * Class 60 = Priority 61 = Machineables 62 = Irregulars 63 = Parcel Post 64 = BPM Parcel 65 =
     * Media Mail 66 = BPM Flat 67 = Standard Flat. Note: Only packaging type code 02 is applicable
     * to Ground Freight Pricing. Package type 24, or 25 is only allowed for shipment without return
     * service. Packaging type must be valid for all the following: ShipTo country or territory,
     * ShipFrom country or territory, a shipment going from ShipTo country or territory to ShipFrom
     * country or territory, all Accessorials at both the shipment and package level, and the
     * shipment service type. UPS will not accept raw wood pallets and please refer the UPS
     * packaging guidelines for pallets on UPS.com.
     */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * Description of packaging type. Examples are letter, customer supplied, express box.
     *
     * @return Option<string>
     */
    public function getDescription(): Option
    {
        return $this->description;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $code = null;
        $description = None::create();
        if (array_key_exists('Code', $data)) {
            $codeRaw = $data['Code'];
            if (!is_string($codeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Code" must be string, got %s.', get_debug_type($codeRaw)),
                );
            }
            $code = $codeRaw;
        }
        if (array_key_exists('Description', $data) && $data['Description'] !== null) {
            $descriptionRaw = $data['Description'];
            if (!is_string($descriptionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Description" must be string, got %s.', get_debug_type($descriptionRaw)),
                );
            }
            $description = Some::create($descriptionRaw);
        }
        $additionalProperties = array_diff_key($data, ['Code' => true, 'Description' => true]);
        if ($code === null) {
            throw new MalformedDataException('Required property "Code" is missing from the document.');
        }

        return new self($code, $description, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['Code'] = $this->code;
        $descriptionOption = $this->description;
        if ($descriptionOption->isDefined()) {
            $description = $descriptionOption->get();
            $dataArray['Description'] = $description;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): PackagePackagingBuilder
    {
        return new PackagePackagingBuilder($this->code, $this->description, $this->additionalProperties);
    }
}
