<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class PackageServiceOptionsNotificationEMail implements SelfNormalizingModel
{
    /**
     * @param list<string>             $eMailAddress
     * @param Option<string>           $subject
     * @param Option<string>           $subjectCode
     * @param Option<string>           $undeliverableEMailAddress
     * @param Option<string>           $fromEMailAddress
     * @param Option<string>           $fromName
     * @param Option<string>           $memo
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private array $eMailAddress,
        private Option $subject,
        private Option $subjectCode,
        private Option $undeliverableEMailAddress,
        private Option $fromEMailAddress,
        private Option $fromName,
        private Option $memo,
        private array $additionalProperties,
    ) {
    }

    /** @param list<string> $eMailAddress */
    public static function builder(array $eMailAddress): PackageServiceOptionsNotificationEMailBuilder
    {
        return new PackageServiceOptionsNotificationEMailBuilder(
            $eMailAddress,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * The eMails subject. Defaults to the UPS Receiver Return Notification plus the shipment ID.
     * Only allowed at the first package.
     *
     * @return Option<string>
     */
    public function getSubject(): Option
    {
        return $this->subject;
    }

    /**
     * Specifies a reference code and reference number to display in the subject of the Receiver
     * Return Notification.
     *
     * When the subject code is provided, the subject will contain the following: UPS Receiver
     * Return Notification.
     *
     * The reference code (the reference code will be mapped to the corresponding ANSI value) Plus
     * the reference number.
     *
     * The valid subject codes are:
     * - 01 - Shipment Reference Number 1,
     * - 02 - Shipment Reference Number 2,
     * - 03 - package Reference Number 1,
     * - 04 - package Reference Number 2,
     * - 05 - package Reference Number 3,
     * - 06 - package Reference Number 4,
     * - 07 - package Reference Number 5,
     * - 08 - Subject Text (Return Notification only).
     *
     * If the subject code tag is not provided and the subject text is provided, the subject of the
     * notification will be the subject text.
     *
     * If the subject text is provided, and subject code tag exists, then the subject code value
     * must be 08.
     *
     * If the subject code is 08, the subject text must exist. If a subject code is provided that
     * refers to a nonexistent reference number, the subject will default to the tracking number.
     * Only allowed at the first package.
     *
     * @return Option<string>
     */
    public function getSubjectCode(): Option
    {
        return $this->subjectCode;
    }

    /**
     * The destination email address of the receiver returns notification email.
     *
     * @return list<string>
     */
    public function getEMailAddress(): array
    {
        return $this->eMailAddress;
    }

    /**
     * The e-mail address where an undeliverable email message is sent if the Receiver Return
     * Notification email is undeliverable. Defaults to FromEMailAddress. Only allowed at the first
     * package.
     *
     * @return Option<string>
     */
    public function getUndeliverableEMailAddress(): Option
    {
        return $this->undeliverableEMailAddress;
    }

    /**
     * The email address listed in the Reply To field of the message header, includes name and
     * e-mail address of sender. The "From" field of the message header contains pkginfo@ups.com.
     * Only allowed at the first package.
     *
     * @return Option<string>
     */
    public function getFromEMailAddress(): Option
    {
        return $this->fromEMailAddress;
    }

    /**
     * The name the receiver return notification will appear to be from. Defaults to the Shipper
     * Name. Only allowed at the first package.
     *
     * @return Option<string>
     */
    public function getFromName(): Option
    {
        return $this->fromName;
    }

    /**
     * User defined text that will be included in the email. Only allowed at the first package.
     *
     * @return Option<string>
     */
    public function getMemo(): Option
    {
        return $this->memo;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $subject = None::create();
        $subjectCode = None::create();
        $eMailAddress = null;
        $undeliverableEMailAddress = None::create();
        $fromEMailAddress = None::create();
        $fromName = None::create();
        $memo = None::create();
        if (array_key_exists('Subject', $data) && $data['Subject'] !== null) {
            $subjectRaw = $data['Subject'];
            if (!is_string($subjectRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Subject" must be string, got %s.', get_debug_type($subjectRaw)),
                );
            }
            $subject = Some::create($subjectRaw);
        }
        if (array_key_exists('SubjectCode', $data) && $data['SubjectCode'] !== null) {
            $subjectCodeRaw = $data['SubjectCode'];
            if (!is_string($subjectCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "SubjectCode" must be string, got %s.', get_debug_type($subjectCodeRaw)),
                );
            }
            $subjectCode = Some::create($subjectCodeRaw);
        }
        if (array_key_exists('EMailAddress', $data)) {
            $eMailAddressRaw = $data['EMailAddress'];
            if (!(is_array($eMailAddressRaw) && array_is_list($eMailAddressRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "EMailAddress" must be list, got %s.', get_debug_type($eMailAddressRaw)),
                );
            }
            $eMailAddress = array_map(static function (mixed $value): string {
                if (!is_string($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value)),
                    );
                }

                return $value;
            }, $eMailAddressRaw);
        }
        if (array_key_exists('UndeliverableEMailAddress', $data) && $data['UndeliverableEMailAddress'] !== null) {
            $undeliverableEMailAddressRaw = $data['UndeliverableEMailAddress'];
            if (!is_string($undeliverableEMailAddressRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "UndeliverableEMailAddress" must be string, got %s.',
                        get_debug_type($undeliverableEMailAddressRaw),
                    ),
                );
            }
            $undeliverableEMailAddress = Some::create($undeliverableEMailAddressRaw);
        }
        if (array_key_exists('FromEMailAddress', $data) && $data['FromEMailAddress'] !== null) {
            $fromEMailAddressRaw = $data['FromEMailAddress'];
            if (!is_string($fromEMailAddressRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "FromEMailAddress" must be string, got %s.',
                        get_debug_type($fromEMailAddressRaw),
                    ),
                );
            }
            $fromEMailAddress = Some::create($fromEMailAddressRaw);
        }
        if (array_key_exists('FromName', $data) && $data['FromName'] !== null) {
            $fromNameRaw = $data['FromName'];
            if (!is_string($fromNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "FromName" must be string, got %s.', get_debug_type($fromNameRaw)),
                );
            }
            $fromName = Some::create($fromNameRaw);
        }
        if (array_key_exists('Memo', $data) && $data['Memo'] !== null) {
            $memoRaw = $data['Memo'];
            if (!is_string($memoRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Memo" must be string, got %s.', get_debug_type($memoRaw)),
                );
            }
            $memo = Some::create($memoRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'Subject' => true,
                'SubjectCode' => true,
                'EMailAddress' => true,
                'UndeliverableEMailAddress' => true,
                'FromEMailAddress' => true,
                'FromName' => true,
                'Memo' => true,
            ],
        );
        if ($eMailAddress === null) {
            throw new MalformedDataException('Required property "EMailAddress" is missing from the document.');
        }

        return new self(
            $eMailAddress,
            $subject,
            $subjectCode,
            $undeliverableEMailAddress,
            $fromEMailAddress,
            $fromName,
            $memo,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $subjectOption = $this->subject;
        if ($subjectOption->isDefined()) {
            $subject = $subjectOption->get();
            $dataArray['Subject'] = $subject;
        }
        $subjectCodeOption = $this->subjectCode;
        if ($subjectCodeOption->isDefined()) {
            $subjectCode = $subjectCodeOption->get();
            $dataArray['SubjectCode'] = $subjectCode;
        }
        $values = [];
        foreach ($this->eMailAddress as $value) {
            $values[] = $value;
        }
        $dataArray['EMailAddress'] = $values;
        $undeliverableEMailAddressOption = $this->undeliverableEMailAddress;
        if ($undeliverableEMailAddressOption->isDefined()) {
            $undeliverableEMailAddress = $undeliverableEMailAddressOption->get();
            $dataArray['UndeliverableEMailAddress'] = $undeliverableEMailAddress;
        }
        $fromEMailAddressOption = $this->fromEMailAddress;
        if ($fromEMailAddressOption->isDefined()) {
            $fromEMailAddress = $fromEMailAddressOption->get();
            $dataArray['FromEMailAddress'] = $fromEMailAddress;
        }
        $fromNameOption = $this->fromName;
        if ($fromNameOption->isDefined()) {
            $fromName = $fromNameOption->get();
            $dataArray['FromName'] = $fromName;
        }
        $memoOption = $this->memo;
        if ($memoOption->isDefined()) {
            $memo = $memoOption->get();
            $dataArray['Memo'] = $memo;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): PackageServiceOptionsNotificationEMailBuilder
    {
        return new PackageServiceOptionsNotificationEMailBuilder(
            $this->eMailAddress,
            $this->subject,
            $this->subjectCode,
            $this->undeliverableEMailAddress,
            $this->fromEMailAddress,
            $this->fromName,
            $this->memo,
            $this->additionalProperties,
        );
    }
}
