<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class PackageResultsNegotiatedCharges implements SelfNormalizingModel
{
    /**
     * @param Option<list<NegotiatedChargesItemizedCharges>> $itemizedCharges
     * @param Option<list<NegotiatedChargesRateModifier>>    $rateModifier
     * @param array<int|string, mixed>                       $additionalProperties
     */
    public function __construct(
        private Option $itemizedCharges,
        private Option $rateModifier,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): PackageResultsNegotiatedChargesBuilder
    {
        return new PackageResultsNegotiatedChargesBuilder(None::create(), None::create(), []);
    }

    /**
     * Negotiated Itemized Accessorial and SurCharges.
     *
     * Negotiated itemized charges are only returned for certain contract-only shipments as well as
     * Worldwide Express Freight, Ground Freight Pricing, and Hazmat movements. Negotiated Itemized
     * Accessorial and Sur Charges are returned only when the subversion element is present and
     * greater than or equal to 1607.
     *
     * Package level itemized charges are only returned for US domestic movements
     *
     * **NOTE:** For versions >= v2403, this element will always be returned as an array. For
     * requests using versions < v2403, this element will be returned as an array if there is more
     * than one object and a single object if there is only 1.
     *
     * @return Option<list<NegotiatedChargesItemizedCharges>>
     */
    public function getItemizedCharges(): Option
    {
        return $this->itemizedCharges;
    }

    /** @return Option<list<NegotiatedChargesRateModifier>> */
    public function getRateModifier(): Option
    {
        return $this->rateModifier;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $itemizedCharges = None::create();
        $rateModifier = None::create();
        if (array_key_exists('ItemizedCharges', $data) && $data['ItemizedCharges'] !== null) {
            $itemizedChargesRaw = $data['ItemizedCharges'];
            if (!(is_array($itemizedChargesRaw) && array_is_list($itemizedChargesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "ItemizedCharges" must be list, got %s.', get_debug_type($itemizedChargesRaw)),
                );
            }
            $itemizedCharges = Some::create(array_map(static function (mixed $value): NegotiatedChargesItemizedCharges {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var non-empty-array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return NegotiatedChargesItemizedCharges::fromArray($valueTyped);
            }, $itemizedChargesRaw));
        }
        if (array_key_exists('RateModifier', $data) && $data['RateModifier'] !== null) {
            $rateModifierRaw = $data['RateModifier'];
            if (!(is_array($rateModifierRaw) && array_is_list($rateModifierRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "RateModifier" must be list, got %s.', get_debug_type($rateModifierRaw)),
                );
            }
            $rateModifier = Some::create(array_map(static function (mixed $value_1): NegotiatedChargesRateModifier {
                if (!is_array($value_1)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value_1)),
                    );
                }
                /** @var non-empty-array<string, mixed> $value_1Typed */
                $value_1Typed = $value_1;

                return NegotiatedChargesRateModifier::fromArray($value_1Typed);
            }, $rateModifierRaw));
        }
        $additionalProperties = array_diff_key($data, ['ItemizedCharges' => true, 'RateModifier' => true]);

        return new self($itemizedCharges, $rateModifier, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $itemizedChargesOption = $this->itemizedCharges;
        if ($itemizedChargesOption->isDefined()) {
            $itemizedCharges = $itemizedChargesOption->get();
            $values = [];
            foreach ($itemizedCharges as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['ItemizedCharges'] = $values;
        }
        $rateModifierOption = $this->rateModifier;
        if ($rateModifierOption->isDefined()) {
            $rateModifier = $rateModifierOption->get();
            $values_1 = [];
            foreach ($rateModifier as $value_1) {
                $values_1[] = $normalizationTarget->model($value_1);
            }
            $dataArray['RateModifier'] = $values_1;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): PackageResultsNegotiatedChargesBuilder
    {
        return new PackageResultsNegotiatedChargesBuilder(
            $this->itemizedCharges,
            $this->rateModifier,
            $this->additionalProperties,
        );
    }
}
