<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see PackageDimWeight}.
 */
final class PackageDimWeightBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<DimWeightUnitOfMeasurement> $unitOfMeasurement
     * @param Option<string>                     $weight
     * @param array<int|string, mixed>           $additionalProperties
     */
    public function __construct(
        private Option $unitOfMeasurement,
        private Option $weight,
        private array $additionalProperties,
    ) {
    }

    /**
     * UnitOfMeasurement Container.
     */
    public function setUnitOfMeasurement(DimWeightUnitOfMeasurement $unitOfMeasurement): self
    {
        $this->unitOfMeasurement = Some::create($unitOfMeasurement);

        return $this;
    }

    /**
     * Actual package weight. Weight accepted for letters/envelopes.
     */
    public function setWeight(string $weight): self
    {
        $this->weight = Some::create($weight);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): PackageDimWeight
    {
        return new PackageDimWeight($this->unitOfMeasurement, $this->weight, $this->additionalProperties);
    }
}
