<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class PackageResultsRateModifier implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(
        private string $modifierType,
        private string $modifierDesc,
        private string $amount,
        private array $additionalProperties,
    ) {
    }

    public static function builder(
        string $modifierType,
        string $modifierDesc,
        string $amount,
    ): PackageResultsRateModifierBuilder {
        return new PackageResultsRateModifierBuilder($modifierType, $modifierDesc, $amount, []);
    }

    /**
     * Rate Modifier Type. Example: "ORM". Applies only if SubVersion is 2205 or greater.
     */
    public function getModifierType(): string
    {
        return $this->modifierType;
    }

    /**
     * Rate Modifier Description. Example: "Origin Modifier". Applies only if SubVersion is 2205 or
     * greater.
     */
    public function getModifierDesc(): string
    {
        return $this->modifierDesc;
    }

    /**
     * Amount. Example: "-1.00","0.25". It contains positive or negative values. Applies only if
     * SubVersion is 2205 or greater.
     */
    public function getAmount(): string
    {
        return $this->amount;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $modifierType = null;
        $modifierDesc = null;
        $amount = null;
        if (array_key_exists('ModifierType', $data)) {
            $modifierTypeRaw = $data['ModifierType'];
            if (!is_string($modifierTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "ModifierType" must be string, got %s.', get_debug_type($modifierTypeRaw)),
                );
            }
            $modifierType = $modifierTypeRaw;
        }
        if (array_key_exists('ModifierDesc', $data)) {
            $modifierDescRaw = $data['ModifierDesc'];
            if (!is_string($modifierDescRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "ModifierDesc" must be string, got %s.', get_debug_type($modifierDescRaw)),
                );
            }
            $modifierDesc = $modifierDescRaw;
        }
        if (array_key_exists('Amount', $data)) {
            $amountRaw = $data['Amount'];
            if (!is_string($amountRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Amount" must be string, got %s.', get_debug_type($amountRaw)),
                );
            }
            $amount = $amountRaw;
        }
        $additionalProperties = array_diff_key(
            $data,
            ['ModifierType' => true, 'ModifierDesc' => true, 'Amount' => true],
        );
        if ($modifierType === null) {
            throw new MalformedDataException('Required property "ModifierType" is missing from the document.');
        }
        if ($modifierDesc === null) {
            throw new MalformedDataException('Required property "ModifierDesc" is missing from the document.');
        }
        if ($amount === null) {
            throw new MalformedDataException('Required property "Amount" is missing from the document.');
        }

        return new self($modifierType, $modifierDesc, $amount, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['ModifierType'] = $this->modifierType;
        $dataArray['ModifierDesc'] = $this->modifierDesc;
        $dataArray['Amount'] = $this->amount;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): PackageResultsRateModifierBuilder
    {
        return new PackageResultsRateModifierBuilder(
            $this->modifierType,
            $this->modifierDesc,
            $this->amount,
            $this->additionalProperties,
        );
    }
}
