<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

/**
 * Builds a {@see PackageServiceOptionsNotification}.
 */
final class PackageServiceOptionsNotificationBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $notificationCode,
        private PackageServiceOptionsNotificationEMail $eMail,
        private array $additionalProperties,
    ) {
    }

    /**
     * Notification Code. Valid values: 3 - Receiver Return Notification 6 - QV Email Notification 7
     * - QV Exception Notification 8 - QV Delivery Notification For Mail Innovations forward
     * shipments, QV Email Notifications are allowed for First Class, Priority Mail, and Expedited
     * Mail Innovation services.
     */
    public function setNotificationCode(string $notificationCode): self
    {
        $this->notificationCode = $notificationCode;

        return $this;
    }

    /**
     * Container for the e-mail message.
     */
    public function setEMail(PackageServiceOptionsNotificationEMail $eMail): self
    {
        $this->eMail = $eMail;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): PackageServiceOptionsNotification
    {
        return new PackageServiceOptionsNotification(
            $this->notificationCode,
            $this->eMail,
            $this->additionalProperties,
        );
    }
}
