<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class PackageServiceOptionsNotification implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(
        private string $notificationCode,
        private PackageServiceOptionsNotificationEMail $eMail,
        private array $additionalProperties,
    ) {
    }

    public static function builder(
        string $notificationCode,
        PackageServiceOptionsNotificationEMail $eMail,
    ): PackageServiceOptionsNotificationBuilder {
        return new PackageServiceOptionsNotificationBuilder($notificationCode, $eMail, []);
    }

    /**
     * Notification Code. Valid values: 3 - Receiver Return Notification 6 - QV Email Notification 7
     * - QV Exception Notification 8 - QV Delivery Notification For Mail Innovations forward
     * shipments, QV Email Notifications are allowed for First Class, Priority Mail, and Expedited
     * Mail Innovation services.
     */
    public function getNotificationCode(): string
    {
        return $this->notificationCode;
    }

    /**
     * Container for the e-mail message.
     */
    public function getEMail(): PackageServiceOptionsNotificationEMail
    {
        return $this->eMail;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $notificationCode = null;
        $eMail = null;
        if (array_key_exists('NotificationCode', $data)) {
            $notificationCodeRaw = $data['NotificationCode'];
            if (!is_string($notificationCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "NotificationCode" must be string, got %s.',
                        get_debug_type($notificationCodeRaw),
                    ),
                );
            }
            $notificationCode = $notificationCodeRaw;
        }
        if (array_key_exists('EMail', $data)) {
            $eMailRaw = $data['EMail'];
            if (!is_array($eMailRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "EMail" must be object, got %s.', get_debug_type($eMailRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $eMailRawTyped */
            $eMailRawTyped = $eMailRaw;
            $eMail = PackageServiceOptionsNotificationEMail::fromArray($eMailRawTyped);
        }
        $additionalProperties = array_diff_key($data, ['NotificationCode' => true, 'EMail' => true]);
        if ($notificationCode === null) {
            throw new MalformedDataException('Required property "NotificationCode" is missing from the document.');
        }
        if ($eMail === null) {
            throw new MalformedDataException('Required property "EMail" is missing from the document.');
        }

        return new self($notificationCode, $eMail, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['NotificationCode'] = $this->notificationCode;
        $dataArray['EMail'] = $normalizationTarget->model($this->eMail);
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): PackageServiceOptionsNotificationBuilder
    {
        return new PackageServiceOptionsNotificationBuilder(
            $this->notificationCode,
            $this->eMail,
            $this->additionalProperties,
        );
    }
}
