<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see PaymentInformationShipmentCharge}.
 */
final class PaymentInformationShipmentChargeBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<ShipmentChargeBillShipper>    $billShipper
     * @param Option<ShipmentChargeBillReceiver>   $billReceiver
     * @param Option<ShipmentChargeBillThirdParty> $billThirdParty
     * @param Option<string>                       $consigneeBilledIndicator
     * @param array<int|string, mixed>             $additionalProperties
     */
    public function __construct(
        private string $type,
        private Option $billShipper,
        private Option $billReceiver,
        private Option $billThirdParty,
        private Option $consigneeBilledIndicator,
        private array $additionalProperties,
    ) {
    }

    /**
     * Valid values: 01 = Transportation 02 = Duties and Taxes 03 = Broker of Choice A shipment
     * charge type of 01 = Transportation is required.
     *
     * A shipment charge type of 02 = Duties and Taxes is not required; however, this charge type is
     * invalid for Qualified Domestic Shipments.
     *
     * A Qualified Domestic Shipment is any shipment in which one of the following applies:
     *
     * 1) The origin and destination country or territory is the same.
     *
     * 2) US to PR shipment.
     *
     * 3) PR to US shipment.
     *
     * 4) The origin and destination country or territory are both European Union countries or
     *    territories and the GoodsNotInFreeCirculation indicator is not present.
     *
     * 5) The origin and destination IATA code is the same. 03 = Broker of Choice
     */
    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Container for the BillShipper billing option. The three payment methods that are available
     * for the Bill Shipper billing option are alternate payment method, account number or credit
     * card. This element or its sibling element, BillReceiver, BillThirdParty or
     * ConsigneeBilledIndicator, must be present but no more than one can be present.
     */
    public function setBillShipper(ShipmentChargeBillShipper $billShipper): self
    {
        $this->billShipper = Some::create($billShipper);

        return $this;
    }

    /**
     * Container for the BillReceiver billing option. This element or its sibling element,
     * BillShipper, BillThirdParty or Consignee Billed, must be present but no more than one can be
     * present. For a return shipment, Bill Receiver is invalid for Transportation charges.
     */
    public function setBillReceiver(ShipmentChargeBillReceiver $billReceiver): self
    {
        $this->billReceiver = Some::create($billReceiver);

        return $this;
    }

    /**
     * Container for the third party billing option. This element or its sibling element,
     * BillShipper, BillReceiver or Consignee Billed, must be present but no more than one can be
     * present.
     */
    public function setBillThirdParty(ShipmentChargeBillThirdParty $billThirdParty): self
    {
        $this->billThirdParty = Some::create($billThirdParty);

        return $this;
    }

    /**
     * Consignee Billing payment option indicator. The presence indicates consignee billing option
     * is selected. The absence indicates one of the other payment options is selected. This is an
     * empty tag, any value inside is ignored. This element or its sibling element, BillShipper,
     * BillReceiver or BillThirdParty, must be present but no more than one can be present. This
     * billing option is valid for a shipment charge type of Transportation only. Only applies to
     * US/PR and PR/US shipment origins and destination.
     *
     * This payment method allows you to bill the charges for a specified shipment to a consignee
     * who has agreed to pay the charges. All shipping charges are billed to the consignees UPS
     * account number including the following accessorials: Additional Handling, Delivery Area
     * Surcharges, Delivery Change Requests, Early AM Premium, Early AM Out of Territory, Fuel
     * Surcharge, Hazardous Material Surcharges, Large Package Surcharge, Over Max Limits, and
     * Saturday Delivery.
     *
     * Declared Value, Delivery Confirmation, On Call Pickup, Remote Area Surcharge, Saturday Pickup
     * of Delivery fees are not passed to the consignee. These charges are billed to the shippers
     * UPS account number.
     */
    public function setConsigneeBilledIndicator(string $consigneeBilledIndicator): self
    {
        $this->consigneeBilledIndicator = Some::create($consigneeBilledIndicator);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): PaymentInformationShipmentCharge
    {
        return new PaymentInformationShipmentCharge(
            $this->type,
            $this->billShipper,
            $this->billReceiver,
            $this->billThirdParty,
            $this->consigneeBilledIndicator,
            $this->additionalProperties,
        );
    }
}
