<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class PaymentInformationShipmentCharge implements SelfNormalizingModel
{
    /**
     * @param Option<ShipmentChargeBillShipper>    $billShipper
     * @param Option<ShipmentChargeBillReceiver>   $billReceiver
     * @param Option<ShipmentChargeBillThirdParty> $billThirdParty
     * @param Option<string>                       $consigneeBilledIndicator
     * @param array<int|string, mixed>             $additionalProperties
     */
    public function __construct(
        private string $type,
        private Option $billShipper,
        private Option $billReceiver,
        private Option $billThirdParty,
        private Option $consigneeBilledIndicator,
        private array $additionalProperties,
    ) {
    }

    public static function builder(string $type): PaymentInformationShipmentChargeBuilder
    {
        return new PaymentInformationShipmentChargeBuilder(
            $type,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Valid values: 01 = Transportation 02 = Duties and Taxes 03 = Broker of Choice A shipment
     * charge type of 01 = Transportation is required.
     *
     * A shipment charge type of 02 = Duties and Taxes is not required; however, this charge type is
     * invalid for Qualified Domestic Shipments.
     *
     * A Qualified Domestic Shipment is any shipment in which one of the following applies:
     *
     * 1) The origin and destination country or territory is the same.
     *
     * 2) US to PR shipment.
     *
     * 3) PR to US shipment.
     *
     * 4) The origin and destination country or territory are both European Union countries or
     *    territories and the GoodsNotInFreeCirculation indicator is not present.
     *
     * 5) The origin and destination IATA code is the same. 03 = Broker of Choice
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Container for the BillShipper billing option. The three payment methods that are available
     * for the Bill Shipper billing option are alternate payment method, account number or credit
     * card. This element or its sibling element, BillReceiver, BillThirdParty or
     * ConsigneeBilledIndicator, must be present but no more than one can be present.
     *
     * @return Option<ShipmentChargeBillShipper>
     */
    public function getBillShipper(): Option
    {
        return $this->billShipper;
    }

    /**
     * Container for the BillReceiver billing option. This element or its sibling element,
     * BillShipper, BillThirdParty or Consignee Billed, must be present but no more than one can be
     * present. For a return shipment, Bill Receiver is invalid for Transportation charges.
     *
     * @return Option<ShipmentChargeBillReceiver>
     */
    public function getBillReceiver(): Option
    {
        return $this->billReceiver;
    }

    /**
     * Container for the third party billing option. This element or its sibling element,
     * BillShipper, BillReceiver or Consignee Billed, must be present but no more than one can be
     * present.
     *
     * @return Option<ShipmentChargeBillThirdParty>
     */
    public function getBillThirdParty(): Option
    {
        return $this->billThirdParty;
    }

    /**
     * Consignee Billing payment option indicator. The presence indicates consignee billing option
     * is selected. The absence indicates one of the other payment options is selected. This is an
     * empty tag, any value inside is ignored. This element or its sibling element, BillShipper,
     * BillReceiver or BillThirdParty, must be present but no more than one can be present. This
     * billing option is valid for a shipment charge type of Transportation only. Only applies to
     * US/PR and PR/US shipment origins and destination.
     *
     * This payment method allows you to bill the charges for a specified shipment to a consignee
     * who has agreed to pay the charges. All shipping charges are billed to the consignees UPS
     * account number including the following accessorials: Additional Handling, Delivery Area
     * Surcharges, Delivery Change Requests, Early AM Premium, Early AM Out of Territory, Fuel
     * Surcharge, Hazardous Material Surcharges, Large Package Surcharge, Over Max Limits, and
     * Saturday Delivery.
     *
     * Declared Value, Delivery Confirmation, On Call Pickup, Remote Area Surcharge, Saturday Pickup
     * of Delivery fees are not passed to the consignee. These charges are billed to the shippers
     * UPS account number.
     *
     * @return Option<string>
     */
    public function getConsigneeBilledIndicator(): Option
    {
        return $this->consigneeBilledIndicator;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $type = null;
        $billShipper = None::create();
        $billReceiver = None::create();
        $billThirdParty = None::create();
        $consigneeBilledIndicator = None::create();
        if (array_key_exists('Type', $data)) {
            $typeRaw = $data['Type'];
            if (!is_string($typeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Type" must be string, got %s.', get_debug_type($typeRaw)),
                );
            }
            $type = $typeRaw;
        }
        if (array_key_exists('BillShipper', $data) && $data['BillShipper'] !== null) {
            $billShipperRaw = $data['BillShipper'];
            if (!is_array($billShipperRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "BillShipper" must be object, got %s.', get_debug_type($billShipperRaw)),
                );
            }
            /** @var array<string, mixed> $billShipperRawTyped */
            $billShipperRawTyped = $billShipperRaw;
            $billShipper = Some::create(ShipmentChargeBillShipper::fromArray($billShipperRawTyped));
        }
        if (array_key_exists('BillReceiver', $data) && $data['BillReceiver'] !== null) {
            $billReceiverRaw = $data['BillReceiver'];
            if (!is_array($billReceiverRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "BillReceiver" must be object, got %s.', get_debug_type($billReceiverRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $billReceiverRawTyped */
            $billReceiverRawTyped = $billReceiverRaw;
            $billReceiver = Some::create(ShipmentChargeBillReceiver::fromArray($billReceiverRawTyped));
        }
        if (array_key_exists('BillThirdParty', $data) && $data['BillThirdParty'] !== null) {
            $billThirdPartyRaw = $data['BillThirdParty'];
            if (!is_array($billThirdPartyRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "BillThirdParty" must be object, got %s.', get_debug_type($billThirdPartyRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $billThirdPartyRawTyped */
            $billThirdPartyRawTyped = $billThirdPartyRaw;
            $billThirdParty = Some::create(ShipmentChargeBillThirdParty::fromArray($billThirdPartyRawTyped));
        }
        if (array_key_exists('ConsigneeBilledIndicator', $data) && $data['ConsigneeBilledIndicator'] !== null) {
            $consigneeBilledIndicatorRaw = $data['ConsigneeBilledIndicator'];
            if (!is_string($consigneeBilledIndicatorRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "ConsigneeBilledIndicator" must be string, got %s.',
                        get_debug_type($consigneeBilledIndicatorRaw),
                    ),
                );
            }
            $consigneeBilledIndicator = Some::create($consigneeBilledIndicatorRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'Type' => true,
                'BillShipper' => true,
                'BillReceiver' => true,
                'BillThirdParty' => true,
                'ConsigneeBilledIndicator' => true,
            ],
        );
        if ($type === null) {
            throw new MalformedDataException('Required property "Type" is missing from the document.');
        }

        return new self(
            $type,
            $billShipper,
            $billReceiver,
            $billThirdParty,
            $consigneeBilledIndicator,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['Type'] = $this->type;
        $billShipperOption = $this->billShipper;
        if ($billShipperOption->isDefined()) {
            $billShipper = $billShipperOption->get();
            $dataArray['BillShipper'] = $normalizationTarget->model($billShipper);
        }
        $billReceiverOption = $this->billReceiver;
        if ($billReceiverOption->isDefined()) {
            $billReceiver = $billReceiverOption->get();
            $dataArray['BillReceiver'] = $normalizationTarget->model($billReceiver);
        }
        $billThirdPartyOption = $this->billThirdParty;
        if ($billThirdPartyOption->isDefined()) {
            $billThirdParty = $billThirdPartyOption->get();
            $dataArray['BillThirdParty'] = $normalizationTarget->model($billThirdParty);
        }
        $consigneeBilledIndicatorOption = $this->consigneeBilledIndicator;
        if ($consigneeBilledIndicatorOption->isDefined()) {
            $consigneeBilledIndicator = $consigneeBilledIndicatorOption->get();
            $dataArray['ConsigneeBilledIndicator'] = $consigneeBilledIndicator;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): PaymentInformationShipmentChargeBuilder
    {
        return new PaymentInformationShipmentChargeBuilder(
            $this->type,
            $this->billShipper,
            $this->billReceiver,
            $this->billThirdParty,
            $this->consigneeBilledIndicator,
            $this->additionalProperties,
        );
    }
}
