<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class PreAlertNotificationVoiceMessage implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(private string $phoneNumber, private array $additionalProperties)
    {
    }

    public static function builder(string $phoneNumber): PreAlertNotificationVoiceMessageBuilder
    {
        return new PreAlertNotificationVoiceMessageBuilder($phoneNumber, []);
    }

    /**
     * Phone number for receiving Voice PreAlertNotification. Valid values are 0 – 9.
     *
     * If the country or territory of the message recipient is US, PR, CA, and VI, the layout is:
     *
     * 1, area code, 7 digit phone number or
     *
     * 1, area code, 7 digit phone number, 4 digit extension number.
     *
     * For other countries or territories, the layout is country or territory code, area code, 7
     * digit number.
     */
    public function getPhoneNumber(): string
    {
        return $this->phoneNumber;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $phoneNumber = null;
        if (array_key_exists('PhoneNumber', $data)) {
            $phoneNumberRaw = $data['PhoneNumber'];
            if (!is_string($phoneNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "PhoneNumber" must be string, got %s.', get_debug_type($phoneNumberRaw)),
                );
            }
            $phoneNumber = $phoneNumberRaw;
        }
        $additionalProperties = array_diff_key($data, ['PhoneNumber' => true]);
        if ($phoneNumber === null) {
            throw new MalformedDataException('Required property "PhoneNumber" is missing from the document.');
        }

        return new self($phoneNumber, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['PhoneNumber'] = $this->phoneNumber;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): PreAlertNotificationVoiceMessageBuilder
    {
        return new PreAlertNotificationVoiceMessageBuilder($this->phoneNumber, $this->additionalProperties);
    }
}
