<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see ProductScheduleB}.
 */
final class ProductScheduleBBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param list<ScheduleBUnitOfMeasurement> $unitOfMeasurement
     * @param Option<list<string>>             $quantity
     * @param array<int|string, mixed>         $additionalProperties
     */
    public function __construct(
        private string $number,
        private array $unitOfMeasurement,
        private Option $quantity,
        private array $additionalProperties,
    ) {
    }

    /**
     * A unique 10-digit commodity classification code for the item being exported. (To classify a
     * commodity access the following Web page:
     * http://www.census.gov/foreign-trade/schedules/b/#search). Applies to EEI forms only. Has to
     * be 10 characters.
     */
    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    /** @param list<ScheduleBUnitOfMeasurement> $unitOfMeasurement */
    public function setUnitOfMeasurement(array $unitOfMeasurement): self
    {
        $this->unitOfMeasurement = $unitOfMeasurement;

        return $this;
    }

    /**
     * The count of how many Schedule B units of the current good are in the shipment (EEI only).
     * For example, if the Schedule B unit of measure is dozens and eight dozen, is being shipped,
     * indicate 8 in this field. Applies to EEI forms only. Conditionally required for EEI forms if
     * ScheduleB UnitOfMeasurement is not X. Should be Numeric. Valid characters are 0 -9.
     *
     * @param list<string> $quantity
     */
    public function setQuantity(array $quantity): self
    {
        $this->quantity = Some::create($quantity);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ProductScheduleB
    {
        return new ProductScheduleB(
            $this->number,
            $this->unitOfMeasurement,
            $this->quantity,
            $this->additionalProperties,
        );
    }
}
