<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class ProductProductWeight implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(
        private ProductWeightUnitOfMeasurement $unitOfMeasurement,
        private string $weight,
        private array $additionalProperties,
    ) {
    }

    public static function builder(
        ProductWeightUnitOfMeasurement $unitOfMeasurement,
        string $weight,
    ): ProductProductWeightBuilder {
        return new ProductProductWeightBuilder($unitOfMeasurement, $weight, []);
    }

    /**
     * Container tag for the Unit of Measurement of weight. Applies to CO and EEI forms only.
     */
    public function getUnitOfMeasurement(): ProductWeightUnitOfMeasurement
    {
        return $this->unitOfMeasurement;
    }

    /**
     * Weight of Product. Applies to CO and EEI forms only. Valid characters are 0-9 and '.'
     * (Decimal point). Limit to 1 digit after the decimal. The maximum length of the field is 5
     * including '.' and can hold up to 1 decimal place.
     */
    public function getWeight(): string
    {
        return $this->weight;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $unitOfMeasurement = null;
        $weight = null;
        if (array_key_exists('UnitOfMeasurement', $data)) {
            $unitOfMeasurementRaw = $data['UnitOfMeasurement'];
            if (!is_array($unitOfMeasurementRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "UnitOfMeasurement" must be object, got %s.',
                        get_debug_type($unitOfMeasurementRaw),
                    ),
                );
            }
            /** @var non-empty-array<string, mixed> $unitOfMeasurementRawTyped */
            $unitOfMeasurementRawTyped = $unitOfMeasurementRaw;
            $unitOfMeasurement = ProductWeightUnitOfMeasurement::fromArray($unitOfMeasurementRawTyped);
        }
        if (array_key_exists('Weight', $data)) {
            $weightRaw = $data['Weight'];
            if (!is_string($weightRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Weight" must be string, got %s.', get_debug_type($weightRaw)),
                );
            }
            $weight = $weightRaw;
        }
        $additionalProperties = array_diff_key($data, ['UnitOfMeasurement' => true, 'Weight' => true]);
        if ($unitOfMeasurement === null) {
            throw new MalformedDataException('Required property "UnitOfMeasurement" is missing from the document.');
        }
        if ($weight === null) {
            throw new MalformedDataException('Required property "Weight" is missing from the document.');
        }

        return new self($unitOfMeasurement, $weight, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['UnitOfMeasurement'] = $normalizationTarget->model($this->unitOfMeasurement);
        $dataArray['Weight'] = $this->weight;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ProductProductWeightBuilder
    {
        return new ProductProductWeightBuilder($this->unitOfMeasurement, $this->weight, $this->additionalProperties);
    }
}
