<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

/**
 * Builds a {@see ResponseAlert}.
 */
final class ResponseAlertBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private string $code, private string $description, private array $additionalProperties)
    {
    }

    /**
     * Warning code returned by the system.
     */
    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Warning messages returned by the system.
     */
    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ResponseAlert
    {
        return new ResponseAlert($this->code, $this->description, $this->additionalProperties);
    }
}
