<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see ShipToAddress}.
 */
final class ShipToAddressBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param list<string>             $addressLine
     * @param Option<string>           $stateProvinceCode
     * @param Option<string>           $postalCode
     * @param Option<string>           $residentialAddressIndicator
     * @param Option<string>           $pOBoxIndicator
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private array $addressLine,
        private string $city,
        private string $countryCode,
        private Option $stateProvinceCode,
        private Option $postalCode,
        private Option $residentialAddressIndicator,
        private Option $pOBoxIndicator,
        private array $additionalProperties,
    ) {
    }

    /**
     * Address Line of the consignee. All three Address Lines will be printed on the label.
     *
     * @param list<string> $addressLine
     */
    public function setAddressLine(array $addressLine): self
    {
        $this->addressLine = $addressLine;

        return $this;
    }

    /**
     * Consignee's city. 30 characters are accepted, but only 15 characters will be printed on the
     * label.
     */
    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Consignee's country or territory code. Must be a valid UPS Billing country or territory code.
     * For Return Shipment the country or territory code must meet the following conditions:
     * - At least two of the following country or territory codes are the same: ShipTo, ShipFrom,
     *   and Shipper.
     * - None of the following country or territory codes are the same and are a member of the EU:
     *   ShipTo, ShipFrom, and Shipper.
     * - If any of the two following country or territory codes: ShipTo/ ShipFrom/ Shipper are
     *   members in EU otherwise check if the shipper has Third country or territory Contract.
     */
    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = $countryCode;

        return $this;
    }

    /**
     * Consignee’s state or province code. Required for US, Canada, and Vietnam (VN).
     *
     * - For US or Canada, the value must be a valid US state or Canadian province code.
     * - For Vietnam (VN), the value must be a valid province code (for example, VN-44).
     * - If the country or territory is Ireland, the StateProvinceCode must contain the county.
     */
    public function setStateProvinceCode(string $stateProvinceCode): self
    {
        $this->stateProvinceCode = Some::create($stateProvinceCode);

        return $this;
    }

    /**
     * Consignee's postal code. If the ShipTo country or territory is US or Puerto Rico, 5 or 9
     * digits are required.
     *
     * If the ShipTo country or territory is CA, then the postal code is required and must be 6
     * alphanumeric characters whose format is A#A#A# where A is an uppercase letter and # is a
     * digit.
     *
     * Otherwise optional. For all other countries or territories the postal code is optional and
     * must be no more than 9 alphanumeric characters long.
     */
    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = Some::create($postalCode);

        return $this;
    }

    /**
     * This field is a flag to indicate if the receiver is a residential location. True if
     * ResidentialAddressIndicator tag exists. This is an empty tag, any value inside is ignored.
     */
    public function setResidentialAddressIndicator(string $residentialAddressIndicator): self
    {
        $this->residentialAddressIndicator = Some::create($residentialAddressIndicator);

        return $this;
    }

    /**
     * This field is a flag to indicate if the receiver address has PO box indicator. True if
     * POBoxIndicator tag exists; false otherwise.
     */
    public function setPOBoxIndicator(string $pOBoxIndicator): self
    {
        $this->pOBoxIndicator = Some::create($pOBoxIndicator);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipToAddress
    {
        return new ShipToAddress(
            $this->addressLine,
            $this->city,
            $this->countryCode,
            $this->stateProvinceCode,
            $this->postalCode,
            $this->residentialAddressIndicator,
            $this->pOBoxIndicator,
            $this->additionalProperties,
        );
    }
}
