<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see ShipmentResultsForm}.
 */
final class ShipmentResultsFormBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>                   $code
     * @param Option<string>                   $description
     * @param Option<ShipmentResultsFormImage> $image
     * @param Option<string>                   $formGroupId
     * @param Option<string>                   $formGroupIdName
     * @param array<int|string, mixed>         $additionalProperties
     */
    public function __construct(
        private Option $code,
        private Option $description,
        private Option $image,
        private Option $formGroupId,
        private Option $formGroupIdName,
        private array $additionalProperties,
    ) {
    }

    /**
     * Code that indicates the type of form.
     *
     * Valid values: 01 - All Requested International Forms.
     */
    public function setCode(string $code): self
    {
        $this->code = Some::create($code);

        return $this;
    }

    /**
     * Description that indicates the type of form. Possible Values. All Requested International
     * Forms.
     */
    public function setDescription(string $description): self
    {
        $this->description = Some::create($description);

        return $this;
    }

    /**
     * Container tag for the International forms image.
     */
    public function setImage(ShipmentResultsFormImage $image): self
    {
        $this->image = Some::create($image);

        return $this;
    }

    /**
     * Unique Id for later retrieval of saved version of the completed international forms. Always
     * returned when code = 01. 01 represents international forms.
     */
    public function setFormGroupId(string $formGroupId): self
    {
        $this->formGroupId = Some::create($formGroupId);

        return $this;
    }

    /**
     * Contains description text which identifies the group of International forms. This element is
     * part of both request and response. This element does not appear on the forms.
     */
    public function setFormGroupIdName(string $formGroupIdName): self
    {
        $this->formGroupIdName = Some::create($formGroupIdName);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentResultsForm
    {
        return new ShipmentResultsForm(
            $this->code,
            $this->description,
            $this->image,
            $this->formGroupId,
            $this->formGroupIdName,
            $this->additionalProperties,
        );
    }
}
