<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see ShipmentFreightShipmentInformation}.
 */
final class ShipmentFreightShipmentInformationBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<FreightShipmentInformationFreightDensityInfo> $freightDensityInfo
     * @param Option<string>                                       $densityEligibleIndicator
     * @param array<int|string, mixed>                             $additionalProperties
     */
    public function __construct(
        private Option $freightDensityInfo,
        private Option $densityEligibleIndicator,
        private array $additionalProperties,
    ) {
    }

    /**
     * Freight Density Info container. Required if DensityEligibleIndicator is present.
     */
    public function setFreightDensityInfo(FreightShipmentInformationFreightDensityInfo $freightDensityInfo): self
    {
        $this->freightDensityInfo = Some::create($freightDensityInfo);

        return $this;
    }

    /**
     * The presence of the tag indicates that the rate request is density based. For Density Based
     * Rating (DBR), the customer must have DBR Contract Service.
     */
    public function setDensityEligibleIndicator(string $densityEligibleIndicator): self
    {
        $this->densityEligibleIndicator = Some::create($densityEligibleIndicator);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentFreightShipmentInformation
    {
        return new ShipmentFreightShipmentInformation(
            $this->freightDensityInfo,
            $this->densityEligibleIndicator,
            $this->additionalProperties,
        );
    }
}
