<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see ShipmentShipTo}.
 */
final class ShipmentShipToBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $attentionName
     * @param Option<string>           $companyDisplayableName
     * @param Option<string>           $taxIdentificationNumber
     * @param Option<ShipToPhone>      $phone
     * @param Option<string>           $faxNumber
     * @param Option<string>           $eMailAddress
     * @param Option<string>           $locationID
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $name,
        private ShipToAddress $address,
        private Option $attentionName,
        private Option $companyDisplayableName,
        private Option $taxIdentificationNumber,
        private Option $phone,
        private Option $faxNumber,
        private Option $eMailAddress,
        private Option $locationID,
        private array $additionalProperties,
    ) {
    }

    /**
     * Consignee's company name. All other accounts must be either a daily pickup account or an
     * occasional account.
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Address Container.
     */
    public function setAddress(ShipToAddress $address): self
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Contact name at the consignee's location. Required for: UPS Next Day Air® Early service, and
     * when ShipTo country or territory is different than ShipFrom country or territory.
     *
     * Required if Invoice International form is requested.
     */
    public function setAttentionName(string $attentionName): self
    {
        $this->attentionName = Some::create($attentionName);

        return $this;
    }

    /**
     * Not applicable for ShipTo.
     */
    public function setCompanyDisplayableName(string $companyDisplayableName): self
    {
        $this->companyDisplayableName = Some::create($companyDisplayableName);

        return $this;
    }

    /**
     * Consignee's tax identification number. This element has been deprecated, replacement can be
     * found in the GlobalTaxInformation container.
     *
     * @deprecated
     */
    public function setTaxIdentificationNumber(string $taxIdentificationNumber): self
    {
        $this->taxIdentificationNumber = Some::create($taxIdentificationNumber);

        return $this;
    }

    /**
     * Container for Phone Number.
     */
    public function setPhone(ShipToPhone $phone): self
    {
        $this->phone = Some::create($phone);

        return $this;
    }

    /**
     * Consignee's fax number. If ShipTo country or territory is US 10 digits allowed, otherwise
     * 1-15 digits allowed.
     */
    public function setFaxNumber(string $faxNumber): self
    {
        $this->faxNumber = Some::create($faxNumber);

        return $this;
    }

    /**
     * Consignee's email address.
     */
    public function setEMailAddress(string $eMailAddress): self
    {
        $this->eMailAddress = Some::create($eMailAddress);

        return $this;
    }

    /**
     * Location ID is a unique identifier referring to a specific shipping/receiving location.
     * Location ID must be alphanumeric characters. All letters must be capitalized.
     */
    public function setLocationID(string $locationID): self
    {
        $this->locationID = Some::create($locationID);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentShipTo
    {
        return new ShipmentShipTo(
            $this->name,
            $this->address,
            $this->attentionName,
            $this->companyDisplayableName,
            $this->taxIdentificationNumber,
            $this->phone,
            $this->faxNumber,
            $this->eMailAddress,
            $this->locationID,
            $this->additionalProperties,
        );
    }
}
