<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

/**
 * Builds a {@see ShipmentWorldEasePortOfEntry}.
 */
final class ShipmentWorldEasePortOfEntryBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $name,
        private string $clearancePortCode,
        private string $consignee,
        private AddressPOE $address,
        private array $additionalProperties,
    ) {
    }

    /**
     * Port of entry name.
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Port code.
     */
    public function setClearancePortCode(string $clearancePortCode): self
    {
        $this->clearancePortCode = $clearancePortCode;

        return $this;
    }

    /**
     * Port of entry consignee.
     */
    public function setConsignee(string $consignee): self
    {
        $this->consignee = $consignee;

        return $this;
    }

    public function setAddress(AddressPOE $address): self
    {
        $this->address = $address;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentWorldEasePortOfEntry
    {
        return new ShipmentWorldEasePortOfEntry(
            $this->name,
            $this->clearancePortCode,
            $this->consignee,
            $this->address,
            $this->additionalProperties,
        );
    }
}
