<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class ShipmentWorldEase implements SelfNormalizingModel
{
    /**
     * @param ShipmentWorldEaseMasterShipmentChgType|UnknownEnumValue<string> $masterShipmentChgType
     * @param Option<string>                                                  $destinationPostalCode
     * @param Option<string>                                                  $gCCN
     * @param Option<string>                                                  $masterEUConsolidationIndicator
     * @param Option<string>                                                  $masterHasDocBox
     * @param Option<string>                                                  $vendorCollectIDNumberExemptIndicator
     * @param array<int|string, mixed>                                        $additionalProperties
     */
    public function __construct(
        private string $destinationCountryCode,
        private ShipmentWorldEaseMasterShipmentChgType|UnknownEnumValue $masterShipmentChgType,
        private ShipmentWorldEasePortOfEntry $portOfEntry,
        private Option $destinationPostalCode,
        private Option $gCCN,
        private Option $masterEUConsolidationIndicator,
        private Option $masterHasDocBox,
        private Option $vendorCollectIDNumberExemptIndicator,
        private array $additionalProperties,
    ) {
    }

    public static function builder(
        string $destinationCountryCode,
        ShipmentWorldEaseMasterShipmentChgType $masterShipmentChgType,
        ShipmentWorldEasePortOfEntry $portOfEntry,
    ): ShipmentWorldEaseBuilder {
        return new ShipmentWorldEaseBuilder(
            $destinationCountryCode,
            $masterShipmentChgType,
            $portOfEntry,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * The final destination country code.
     */
    public function getDestinationCountryCode(): string
    {
        return $this->destinationCountryCode;
    }

    /**
     * The final destination postal code.
     *
     * @return Option<string>
     */
    public function getDestinationPostalCode(): Option
    {
        return $this->destinationPostalCode;
    }

    /**
     * The Global Consolidation Clearance Number(GCCN) generated for the master shipment. This is
     * required for child shipment.
     *
     * @return Option<string>
     */
    public function getGCCN(): Option
    {
        return $this->gCCN;
    }

    /**
     * 1 indicates a Master Consolidation request for the European Union.
     *
     * @return Option<string>
     */
    public function getMasterEUConsolidationIndicator(): Option
    {
        return $this->masterEUConsolidationIndicator;
    }

    /**
     * This field indicates whether the shipment is a master shipment and specifies the document box
     * type. This is required for Master shipment only.
     *
     * Valid values
     *
     * 0 - Virtual DocBox
     *
     * 1 - Physical DocBox.
     *
     * @return Option<string>
     */
    public function getMasterHasDocBox(): Option
    {
        return $this->masterHasDocBox;
    }

    /**
     * Code that indicates how shipping charges will be paid.
     *
     * | Code  | Name                | Description:                                                              |
     * | :--:  | :--                 | :--                                                                       |
     * | CAF   | Cost And Freight    | Shipper pays to point of import, conignee pays balance.                   |
     * | COL   | Freight Collect     | Consignee (with valid UPS account) pays all shipping charges              |
     * | DDP   | Delivered Duty Paid | Shipper pays shipping and duty, consignee pays the Value Added Tax (VAT)  |
     * | FOB   | Free On Board       | Shipper pays to point to export, consignee pays balance                   |
     * | PRE   | Prepaid             | Shipper pays all shipping charges                                         |
     * | SDT   | Free Domicile       | Child Shipper pays for shipping, duities and taxes                        |
     *
     * @return ShipmentWorldEaseMasterShipmentChgType|UnknownEnumValue<string>
     */
    public function getMasterShipmentChgType(): ShipmentWorldEaseMasterShipmentChgType|UnknownEnumValue
    {
        return $this->masterShipmentChgType;
    }

    /**
     * This field indicates if VendorCollectIDTypeCode and VendorCollectIDNumber should be exempt
     * from validation. "0" indicates VendorCollectIDTypeCode and VendorCollectIDNumber fields are
     * required.
     *
     * @return Option<string>
     */
    public function getVendorCollectIDNumberExemptIndicator(): Option
    {
        return $this->vendorCollectIDNumberExemptIndicator;
    }

    /**
     * Container for port of entry details.
     */
    public function getPortOfEntry(): ShipmentWorldEasePortOfEntry
    {
        return $this->portOfEntry;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $destinationCountryCode = null;
        $destinationPostalCode = None::create();
        $gCCN = None::create();
        $masterEUConsolidationIndicator = None::create();
        $masterHasDocBox = None::create();
        $masterShipmentChgType = null;
        $vendorCollectIDNumberExemptIndicator = None::create();
        $portOfEntry = null;
        if (array_key_exists('DestinationCountryCode', $data)) {
            $destinationCountryCodeRaw = $data['DestinationCountryCode'];
            if (!is_string($destinationCountryCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "DestinationCountryCode" must be string, got %s.',
                        get_debug_type($destinationCountryCodeRaw),
                    ),
                );
            }
            $destinationCountryCode = $destinationCountryCodeRaw;
        }
        if (array_key_exists('DestinationPostalCode', $data) && $data['DestinationPostalCode'] !== null) {
            $destinationPostalCodeRaw = $data['DestinationPostalCode'];
            if (!is_string($destinationPostalCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "DestinationPostalCode" must be string, got %s.',
                        get_debug_type($destinationPostalCodeRaw),
                    ),
                );
            }
            $destinationPostalCode = Some::create($destinationPostalCodeRaw);
        }
        if (array_key_exists('GCCN', $data) && $data['GCCN'] !== null) {
            $gCCNRaw = $data['GCCN'];
            if (!is_string($gCCNRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "GCCN" must be string, got %s.', get_debug_type($gCCNRaw)),
                );
            }
            $gCCN = Some::create($gCCNRaw);
        }
        if (
            array_key_exists('MasterEUConsolidationIndicator', $data)
            && $data['MasterEUConsolidationIndicator'] !== null
        ) {
            $masterEUConsolidationIndicatorRaw = $data['MasterEUConsolidationIndicator'];
            if (!is_string($masterEUConsolidationIndicatorRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "MasterEUConsolidationIndicator" must be string, got %s.',
                        get_debug_type($masterEUConsolidationIndicatorRaw),
                    ),
                );
            }
            $masterEUConsolidationIndicator = Some::create($masterEUConsolidationIndicatorRaw);
        }
        if (array_key_exists('MasterHasDocBox', $data) && $data['MasterHasDocBox'] !== null) {
            $masterHasDocBoxRaw = $data['MasterHasDocBox'];
            if (!is_string($masterHasDocBoxRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "MasterHasDocBox" must be string, got %s.', get_debug_type($masterHasDocBoxRaw)),
                );
            }
            $masterHasDocBox = Some::create($masterHasDocBoxRaw);
        }
        if (array_key_exists('MasterShipmentChgType', $data)) {
            $masterShipmentChgTypeRaw = $data['MasterShipmentChgType'];
            if (!is_string($masterShipmentChgTypeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "MasterShipmentChgType" must be string, got %s.',
                        get_debug_type($masterShipmentChgTypeRaw),
                    ),
                );
            }
            $masterShipmentChgType = ShipmentWorldEaseMasterShipmentChgType::tryFrom($masterShipmentChgTypeRaw)
                ?? UnknownEnumValue::of($masterShipmentChgTypeRaw);
        }
        if (
            array_key_exists('VendorCollectIDNumberExemptIndicator', $data)
            && $data['VendorCollectIDNumberExemptIndicator'] !== null
        ) {
            $vendorCollectIDNumberExemptIndicatorRaw = $data['VendorCollectIDNumberExemptIndicator'];
            if (!is_string($vendorCollectIDNumberExemptIndicatorRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "VendorCollectIDNumberExemptIndicator" must be string, got %s.',
                        get_debug_type($vendorCollectIDNumberExemptIndicatorRaw),
                    ),
                );
            }
            $vendorCollectIDNumberExemptIndicator = Some::create($vendorCollectIDNumberExemptIndicatorRaw);
        }
        if (array_key_exists('PortOfEntry', $data)) {
            $portOfEntryRaw = $data['PortOfEntry'];
            if (!is_array($portOfEntryRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "PortOfEntry" must be object, got %s.', get_debug_type($portOfEntryRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $portOfEntryRawTyped */
            $portOfEntryRawTyped = $portOfEntryRaw;
            $portOfEntry = ShipmentWorldEasePortOfEntry::fromArray($portOfEntryRawTyped);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'DestinationCountryCode' => true,
                'DestinationPostalCode' => true,
                'GCCN' => true,
                'MasterEUConsolidationIndicator' => true,
                'MasterHasDocBox' => true,
                'MasterShipmentChgType' => true,
                'VendorCollectIDNumberExemptIndicator' => true,
                'PortOfEntry' => true,
            ],
        );
        if ($destinationCountryCode === null) {
            throw new MalformedDataException(
                'Required property "DestinationCountryCode" is missing from the document.',
            );
        }
        if ($masterShipmentChgType === null) {
            throw new MalformedDataException('Required property "MasterShipmentChgType" is missing from the document.');
        }
        if ($portOfEntry === null) {
            throw new MalformedDataException('Required property "PortOfEntry" is missing from the document.');
        }

        return new self(
            $destinationCountryCode,
            $masterShipmentChgType,
            $portOfEntry,
            $destinationPostalCode,
            $gCCN,
            $masterEUConsolidationIndicator,
            $masterHasDocBox,
            $vendorCollectIDNumberExemptIndicator,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['DestinationCountryCode'] = $this->destinationCountryCode;
        $destinationPostalCodeOption = $this->destinationPostalCode;
        if ($destinationPostalCodeOption->isDefined()) {
            $destinationPostalCode = $destinationPostalCodeOption->get();
            $dataArray['DestinationPostalCode'] = $destinationPostalCode;
        }
        $gCCNOption = $this->gCCN;
        if ($gCCNOption->isDefined()) {
            $gCCN = $gCCNOption->get();
            $dataArray['GCCN'] = $gCCN;
        }
        $masterEUConsolidationIndicatorOption = $this->masterEUConsolidationIndicator;
        if ($masterEUConsolidationIndicatorOption->isDefined()) {
            $masterEUConsolidationIndicator = $masterEUConsolidationIndicatorOption->get();
            $dataArray['MasterEUConsolidationIndicator'] = $masterEUConsolidationIndicator;
        }
        $masterHasDocBoxOption = $this->masterHasDocBox;
        if ($masterHasDocBoxOption->isDefined()) {
            $masterHasDocBox = $masterHasDocBoxOption->get();
            $dataArray['MasterHasDocBox'] = $masterHasDocBox;
        }
        $dataArray['MasterShipmentChgType'] = $this->masterShipmentChgType->value;
        $vendorCollectIDNumberExemptIndicatorOption = $this->vendorCollectIDNumberExemptIndicator;
        if ($vendorCollectIDNumberExemptIndicatorOption->isDefined()) {
            $vendorCollectIDNumberExemptIndicator = $vendorCollectIDNumberExemptIndicatorOption->get();
            $dataArray['VendorCollectIDNumberExemptIndicator'] = $vendorCollectIDNumberExemptIndicator;
        }
        $dataArray['PortOfEntry'] = $normalizationTarget->model($this->portOfEntry);
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ShipmentWorldEaseBuilder
    {
        return new ShipmentWorldEaseBuilder(
            $this->destinationCountryCode,
            $this->masterShipmentChgType,
            $this->portOfEntry,
            $this->destinationPostalCode,
            $this->gCCN,
            $this->masterEUConsolidationIndicator,
            $this->masterHasDocBox,
            $this->vendorCollectIDNumberExemptIndicator,
            $this->additionalProperties,
        );
    }
}
