<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class SHIPRequestWrapper implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(private ShipmentRequest $shipmentRequest, private array $additionalProperties)
    {
    }

    public static function builder(ShipmentRequest $shipmentRequest): SHIPRequestWrapperBuilder
    {
        return new SHIPRequestWrapperBuilder($shipmentRequest, []);
    }

    /**
     * Shipment Request.
     */
    public function getShipmentRequest(): ShipmentRequest
    {
        return $this->shipmentRequest;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $shipmentRequest = null;
        if (array_key_exists('ShipmentRequest', $data)) {
            $shipmentRequestRaw = $data['ShipmentRequest'];
            if (!is_array($shipmentRequestRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "ShipmentRequest" must be object, got %s.', get_debug_type($shipmentRequestRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $shipmentRequestRawTyped */
            $shipmentRequestRawTyped = $shipmentRequestRaw;
            $shipmentRequest = ShipmentRequest::fromArray($shipmentRequestRawTyped);
        }
        $additionalProperties = array_diff_key($data, ['ShipmentRequest' => true]);
        if ($shipmentRequest === null) {
            throw new MalformedDataException('Required property "ShipmentRequest" is missing from the document.');
        }

        return new self($shipmentRequest, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['ShipmentRequest'] = $normalizationTarget->model($this->shipmentRequest);
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): SHIPRequestWrapperBuilder
    {
        return new SHIPRequestWrapperBuilder($this->shipmentRequest, $this->additionalProperties);
    }
}
