<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class ShipmentResultsFRSShipmentData implements SelfNormalizingModel
{
    /**
     * @param Option<FRSShipmentDataFreightDensityRate>  $freightDensityRate
     * @param Option<list<FRSShipmentDataHandlingUnits>> $handlingUnits
     * @param array<int|string, mixed>                   $additionalProperties
     */
    public function __construct(
        private FRSShipmentDataTransportationCharges $transportationCharges,
        private Option $freightDensityRate,
        private Option $handlingUnits,
        private array $additionalProperties,
    ) {
    }

    public static function builder(
        FRSShipmentDataTransportationCharges $transportationCharges,
    ): ShipmentResultsFRSShipmentDataBuilder {
        return new ShipmentResultsFRSShipmentDataBuilder($transportationCharges, None::create(), None::create(), []);
    }

    /**
     * Transportation charges container. Ground Freight Pricing transportation charges. These are
     * only returned for Ground Freight Pricing enabled shipper account number when the user
     * includes the FRSShipmentIndicator in the request.
     */
    public function getTransportationCharges(): FRSShipmentDataTransportationCharges
    {
        return $this->transportationCharges;
    }

    /**
     * FreightDensityRate container for Density based rating.
     *
     * @return Option<FRSShipmentDataFreightDensityRate>
     */
    public function getFreightDensityRate(): Option
    {
        return $this->freightDensityRate;
    }

    /**
     * Handling Unit for Density based rating container.
     *
     * **NOTE:** For versions >= v2403, this element will always be returned as an array. For
     * requests using versions < v2403, this element will be returned as an array if there is more
     * than one object and a single object if there is only 1.
     *
     * @return Option<list<FRSShipmentDataHandlingUnits>>
     */
    public function getHandlingUnits(): Option
    {
        return $this->handlingUnits;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $transportationCharges = null;
        $freightDensityRate = None::create();
        $handlingUnits = None::create();
        if (array_key_exists('TransportationCharges', $data)) {
            $transportationChargesRaw = $data['TransportationCharges'];
            if (!is_array($transportationChargesRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "TransportationCharges" must be object, got %s.',
                        get_debug_type($transportationChargesRaw),
                    ),
                );
            }
            /** @var non-empty-array<string, mixed> $transportationChargesRawTyped */
            $transportationChargesRawTyped = $transportationChargesRaw;
            $transportationCharges = FRSShipmentDataTransportationCharges::fromArray($transportationChargesRawTyped);
        }
        if (array_key_exists('FreightDensityRate', $data) && $data['FreightDensityRate'] !== null) {
            $freightDensityRateRaw = $data['FreightDensityRate'];
            if (!is_array($freightDensityRateRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "FreightDensityRate" must be object, got %s.',
                        get_debug_type($freightDensityRateRaw),
                    ),
                );
            }
            /** @var non-empty-array<string, mixed> $freightDensityRateRawTyped */
            $freightDensityRateRawTyped = $freightDensityRateRaw;
            $freightDensityRate = Some::create(
                FRSShipmentDataFreightDensityRate::fromArray($freightDensityRateRawTyped),
            );
        }
        if (array_key_exists('HandlingUnits', $data) && $data['HandlingUnits'] !== null) {
            $handlingUnitsRaw = $data['HandlingUnits'];
            if (!(is_array($handlingUnitsRaw) && array_is_list($handlingUnitsRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "HandlingUnits" must be list, got %s.', get_debug_type($handlingUnitsRaw)),
                );
            }
            $handlingUnits = Some::create(array_map(static function (mixed $value): FRSShipmentDataHandlingUnits {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var non-empty-array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return FRSShipmentDataHandlingUnits::fromArray($valueTyped);
            }, $handlingUnitsRaw));
        }
        $additionalProperties = array_diff_key(
            $data,
            ['TransportationCharges' => true, 'FreightDensityRate' => true, 'HandlingUnits' => true],
        );
        if ($transportationCharges === null) {
            throw new MalformedDataException('Required property "TransportationCharges" is missing from the document.');
        }

        return new self($transportationCharges, $freightDensityRate, $handlingUnits, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['TransportationCharges'] = $normalizationTarget->model($this->transportationCharges);
        $freightDensityRateOption = $this->freightDensityRate;
        if ($freightDensityRateOption->isDefined()) {
            $freightDensityRate = $freightDensityRateOption->get();
            $dataArray['FreightDensityRate'] = $normalizationTarget->model($freightDensityRate);
        }
        $handlingUnitsOption = $this->handlingUnits;
        if ($handlingUnitsOption->isDefined()) {
            $handlingUnits = $handlingUnitsOption->get();
            $values = [];
            foreach ($handlingUnits as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['HandlingUnits'] = $values;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ShipmentResultsFRSShipmentDataBuilder
    {
        return new ShipmentResultsFRSShipmentDataBuilder(
            $this->transportationCharges,
            $this->freightDensityRate,
            $this->handlingUnits,
            $this->additionalProperties,
        );
    }
}
