<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see ShipmentRequestLabelSpecification}.
 */
final class ShipmentRequestLabelSpecificationBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>                              $hTTPUserAgent
     * @param Option<list<LabelSpecificationInstruction>> $instruction
     * @param Option<string>                              $characterSet
     * @param array<int|string, mixed>                    $additionalProperties
     */
    public function __construct(
        private LabelSpecificationLabelImageFormat $labelImageFormat,
        private LabelSpecificationLabelStockSize $labelStockSize,
        private Option $hTTPUserAgent,
        private Option $instruction,
        private Option $characterSet,
        private array $additionalProperties,
    ) {
    }

    /**
     * LabelImageFormat Container.
     */
    public function setLabelImageFormat(LabelSpecificationLabelImageFormat $labelImageFormat): self
    {
        $this->labelImageFormat = $labelImageFormat;

        return $this;
    }

    /**
     * Container for the EPL2, ZPL or SPL label size. Valid for EPL2, ZPL and SPL Labels.
     */
    public function setLabelStockSize(LabelSpecificationLabelStockSize $labelStockSize): self
    {
        $this->labelStockSize = $labelStockSize;

        return $this;
    }

    /**
     * Browser HTTPUserAgent String. This is the preferred way of identifying GIF image type to be
     * generated. Required if
     * /ShipmentRequest/LabelSpecificationLabelSpecification/LabelImageFormat/Code = Gif. Default to
     * Mozilla/4.5 if this field is missing or has invalid value.
     */
    public function setHTTPUserAgent(string $hTTPUserAgent): self
    {
        $this->hTTPUserAgent = Some::create($hTTPUserAgent);

        return $this;
    }

    /** @param list<LabelSpecificationInstruction> $instruction */
    public function setInstruction(array $instruction): self
    {
        $this->instruction = Some::create($instruction);

        return $this;
    }

    /**
     * Language character set expected on label. Valid values: dan = Danish (Latin-1) nld = Dutch
     * (Latin-1) fin = Finnish (Latin-1) fra = French (Latin-1) deu = German (Latin-1) itl = Italian
     * (Latin-1) nor = Norwegian (Latin-1) pol = Polish (Latin-2) por = Poruguese (Latin-1) spa =
     * Spanish (Latin-1) swe = Swedish (Latin-1) ces = Czech (Latin-2) hun = Hungarian (Latin-2) slk
     * = Slovak (Latin-2) rus = Russian (Cyrillic) tur = Turkish (Latin-5) ron = Romanian (Latin-2)
     * bul = Bulgarian (Latin-2) est = Estonian (Latin-2) ell = Greek (Latin-2) lav = Latvian
     * (Latin-2) lit = Lithuanian (Latin-2) eng = English (Latin-1) Default is English (Latin-1).
     */
    public function setCharacterSet(string $characterSet): self
    {
        $this->characterSet = Some::create($characterSet);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentRequestLabelSpecification
    {
        return new ShipmentRequestLabelSpecification(
            $this->labelImageFormat,
            $this->labelStockSize,
            $this->hTTPUserAgent,
            $this->instruction,
            $this->characterSet,
            $this->additionalProperties,
        );
    }
}
