<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see ShipmentWorldEase}.
 */
final class ShipmentWorldEaseBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param ShipmentWorldEaseMasterShipmentChgType|UnknownEnumValue<string> $masterShipmentChgType
     * @param Option<string>                                                  $destinationPostalCode
     * @param Option<string>                                                  $gCCN
     * @param Option<string>                                                  $masterEUConsolidationIndicator
     * @param Option<string>                                                  $masterHasDocBox
     * @param Option<string>                                                  $vendorCollectIDNumberExemptIndicator
     * @param array<int|string, mixed>                                        $additionalProperties
     */
    public function __construct(
        private string $destinationCountryCode,
        private ShipmentWorldEaseMasterShipmentChgType|UnknownEnumValue $masterShipmentChgType,
        private ShipmentWorldEasePortOfEntry $portOfEntry,
        private Option $destinationPostalCode,
        private Option $gCCN,
        private Option $masterEUConsolidationIndicator,
        private Option $masterHasDocBox,
        private Option $vendorCollectIDNumberExemptIndicator,
        private array $additionalProperties,
    ) {
    }

    /**
     * The final destination country code.
     */
    public function setDestinationCountryCode(string $destinationCountryCode): self
    {
        $this->destinationCountryCode = $destinationCountryCode;

        return $this;
    }

    /**
     * Code that indicates how shipping charges will be paid.
     *
     * | Code  | Name                | Description:                                                              |
     * | :--:  | :--                 | :--                                                                       |
     * | CAF   | Cost And Freight    | Shipper pays to point of import, conignee pays balance.                   |
     * | COL   | Freight Collect     | Consignee (with valid UPS account) pays all shipping charges              |
     * | DDP   | Delivered Duty Paid | Shipper pays shipping and duty, consignee pays the Value Added Tax (VAT)  |
     * | FOB   | Free On Board       | Shipper pays to point to export, consignee pays balance                   |
     * | PRE   | Prepaid             | Shipper pays all shipping charges                                         |
     * | SDT   | Free Domicile       | Child Shipper pays for shipping, duities and taxes                        |
     */
    public function setMasterShipmentChgType(ShipmentWorldEaseMasterShipmentChgType $masterShipmentChgType): self
    {
        $this->masterShipmentChgType = $masterShipmentChgType;

        return $this;
    }

    /**
     * Container for port of entry details.
     */
    public function setPortOfEntry(ShipmentWorldEasePortOfEntry $portOfEntry): self
    {
        $this->portOfEntry = $portOfEntry;

        return $this;
    }

    /**
     * The final destination postal code.
     */
    public function setDestinationPostalCode(string $destinationPostalCode): self
    {
        $this->destinationPostalCode = Some::create($destinationPostalCode);

        return $this;
    }

    /**
     * The Global Consolidation Clearance Number(GCCN) generated for the master shipment. This is
     * required for child shipment.
     */
    public function setGCCN(string $gCCN): self
    {
        $this->gCCN = Some::create($gCCN);

        return $this;
    }

    /**
     * 1 indicates a Master Consolidation request for the European Union.
     */
    public function setMasterEUConsolidationIndicator(string $masterEUConsolidationIndicator): self
    {
        $this->masterEUConsolidationIndicator = Some::create($masterEUConsolidationIndicator);

        return $this;
    }

    /**
     * This field indicates whether the shipment is a master shipment and specifies the document box
     * type. This is required for Master shipment only.
     *
     * Valid values
     *
     * 0 - Virtual DocBox
     *
     * 1 - Physical DocBox.
     */
    public function setMasterHasDocBox(string $masterHasDocBox): self
    {
        $this->masterHasDocBox = Some::create($masterHasDocBox);

        return $this;
    }

    /**
     * This field indicates if VendorCollectIDTypeCode and VendorCollectIDNumber should be exempt
     * from validation. "0" indicates VendorCollectIDTypeCode and VendorCollectIDNumber fields are
     * required.
     */
    public function setVendorCollectIDNumberExemptIndicator(string $vendorCollectIDNumberExemptIndicator): self
    {
        $this->vendorCollectIDNumberExemptIndicator = Some::create($vendorCollectIDNumberExemptIndicator);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentWorldEase
    {
        return new ShipmentWorldEase(
            $this->destinationCountryCode,
            $this->masterShipmentChgType,
            $this->portOfEntry,
            $this->destinationPostalCode,
            $this->gCCN,
            $this->masterEUConsolidationIndicator,
            $this->masterHasDocBox,
            $this->vendorCollectIDNumberExemptIndicator,
            $this->additionalProperties,
        );
    }
}
