<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see ShipmentResponseResponse}.
 */
final class ShipmentResponseResponseBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<list<ResponseAlert>>          $alert
     * @param Option<ResponseTransactionReference> $transactionReference
     * @param array<int|string, mixed>             $additionalProperties
     */
    public function __construct(
        private ResponseResponseStatus $responseStatus,
        private Option $alert,
        private Option $transactionReference,
        private array $additionalProperties,
    ) {
    }

    /**
     * Response status container.
     */
    public function setResponseStatus(ResponseResponseStatus $responseStatus): self
    {
        $this->responseStatus = $responseStatus;

        return $this;
    }

    /**
     * Alert Container. There can be zero to many alert containers with code and description.
     *
     * **NOTE:** For versions >= v2403, this element will always be returned as an array. For
     * requests using versions < v2403, this element will be returned as an array if there is more
     * than one object and a single object if there is only 1.
     *
     * @param list<ResponseAlert> $alert
     */
    public function setAlert(array $alert): self
    {
        $this->alert = Some::create($alert);

        return $this;
    }

    /**
     * Transaction Reference Container.
     */
    public function setTransactionReference(ResponseTransactionReference $transactionReference): self
    {
        $this->transactionReference = Some::create($transactionReference);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentResponseResponse
    {
        return new ShipmentResponseResponse(
            $this->responseStatus,
            $this->alert,
            $this->transactionReference,
            $this->additionalProperties,
        );
    }
}
