<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class ShipmentRequestLabelSpecification implements SelfNormalizingModel
{
    /**
     * @param Option<string>                              $hTTPUserAgent
     * @param Option<list<LabelSpecificationInstruction>> $instruction
     * @param Option<string>                              $characterSet
     * @param array<int|string, mixed>                    $additionalProperties
     */
    public function __construct(
        private LabelSpecificationLabelImageFormat $labelImageFormat,
        private LabelSpecificationLabelStockSize $labelStockSize,
        private Option $hTTPUserAgent,
        private Option $instruction,
        private Option $characterSet,
        private array $additionalProperties,
    ) {
    }

    public static function builder(
        LabelSpecificationLabelImageFormat $labelImageFormat,
        LabelSpecificationLabelStockSize $labelStockSize,
    ): ShipmentRequestLabelSpecificationBuilder {
        return new ShipmentRequestLabelSpecificationBuilder(
            $labelImageFormat,
            $labelStockSize,
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * LabelImageFormat Container.
     */
    public function getLabelImageFormat(): LabelSpecificationLabelImageFormat
    {
        return $this->labelImageFormat;
    }

    /**
     * Browser HTTPUserAgent String. This is the preferred way of identifying GIF image type to be
     * generated. Required if
     * /ShipmentRequest/LabelSpecificationLabelSpecification/LabelImageFormat/Code = Gif. Default to
     * Mozilla/4.5 if this field is missing or has invalid value.
     *
     * @return Option<string>
     */
    public function getHTTPUserAgent(): Option
    {
        return $this->hTTPUserAgent;
    }

    /**
     * Container for the EPL2, ZPL or SPL label size. Valid for EPL2, ZPL and SPL Labels.
     */
    public function getLabelStockSize(): LabelSpecificationLabelStockSize
    {
        return $this->labelStockSize;
    }

    /** @return Option<list<LabelSpecificationInstruction>> */
    public function getInstruction(): Option
    {
        return $this->instruction;
    }

    /**
     * Language character set expected on label. Valid values: dan = Danish (Latin-1) nld = Dutch
     * (Latin-1) fin = Finnish (Latin-1) fra = French (Latin-1) deu = German (Latin-1) itl = Italian
     * (Latin-1) nor = Norwegian (Latin-1) pol = Polish (Latin-2) por = Poruguese (Latin-1) spa =
     * Spanish (Latin-1) swe = Swedish (Latin-1) ces = Czech (Latin-2) hun = Hungarian (Latin-2) slk
     * = Slovak (Latin-2) rus = Russian (Cyrillic) tur = Turkish (Latin-5) ron = Romanian (Latin-2)
     * bul = Bulgarian (Latin-2) est = Estonian (Latin-2) ell = Greek (Latin-2) lav = Latvian
     * (Latin-2) lit = Lithuanian (Latin-2) eng = English (Latin-1) Default is English (Latin-1).
     *
     * @return Option<string>
     */
    public function getCharacterSet(): Option
    {
        return $this->characterSet;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $labelImageFormat = null;
        $hTTPUserAgent = None::create();
        $labelStockSize = null;
        $instruction = None::create();
        $characterSet = None::create();
        if (array_key_exists('LabelImageFormat', $data)) {
            $labelImageFormatRaw = $data['LabelImageFormat'];
            if (!is_array($labelImageFormatRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "LabelImageFormat" must be object, got %s.',
                        get_debug_type($labelImageFormatRaw),
                    ),
                );
            }
            /** @var non-empty-array<string, mixed> $labelImageFormatRawTyped */
            $labelImageFormatRawTyped = $labelImageFormatRaw;
            $labelImageFormat = LabelSpecificationLabelImageFormat::fromArray($labelImageFormatRawTyped);
        }
        if (array_key_exists('HTTPUserAgent', $data) && $data['HTTPUserAgent'] !== null) {
            $hTTPUserAgentRaw = $data['HTTPUserAgent'];
            if (!is_string($hTTPUserAgentRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "HTTPUserAgent" must be string, got %s.', get_debug_type($hTTPUserAgentRaw)),
                );
            }
            $hTTPUserAgent = Some::create($hTTPUserAgentRaw);
        }
        if (array_key_exists('LabelStockSize', $data)) {
            $labelStockSizeRaw = $data['LabelStockSize'];
            if (!is_array($labelStockSizeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "LabelStockSize" must be object, got %s.', get_debug_type($labelStockSizeRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $labelStockSizeRawTyped */
            $labelStockSizeRawTyped = $labelStockSizeRaw;
            $labelStockSize = LabelSpecificationLabelStockSize::fromArray($labelStockSizeRawTyped);
        }
        if (array_key_exists('Instruction', $data) && $data['Instruction'] !== null) {
            $instructionRaw = $data['Instruction'];
            if (!(is_array($instructionRaw) && array_is_list($instructionRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "Instruction" must be list, got %s.', get_debug_type($instructionRaw)),
                );
            }
            $instruction = Some::create(array_map(static function (mixed $value): LabelSpecificationInstruction {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var non-empty-array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return LabelSpecificationInstruction::fromArray($valueTyped);
            }, $instructionRaw));
        }
        if (array_key_exists('CharacterSet', $data) && $data['CharacterSet'] !== null) {
            $characterSetRaw = $data['CharacterSet'];
            if (!is_string($characterSetRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "CharacterSet" must be string, got %s.', get_debug_type($characterSetRaw)),
                );
            }
            $characterSet = Some::create($characterSetRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'LabelImageFormat' => true,
                'HTTPUserAgent' => true,
                'LabelStockSize' => true,
                'Instruction' => true,
                'CharacterSet' => true,
            ],
        );
        if ($labelImageFormat === null) {
            throw new MalformedDataException('Required property "LabelImageFormat" is missing from the document.');
        }
        if ($labelStockSize === null) {
            throw new MalformedDataException('Required property "LabelStockSize" is missing from the document.');
        }

        return new self(
            $labelImageFormat,
            $labelStockSize,
            $hTTPUserAgent,
            $instruction,
            $characterSet,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['LabelImageFormat'] = $normalizationTarget->model($this->labelImageFormat);
        $hTTPUserAgentOption = $this->hTTPUserAgent;
        if ($hTTPUserAgentOption->isDefined()) {
            $hTTPUserAgent = $hTTPUserAgentOption->get();
            $dataArray['HTTPUserAgent'] = $hTTPUserAgent;
        }
        $dataArray['LabelStockSize'] = $normalizationTarget->model($this->labelStockSize);
        $instructionOption = $this->instruction;
        if ($instructionOption->isDefined()) {
            $instruction = $instructionOption->get();
            $values = [];
            foreach ($instruction as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['Instruction'] = $values;
        }
        $characterSetOption = $this->characterSet;
        if ($characterSetOption->isDefined()) {
            $characterSet = $characterSetOption->get();
            $dataArray['CharacterSet'] = $characterSet;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ShipmentRequestLabelSpecificationBuilder
    {
        return new ShipmentRequestLabelSpecificationBuilder(
            $this->labelImageFormat,
            $this->labelStockSize,
            $this->hTTPUserAgent,
            $this->instruction,
            $this->characterSet,
            $this->additionalProperties,
        );
    }
}
