<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class ShipmentServiceOptionsNotification implements SelfNormalizingModel
{
    /**
     * @param Option<NotificationVoiceMessage> $voiceMessage
     * @param Option<NotificationTextMessage>  $textMessage
     * @param Option<NotificationLocale>       $locale
     * @param array<int|string, mixed>         $additionalProperties
     */
    public function __construct(
        private string $notificationCode,
        private NotificationEMail $eMail,
        private Option $voiceMessage,
        private Option $textMessage,
        private Option $locale,
        private array $additionalProperties,
    ) {
    }

    public static function builder(
        string $notificationCode,
        NotificationEMail $eMail,
    ): ShipmentServiceOptionsNotificationBuilder {
        return new ShipmentServiceOptionsNotificationBuilder(
            $notificationCode,
            $eMail,
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * The type of notification requested.
     *
     * Note:
     * - QVN Exception notification and return notification are not applicable to GFP.
     * - QV In-transit and Return Notifications are only valid for ImportControl and Return
     *   shipment.
     * - QV In-transit Notification is allowed for return shipments only.
     * - QV Ship Notification is allowed for forward moving shipments only.
     *
     * Valid values:
     * - 5 - QV In-transit Notification
     * - 6 - QV Ship Notification
     * - 7 - QV Exception Notification
     * - 8 - QV Delivery Notification
     * - 2 - Return Notification or Label Creation Notification
     * - 012 - Alternate Delivery Location Notification
     * - 013 - UAP Shipper Notification.
     */
    public function getNotificationCode(): string
    {
        return $this->notificationCode;
    }

    /**
     * Container for Email Information.
     */
    public function getEMail(): NotificationEMail
    {
        return $this->eMail;
    }

    /**
     * VoiceMessage container is used for specifying phone number for receiving voice Alternate
     * Delivery Location notification and UAP Shipper notification. Valid only for Alternate
     * Delivery Location notification and UAP Shipper notification. VoiceMessage phone number or
     * TextMessage phone number or email address is required for ADL notification and UAP Shipper
     * notification.
     *
     * @return Option<NotificationVoiceMessage>
     */
    public function getVoiceMessage(): Option
    {
        return $this->voiceMessage;
    }

    /**
     * TextMessage container is used for specifying phone number for receiving text Alternate
     * Delivery Location notification and UAP Shipper notification. Valid only for Alternate
     * Delivery Location notification and UAP Shipper notification. VoiceMessage phone number or
     * TextMessage phone number or email address is required for ADL notification and UAP Shipper
     * notification.
     *
     * @return Option<NotificationTextMessage>
     */
    public function getTextMessage(): Option
    {
        return $this->textMessage;
    }

    /**
     * This container is used for providing Language and dialect details for Alternate Delivery
     * Location notifications and UAP Shipper notifications. Valid only for Alternate Delivery
     * Location notification and UAP Shipper notification.
     *
     * @return Option<NotificationLocale>
     */
    public function getLocale(): Option
    {
        return $this->locale;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $notificationCode = null;
        $eMail = null;
        $voiceMessage = None::create();
        $textMessage = None::create();
        $locale = None::create();
        if (array_key_exists('NotificationCode', $data)) {
            $notificationCodeRaw = $data['NotificationCode'];
            if (!is_string($notificationCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "NotificationCode" must be string, got %s.',
                        get_debug_type($notificationCodeRaw),
                    ),
                );
            }
            $notificationCode = $notificationCodeRaw;
        }
        if (array_key_exists('EMail', $data)) {
            $eMailRaw = $data['EMail'];
            if (!is_array($eMailRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "EMail" must be object, got %s.', get_debug_type($eMailRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $eMailRawTyped */
            $eMailRawTyped = $eMailRaw;
            $eMail = NotificationEMail::fromArray($eMailRawTyped);
        }
        if (array_key_exists('VoiceMessage', $data) && $data['VoiceMessage'] !== null) {
            $voiceMessageRaw = $data['VoiceMessage'];
            if (!is_array($voiceMessageRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "VoiceMessage" must be object, got %s.', get_debug_type($voiceMessageRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $voiceMessageRawTyped */
            $voiceMessageRawTyped = $voiceMessageRaw;
            $voiceMessage = Some::create(NotificationVoiceMessage::fromArray($voiceMessageRawTyped));
        }
        if (array_key_exists('TextMessage', $data) && $data['TextMessage'] !== null) {
            $textMessageRaw = $data['TextMessage'];
            if (!is_array($textMessageRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "TextMessage" must be object, got %s.', get_debug_type($textMessageRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $textMessageRawTyped */
            $textMessageRawTyped = $textMessageRaw;
            $textMessage = Some::create(NotificationTextMessage::fromArray($textMessageRawTyped));
        }
        if (array_key_exists('Locale', $data) && $data['Locale'] !== null) {
            $localeRaw = $data['Locale'];
            if (!is_array($localeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Locale" must be object, got %s.', get_debug_type($localeRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $localeRawTyped */
            $localeRawTyped = $localeRaw;
            $locale = Some::create(NotificationLocale::fromArray($localeRawTyped));
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'NotificationCode' => true,
                'EMail' => true,
                'VoiceMessage' => true,
                'TextMessage' => true,
                'Locale' => true,
            ],
        );
        if ($notificationCode === null) {
            throw new MalformedDataException('Required property "NotificationCode" is missing from the document.');
        }
        if ($eMail === null) {
            throw new MalformedDataException('Required property "EMail" is missing from the document.');
        }

        return new self($notificationCode, $eMail, $voiceMessage, $textMessage, $locale, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['NotificationCode'] = $this->notificationCode;
        $dataArray['EMail'] = $normalizationTarget->model($this->eMail);
        $voiceMessageOption = $this->voiceMessage;
        if ($voiceMessageOption->isDefined()) {
            $voiceMessage = $voiceMessageOption->get();
            $dataArray['VoiceMessage'] = $normalizationTarget->model($voiceMessage);
        }
        $textMessageOption = $this->textMessage;
        if ($textMessageOption->isDefined()) {
            $textMessage = $textMessageOption->get();
            $dataArray['TextMessage'] = $normalizationTarget->model($textMessage);
        }
        $localeOption = $this->locale;
        if ($localeOption->isDefined()) {
            $locale = $localeOption->get();
            $dataArray['Locale'] = $normalizationTarget->model($locale);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ShipmentServiceOptionsNotificationBuilder
    {
        return new ShipmentServiceOptionsNotificationBuilder(
            $this->notificationCode,
            $this->eMail,
            $this->voiceMessage,
            $this->textMessage,
            $this->locale,
            $this->additionalProperties,
        );
    }
}
