<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see ShipmentChargeBillThirdParty}.
 */
final class ShipmentChargeBillThirdPartyBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $accountNumber
     * @param Option<string>           $certifiedElectronicMail
     * @param Option<string>           $interchangeSystemCode
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private BillThirdPartyAddress $address,
        private Option $accountNumber,
        private Option $certifiedElectronicMail,
        private Option $interchangeSystemCode,
        private array $additionalProperties,
    ) {
    }

    /**
     * Container for additional information for the third party UPS accounts address.
     */
    public function setAddress(BillThirdPartyAddress $address): self
    {
        $this->address = $address;

        return $this;
    }

    /**
     * The UPS account number of the third party shipper. The account must be a valid UPS account
     * number that is active.
     *
     * For US, PR and CA accounts, the account must be either a daily pickup account, an occasional
     * account, or a customer B.I.N account, or a drop shipper account.
     *
     * All other accounts must be either a daily pickup account, an occasional account, a drop
     * shipper account, or a non-shipping account.
     */
    public function setAccountNumber(string $accountNumber): self
    {
        $this->accountNumber = Some::create($accountNumber);

        return $this;
    }

    /**
     * Posta Elettronica Certificata (PEC) which is the recipient code for the customers certified
     * electronic mail value.
     */
    public function setCertifiedElectronicMail(string $certifiedElectronicMail): self
    {
        $this->certifiedElectronicMail = Some::create($certifiedElectronicMail);

        return $this;
    }

    /**
     * Sistema Di Interscambio(SDI) which is the recipient code for the customer's interchange value
     * or Interchange System Code.
     */
    public function setInterchangeSystemCode(string $interchangeSystemCode): self
    {
        $this->interchangeSystemCode = Some::create($interchangeSystemCode);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentChargeBillThirdParty
    {
        return new ShipmentChargeBillThirdParty(
            $this->address,
            $this->accountNumber,
            $this->certifiedElectronicMail,
            $this->interchangeSystemCode,
            $this->additionalProperties,
        );
    }
}
