<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class ShipmentFreightShipmentInformation implements SelfNormalizingModel
{
    /**
     * @param Option<FreightShipmentInformationFreightDensityInfo> $freightDensityInfo
     * @param Option<string>                                       $densityEligibleIndicator
     * @param array<int|string, mixed>                             $additionalProperties
     */
    public function __construct(
        private Option $freightDensityInfo,
        private Option $densityEligibleIndicator,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ShipmentFreightShipmentInformationBuilder
    {
        return new ShipmentFreightShipmentInformationBuilder(None::create(), None::create(), []);
    }

    /**
     * Freight Density Info container. Required if DensityEligibleIndicator is present.
     *
     * @return Option<FreightShipmentInformationFreightDensityInfo>
     */
    public function getFreightDensityInfo(): Option
    {
        return $this->freightDensityInfo;
    }

    /**
     * The presence of the tag indicates that the rate request is density based. For Density Based
     * Rating (DBR), the customer must have DBR Contract Service.
     *
     * @return Option<string>
     */
    public function getDensityEligibleIndicator(): Option
    {
        return $this->densityEligibleIndicator;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $freightDensityInfo = None::create();
        $densityEligibleIndicator = None::create();
        if (array_key_exists('FreightDensityInfo', $data) && $data['FreightDensityInfo'] !== null) {
            $freightDensityInfoRaw = $data['FreightDensityInfo'];
            if (!is_array($freightDensityInfoRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "FreightDensityInfo" must be object, got %s.',
                        get_debug_type($freightDensityInfoRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $freightDensityInfoRawTyped */
            $freightDensityInfoRawTyped = $freightDensityInfoRaw;
            $freightDensityInfo = Some::create(
                FreightShipmentInformationFreightDensityInfo::fromArray($freightDensityInfoRawTyped),
            );
        }
        if (array_key_exists('DensityEligibleIndicator', $data) && $data['DensityEligibleIndicator'] !== null) {
            $densityEligibleIndicatorRaw = $data['DensityEligibleIndicator'];
            if (!is_string($densityEligibleIndicatorRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "DensityEligibleIndicator" must be string, got %s.',
                        get_debug_type($densityEligibleIndicatorRaw),
                    ),
                );
            }
            $densityEligibleIndicator = Some::create($densityEligibleIndicatorRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            ['FreightDensityInfo' => true, 'DensityEligibleIndicator' => true],
        );

        return new self($freightDensityInfo, $densityEligibleIndicator, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $freightDensityInfoOption = $this->freightDensityInfo;
        if ($freightDensityInfoOption->isDefined()) {
            $freightDensityInfo = $freightDensityInfoOption->get();
            $dataArray['FreightDensityInfo'] = $normalizationTarget->model($freightDensityInfo);
        }
        $densityEligibleIndicatorOption = $this->densityEligibleIndicator;
        if ($densityEligibleIndicatorOption->isDefined()) {
            $densityEligibleIndicator = $densityEligibleIndicatorOption->get();
            $dataArray['DensityEligibleIndicator'] = $densityEligibleIndicator;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ShipmentFreightShipmentInformationBuilder
    {
        return new ShipmentFreightShipmentInformationBuilder(
            $this->freightDensityInfo,
            $this->densityEligibleIndicator,
            $this->additionalProperties,
        );
    }
}
