<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see ShipmentTradeDirect}.
 */
final class ShipmentTradeDirectBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param ShipmentTradeDirectShipmentType|UnknownEnumValue<string> $shipmentType
     * @param Option<TradeDirectMaster>                                $master
     * @param Option<TradeDirectChild>                                 $child
     * @param Option<string>                                           $generalDescriptionOfGoods
     * @param array<int|string, mixed>                                 $additionalProperties
     */
    public function __construct(
        private ShipmentTradeDirectShipmentType|UnknownEnumValue $shipmentType,
        private string $currencyCode,
        private Option $master,
        private Option $child,
        private Option $generalDescriptionOfGoods,
        private array $additionalProperties,
    ) {
    }

    /**
     * Consolidated shipment types.
     *
     * Valid values:
     * - TRADEDIRECTAIR = TradeDirect Air - consolidation, custom clearance, deconsolidation and
     *   delivery to multiple addresses within destination country, with Airport-to-door or
     *   door-to-door.
     *
     * - TRADEDIRECTOCEAN = TradeDirect Ocean - consolidation, ocean transportation, customs
     *   clearance, deconsolidation and delivery to multiple addresses within a destination country,
     *   with port-to-door and door-to-door service from shipper to consignee. Available from more
     *   than 70 ports.
     *
     * - TRADEDIRECTCROSSBORDER = TradeDirect CrossBoarder - consolidation, customs clearance,
     *   deconsolidation and delivery to multiple addresses within the destination country, with
     *   door-to-door service across North American borders.
     */
    public function setShipmentType(ShipmentTradeDirectShipmentType $shipmentType): self
    {
        $this->shipmentType = $shipmentType;

        return $this;
    }

    /**
     * The currency code for the shipment as per ISO 4217.
     */
    public function setCurrencyCode(string $currencyCode): self
    {
        $this->currencyCode = $currencyCode;

        return $this;
    }

    /**
     * A collection of small package and LTL/TL shipments that are transported by UPS from the
     * customer to the destination CFS.
     */
    public function setMaster(TradeDirectMaster $master): self
    {
        $this->master = Some::create($master);

        return $this;
    }

    /**
     * A small package or LTL/TL shipment associated with a Trade Direct Master.
     */
    public function setChild(TradeDirectChild $child): self
    {
        $this->child = Some::create($child);

        return $this;
    }

    /**
     * General description of the goods being shipped. It is required for master shipment.
     */
    public function setGeneralDescriptionOfGoods(string $generalDescriptionOfGoods): self
    {
        $this->generalDescriptionOfGoods = Some::create($generalDescriptionOfGoods);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentTradeDirect
    {
        return new ShipmentTradeDirect(
            $this->shipmentType,
            $this->currencyCode,
            $this->master,
            $this->child,
            $this->generalDescriptionOfGoods,
            $this->additionalProperties,
        );
    }
}
