<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see ShipmentResultsPalletLabel}.
 */
final class ShipmentResultsPalletLabelBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $palletLabel
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $palletLabel, private array $additionalProperties)
    {
    }

    /**
     * Base64-encoded graphic image of Pallet.
     */
    public function setPalletLabel(string $palletLabel): self
    {
        $this->palletLabel = Some::create($palletLabel);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentResultsPalletLabel
    {
        return new ShipmentResultsPalletLabel($this->palletLabel, $this->additionalProperties);
    }
}
