<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see ShipmentResultsDisclaimer}.
 */
final class ShipmentResultsDisclaimerBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $description
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private string $code, private Option $description, private array $additionalProperties)
    {
    }

    /**
     * Code representing type of Disclaimer. Refer to Disclaimer Codes and Messages in the Appendix
     * for various disclaimers that would be possible for a given shipment.
     */
    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Disclaimer description. This field would be returned only if TaxInformationIndicator is
     * present in a request.
     *
     * Refer to Disclaimer Codes and Messages in the Appendix for various disclaimers that would be
     * possible for a given shipment.
     */
    public function setDescription(string $description): self
    {
        $this->description = Some::create($description);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentResultsDisclaimer
    {
        return new ShipmentResultsDisclaimer($this->code, $this->description, $this->additionalProperties);
    }
}
