<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class ShipmentFRSPaymentInformation implements SelfNormalizingModel
{
    /**
     * @param Option<FRSPaymentInformationAddress> $address
     * @param array<int|string, mixed>             $additionalProperties
     */
    public function __construct(
        private FRSPaymentInformationType $type,
        private string $accountNumber,
        private Option $address,
        private array $additionalProperties,
    ) {
    }

    public static function builder(
        FRSPaymentInformationType $type,
        string $accountNumber,
    ): ShipmentFRSPaymentInformationBuilder {
        return new ShipmentFRSPaymentInformationBuilder($type, $accountNumber, None::create(), []);
    }

    /**
     * Container to hold the Ground Freight Pricing payment type information. It is required if the
     * request has Ground Freight Pricing shipment indicator.
     */
    public function getType(): FRSPaymentInformationType
    {
        return $this->type;
    }

    /**
     * The UPS account number. If the Ground Freight Pricing indicator and
     * FreightShipmentInformation/DensityEligibleIndicator is present in the request, this account
     * number must be validated to check if it is Ground Freight Pricing Density Based Rating
     * enabled.
     */
    public function getAccountNumber(): string
    {
        return $this->accountNumber;
    }

    /**
     * Container to hold the information for the FreightCollect and PrepaidThirdParty Address. Note:
     * The Address is required only when the billing option is Freight collect or ThirdParty.
     *
     * @return Option<FRSPaymentInformationAddress>
     */
    public function getAddress(): Option
    {
        return $this->address;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $type = null;
        $accountNumber = null;
        $address = None::create();
        if (array_key_exists('Type', $data)) {
            $typeRaw = $data['Type'];
            if (!is_array($typeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Type" must be object, got %s.', get_debug_type($typeRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $typeRawTyped */
            $typeRawTyped = $typeRaw;
            $type = FRSPaymentInformationType::fromArray($typeRawTyped);
        }
        if (array_key_exists('AccountNumber', $data)) {
            $accountNumberRaw = $data['AccountNumber'];
            if (!is_string($accountNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "AccountNumber" must be string, got %s.', get_debug_type($accountNumberRaw)),
                );
            }
            $accountNumber = $accountNumberRaw;
        }
        if (array_key_exists('Address', $data) && $data['Address'] !== null) {
            $addressRaw = $data['Address'];
            if (!is_array($addressRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Address" must be object, got %s.', get_debug_type($addressRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $addressRawTyped */
            $addressRawTyped = $addressRaw;
            $address = Some::create(FRSPaymentInformationAddress::fromArray($addressRawTyped));
        }
        $additionalProperties = array_diff_key($data, ['Type' => true, 'AccountNumber' => true, 'Address' => true]);
        if ($type === null) {
            throw new MalformedDataException('Required property "Type" is missing from the document.');
        }
        if ($accountNumber === null) {
            throw new MalformedDataException('Required property "AccountNumber" is missing from the document.');
        }

        return new self($type, $accountNumber, $address, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['Type'] = $normalizationTarget->model($this->type);
        $dataArray['AccountNumber'] = $this->accountNumber;
        $addressOption = $this->address;
        if ($addressOption->isDefined()) {
            $address = $addressOption->get();
            $dataArray['Address'] = $normalizationTarget->model($address);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ShipmentFRSPaymentInformationBuilder
    {
        return new ShipmentFRSPaymentInformationBuilder(
            $this->type,
            $this->accountNumber,
            $this->address,
            $this->additionalProperties,
        );
    }
}
