<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see ShipmentShipmentServiceOptions}.
 */
final class ShipmentShipmentServiceOptionsBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>                                           $saturdayDeliveryIndicator
     * @param Option<string>                                           $saturdayPickupIndicator
     * @param Option<ShipmentServiceOptionsCOD>                        $cOD
     * @param Option<ShipmentServiceOptionsAccessPointCOD>             $accessPointCOD
     * @param Option<string>                                           $deliverToAddresseeOnlyIndicator
     * @param Option<string>                                           $directDeliveryOnlyIndicator
     * @param Option<list<ShipmentServiceOptionsNotification>>         $notification
     * @param Option<ShipmentServiceOptionsLabelDelivery>              $labelDelivery
     * @param Option<ShipmentServiceOptionsInternationalForms>         $internationalForms
     * @param Option<ShipmentServiceOptionsDeliveryConfirmation>       $deliveryConfirmation
     * @param Option<string>                                           $returnOfDocumentIndicator
     * @param Option<string>                                           $importControlIndicator
     * @param Option<ShipmentServiceOptionsLabelMethod>                $labelMethod
     * @param Option<string>                                           $commercialInvoiceRemovalIndicator
     * @param Option<string>                                           $uPScarbonneutralIndicator
     * @param Option<list<ShipmentServiceOptionsPreAlertNotification>> $preAlertNotification
     * @param Option<string>                                           $exchangeForwardIndicator
     * @param Option<string>                                           $holdForPickupIndicator
     * @param Option<string>                                           $dropoffAtUPSFacilityIndicator
     * @param Option<string>                                           $liftGateForPickUpIndicator
     * @param Option<string>                                           $liftGateForDeliveryIndicator
     * @param Option<string>                                           $sDLShipmentIndicator
     * @param Option<string>                                           $ePRAReleaseCode
     * @param Option<ShipmentServiceOptionsRestrictedArticles>         $restrictedArticles
     * @param Option<string>                                           $insideDelivery
     * @param Option<string>                                           $itemDisposal
     * @param Option<ShipmentServiceOptionsVerifiedDelivery>           $verifiedDelivery
     * @param array<int|string, mixed>                                 $additionalProperties
     */
    public function __construct(
        private Option $saturdayDeliveryIndicator,
        private Option $saturdayPickupIndicator,
        private Option $cOD,
        private Option $accessPointCOD,
        private Option $deliverToAddresseeOnlyIndicator,
        private Option $directDeliveryOnlyIndicator,
        private Option $notification,
        private Option $labelDelivery,
        private Option $internationalForms,
        private Option $deliveryConfirmation,
        private Option $returnOfDocumentIndicator,
        private Option $importControlIndicator,
        private Option $labelMethod,
        private Option $commercialInvoiceRemovalIndicator,
        private Option $uPScarbonneutralIndicator,
        private Option $preAlertNotification,
        private Option $exchangeForwardIndicator,
        private Option $holdForPickupIndicator,
        private Option $dropoffAtUPSFacilityIndicator,
        private Option $liftGateForPickUpIndicator,
        private Option $liftGateForDeliveryIndicator,
        private Option $sDLShipmentIndicator,
        private Option $ePRAReleaseCode,
        private Option $restrictedArticles,
        private Option $insideDelivery,
        private Option $itemDisposal,
        private Option $verifiedDelivery,
        private array $additionalProperties,
    ) {
    }

    /**
     * Saturday delivery indicator. The presence indicates Saturday delivery is requested and the
     * absence indicates Saturday delivery is not requested. This is an empty tag, any value inside
     * is ignored.
     */
    public function setSaturdayDeliveryIndicator(string $saturdayDeliveryIndicator): self
    {
        $this->saturdayDeliveryIndicator = Some::create($saturdayDeliveryIndicator);

        return $this;
    }

    /**
     * Saturday pickup indicator. The presence indicates Saturday pickup is requested and the
     * absence indicates Saturday pickup is not requested. This is an empty tag, any value inside is
     * ignored.
     */
    public function setSaturdayPickupIndicator(string $saturdayPickupIndicator): self
    {
        $this->saturdayPickupIndicator = Some::create($saturdayPickupIndicator);

        return $this;
    }

    /**
     * COD container Indicates COD is requested. Shipment COD is only available for EU origin
     * countries or territories and for shippers account type Daily Pickup and Drop Shipping. Not
     * available to shipment with return service.
     */
    public function setCOD(ShipmentServiceOptionsCOD $cOD): self
    {
        $this->cOD = Some::create($cOD);

        return $this;
    }

    /**
     * Access Point COD indicates COD is requested for a shipment. Valid only for "01 - Hold For
     * Pickup At UPS Access Point" Shipment Indication type. Shipment Access Point COD is valid only
     * for countries or territories within E.U. Not valid with (Shipment) COD. Not available to
     * shipment with return service.
     */
    public function setAccessPointCOD(ShipmentServiceOptionsAccessPointCOD $accessPointCOD): self
    {
        $this->accessPointCOD = Some::create($accessPointCOD);

        return $this;
    }

    /**
     * Presence/Absence Indicator. Any value inside is ignored. DeliverToAddresseeOnlyIndicator is
     * shipper specified restriction that requires the addressee to be the one who takes final
     * delivery of the "Hold For PickUp at UPS Access Point" package. Presence of indicator means
     * shipper restriction will apply to the shipment. Only valid for Shipment Indication type "01 -
     * Hold For PickUp at UPS Access Point".
     */
    public function setDeliverToAddresseeOnlyIndicator(string $deliverToAddresseeOnlyIndicator): self
    {
        $this->deliverToAddresseeOnlyIndicator = Some::create($deliverToAddresseeOnlyIndicator);

        return $this;
    }

    /**
     * Presence/Absence Indicator. Any value inside is ignored. Direct Delivery Only (DDO)
     * accessorial in a request would ensure that delivery is made only to the ship to address on
     * the shipping label. This accessorial is not valid with Shipment Indication Type "01 - Hold
     * For Pickup At UPS Access Point" and "02 - UPS Access Point™ Delivery".
     */
    public function setDirectDeliveryOnlyIndicator(string $directDeliveryOnlyIndicator): self
    {
        $this->directDeliveryOnlyIndicator = Some::create($directDeliveryOnlyIndicator);

        return $this;
    }

    /** @param list<ShipmentServiceOptionsNotification> $notification */
    public function setNotification(array $notification): self
    {
        $this->notification = Some::create($notification);

        return $this;
    }

    /**
     * Container for the Label Delivery accessorial. Note - LabelDelivery is not applicable for GFP
     * and Mail Innovations Forward shipment. Required for shipments with either Electronic Return
     * Label Return Service or ImportControl Electronic LabelMethod type. Optional for shipments
     * with Print Return Label Return Service or ImportControl Print LabelMethod type or Forward
     * movement. If this container is present for shipments with either Electronic Return Label
     * Return Service or ImportControl Electronic LabelMethod type, either of the
     * LabelLinksIndicator or EMail container should be provided. For shipments with Print Return
     * Label Return Service or ImportControl Print LabelMethod type or Forward movement, only
     * LabelLinksIndicator is valid option for LabelDelivery container.
     */
    public function setLabelDelivery(ShipmentServiceOptionsLabelDelivery $labelDelivery): self
    {
        $this->labelDelivery = Some::create($labelDelivery);

        return $this;
    }

    /**
     * International Forms information. This is applicable to Trade Direct SMALLPACKAGE
     * International Child movements and not applicable to Trade Direct Master or Trade Direct LTL
     * Child movements.
     */
    public function setInternationalForms(ShipmentServiceOptionsInternationalForms $internationalForms): self
    {
        $this->internationalForms = Some::create($internationalForms);

        return $this;
    }

    /**
     * Delivery Confirmation container. Valid for forward shipments only.
     *
     * Refer to Delivery Confirmation Origin-Destination Pairs in the Appendix for a list of valid
     * values.
     */
    public function setDeliveryConfirmation(ShipmentServiceOptionsDeliveryConfirmation $deliveryConfirmation): self
    {
        $this->deliveryConfirmation = Some::create($deliveryConfirmation);

        return $this;
    }

    /**
     * The flag indicates the ReturnOfDocument accessorial has been requested. Valid for Poland to
     * Poland forward shipment only.
     */
    public function setReturnOfDocumentIndicator(string $returnOfDocumentIndicator): self
    {
        $this->returnOfDocumentIndicator = Some::create($returnOfDocumentIndicator);

        return $this;
    }

    /**
     * Indicates that the Shipment is an ImportControl shipment.
     */
    public function setImportControlIndicator(string $importControlIndicator): self
    {
        $this->importControlIndicator = Some::create($importControlIndicator);

        return $this;
    }

    /**
     * Type of ImportControl Label. This container is applicable only for ImportControl shipments.
     * This container is applicable only for ImportControl shipments.
     */
    public function setLabelMethod(ShipmentServiceOptionsLabelMethod $labelMethod): self
    {
        $this->labelMethod = Some::create($labelMethod);

        return $this;
    }

    /**
     * CommercialInvoiceRemovalIndicator allows a shipper to dictate UPS to remove the Commercial
     * Invoice from the user's shipment before the shipment is delivered to the ultimate consignee.
     */
    public function setCommercialInvoiceRemovalIndicator(string $commercialInvoiceRemovalIndicator): self
    {
        $this->commercialInvoiceRemovalIndicator = Some::create($commercialInvoiceRemovalIndicator);

        return $this;
    }

    /**
     * UPS carbon offsets indicator presence at shipment level is required to create carbon offsets
     * Shipments.
     */
    public function setUPScarbonneutralIndicator(string $uPScarbonneutralIndicator): self
    {
        $this->uPScarbonneutralIndicator = Some::create($uPScarbonneutralIndicator);

        return $this;
    }

    /** @param list<ShipmentServiceOptionsPreAlertNotification> $preAlertNotification */
    public function setPreAlertNotification(array $preAlertNotification): self
    {
        $this->preAlertNotification = Some::create($preAlertNotification);

        return $this;
    }

    /**
     * Exchange forward indicator presence at shipment level is required to create exchange forward
     * Shipments. In the label routing Instruction text will be defaulted to "EXCHANGE-LIKE ITEM
     * ONLY".
     */
    public function setExchangeForwardIndicator(string $exchangeForwardIndicator): self
    {
        $this->exchangeForwardIndicator = Some::create($exchangeForwardIndicator);

        return $this;
    }

    /**
     * Hold For Pickup indicator. The empty tag means indicator is present. This accessorial is only
     * valid for UPS Worldwide Express Freight and UPS Worldwide Express Freight Midday Shipment.
     */
    public function setHoldForPickupIndicator(string $holdForPickupIndicator): self
    {
        $this->holdForPickupIndicator = Some::create($holdForPickupIndicator);

        return $this;
    }

    /**
     * Drop off At UPS Facility indicator. The empty tag means indicator is present. This
     * accessorial is only valid for UPS Worldwide Express Freight and UPS Worldwide Express Freight
     * Midday Shipment.
     */
    public function setDropoffAtUPSFacilityIndicator(string $dropoffAtUPSFacilityIndicator): self
    {
        $this->dropoffAtUPSFacilityIndicator = Some::create($dropoffAtUPSFacilityIndicator);

        return $this;
    }

    /**
     * Lift Gate For Pick Up indicator. The empty tag means indicator is present. Lift Gate for
     * Pickup is not allowed with Drop Off At UPS Facility for a UPS Worldwide Express Freight and
     * UPS Worldwide Express Freight Midday shipment.
     *
     * When both Hold for Pickup and Drop Off At Facility are selected, neither of the Lift Gate
     * accessorial (Pick Up or Delivery) are allowed for a UPS Worldwide Express Freight and UPS
     * Worldwide Express Freight Midday shipment.
     *
     * This accessorial is only valid for UPS Worldwide Express Freight and UPS Worldwide Express
     * Freight Midday Shipment.
     */
    public function setLiftGateForPickUpIndicator(string $liftGateForPickUpIndicator): self
    {
        $this->liftGateForPickUpIndicator = Some::create($liftGateForPickUpIndicator);

        return $this;
    }

    /**
     * Lift Gate For Delivery indicator. The empty tag means indicator is present. Lift Gate for
     * Delivery is not allowed with Hold For Pickup for a UPS Worldwide Express Freight and UPS
     * Worldwide Express Freight Midday shipment.
     *
     * When both Hold for Pickup and Drop Off At UPS Facility are selected, neither of the Lift Gate
     * accessorial (Pick Up or Delivery) are allowed for a UPS Worldwide Express Freight and UPS
     * Worldwide Express Freight Midday shipment.
     *
     * This accessorial is only valid for UPS Worldwide Express Freight and UPS Worldwide Express
     * Freight Midday Shipment.
     */
    public function setLiftGateForDeliveryIndicator(string $liftGateForDeliveryIndicator): self
    {
        $this->liftGateForDeliveryIndicator = Some::create($liftGateForDeliveryIndicator);

        return $this;
    }

    /**
     * The presence of the tag SDLShipmentIndicator indicates Shipment is SDL. SDLShipmentIndicator
     * presence means EEI form/ EEI Filing option required.
     */
    public function setSDLShipmentIndicator(string $sDLShipmentIndicator): self
    {
        $this->sDLShipmentIndicator = Some::create($sDLShipmentIndicator);

        return $this;
    }

    /**
     * Package Release code allows the consignee or claimant to pick-up a package at a UPS Access
     * Point™. The shipper must provide the Package Release Code to the consignee so that they can
     * provide the code to the UPS Access Point personnel as another item for authentication before
     * the package is released to them. Package Release Code is only valid with
     * ShipmentIndicationType 01 - Hold for Pickup at UPS Access Point™. The release code must be
     * between length 4 and 6 and only contain numbers.
     */
    public function setEPRAReleaseCode(string $ePRAReleaseCode): self
    {
        $this->ePRAReleaseCode = Some::create($ePRAReleaseCode);

        return $this;
    }

    /**
     * Restricted Articles container.
     */
    public function setRestrictedArticles(ShipmentServiceOptionsRestrictedArticles $restrictedArticles): self
    {
        $this->restrictedArticles = Some::create($restrictedArticles);

        return $this;
    }

    /**
     * Inside delivery accessory. Valid values: 01 - White Glove, 02 - Room of Choice, 03 -
     * Installation, 04 - Over Threshold Fee. Default is Room of Choice. Shippers account needs to
     * have a valid contract for Heavy Goods Service.
     */
    public function setInsideDelivery(string $insideDelivery): self
    {
        $this->insideDelivery = Some::create($insideDelivery);

        return $this;
    }

    /**
     * Presence/Absence indicator. True if present; false otherwise. Any value is ignored. If
     * present, indicates that the customer would like items disposed. Shippers account needs to
     * have a valid contract for Heavy Goods Service.
     */
    public function setItemDisposal(string $itemDisposal): self
    {
        $this->itemDisposal = Some::create($itemDisposal);

        return $this;
    }

    /**
     * Protected Delivery container required for Secure Pin Delivery. Protected Delivery will offer
     * shippers extra security to ensure their packages are delivered to the intended recipient.
     */
    public function setVerifiedDelivery(ShipmentServiceOptionsVerifiedDelivery $verifiedDelivery): self
    {
        $this->verifiedDelivery = Some::create($verifiedDelivery);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentShipmentServiceOptions
    {
        return new ShipmentShipmentServiceOptions(
            $this->saturdayDeliveryIndicator,
            $this->saturdayPickupIndicator,
            $this->cOD,
            $this->accessPointCOD,
            $this->deliverToAddresseeOnlyIndicator,
            $this->directDeliveryOnlyIndicator,
            $this->notification,
            $this->labelDelivery,
            $this->internationalForms,
            $this->deliveryConfirmation,
            $this->returnOfDocumentIndicator,
            $this->importControlIndicator,
            $this->labelMethod,
            $this->commercialInvoiceRemovalIndicator,
            $this->uPScarbonneutralIndicator,
            $this->preAlertNotification,
            $this->exchangeForwardIndicator,
            $this->holdForPickupIndicator,
            $this->dropoffAtUPSFacilityIndicator,
            $this->liftGateForPickUpIndicator,
            $this->liftGateForDeliveryIndicator,
            $this->sDLShipmentIndicator,
            $this->ePRAReleaseCode,
            $this->restrictedArticles,
            $this->insideDelivery,
            $this->itemDisposal,
            $this->verifiedDelivery,
            $this->additionalProperties,
        );
    }
}
