<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see SoldToAddress}.
 */
final class SoldToAddressBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param list<string>             $addressLine
     * @param Option<string>           $stateProvinceCode
     * @param Option<string>           $town
     * @param Option<string>           $postalCode
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private array $addressLine,
        private string $city,
        private string $countryCode,
        private Option $stateProvinceCode,
        private Option $town,
        private Option $postalCode,
        private array $additionalProperties,
    ) {
    }

    /**
     * SoldTo location's street address. Applies to USMCA.
     *
     * @param list<string> $addressLine
     */
    public function setAddressLine(array $addressLine): self
    {
        $this->addressLine = $addressLine;

        return $this;
    }

    /**
     * SoldTo location's city.
     */
    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * SoldTo location's country or territory code.
     */
    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = $countryCode;

        return $this;
    }

    /**
     * SoldTo location's state or province code. Required for US, Canada, and Vietnam (VN).
     *
     * - For US or Canada, the value must be a valid US state or Canadian province code.
     * - For Vietnam (VN), the value must be a valid province code (for example, VN-44).
     * - If the country or territory is Ireland, the StateProvinceCode must contain the county.
     */
    public function setStateProvinceCode(string $stateProvinceCode): self
    {
        $this->stateProvinceCode = Some::create($stateProvinceCode);

        return $this;
    }

    /**
     * SoldTo location's town code.
     */
    public function setTown(string $town): self
    {
        $this->town = Some::create($town);

        return $this;
    }

    /**
     * SoldTo location's postal code.
     */
    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = Some::create($postalCode);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): SoldToAddress
    {
        return new SoldToAddress(
            $this->addressLine,
            $this->city,
            $this->countryCode,
            $this->stateProvinceCode,
            $this->town,
            $this->postalCode,
            $this->additionalProperties,
        );
    }
}
