<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Optional\None;
use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class TradeDirectMaster implements SelfNormalizingModel
{
    /**
     * @param TradeDirectMasterUomType|UnknownEnumValue<string> $uomType
     * @param Option<string>                                    $soldToSameAsShipTo
     * @param Option<MasterSoldTo>                              $soldTo
     * @param Option<MasterPickup>                              $pickup
     * @param Option<MasterTradeComplianceDetails>              $tradeComplianceDetails
     * @param Option<TradeDirectNotificationBeforeDelivery>     $notificationBeforeDelivery
     * @param array<int|string, mixed>                          $additionalProperties
     */
    public function __construct(
        private TradeDirectMasterUomType|UnknownEnumValue $uomType,
        private Option $soldToSameAsShipTo,
        private Option $soldTo,
        private Option $pickup,
        private Option $tradeComplianceDetails,
        private Option $notificationBeforeDelivery,
        private array $additionalProperties,
    ) {
    }

    public static function builder(TradeDirectMasterUomType $uomType): TradeDirectMasterBuilder
    {
        return new TradeDirectMasterBuilder(
            $uomType,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * If Present indicates the Sold to and Ship To are the same.
     *
     * @return Option<string>
     */
    public function getSoldToSameAsShipTo(): Option
    {
        return $this->soldToSameAsShipTo;
    }

    /**
     * Contains the address and contact details of the shipments.
     *
     * @return Option<MasterSoldTo>
     */
    public function getSoldTo(): Option
    {
        return $this->soldTo;
    }

    /**
     * Contains the address and contact details of the shipments.
     *
     * @return Option<MasterPickup>
     */
    public function getPickup(): Option
    {
        return $this->pickup;
    }

    /**
     * Contains trade compliance details for the master shipment, such as invoice terms, export
     * reasons, and declaration statements. It also includes additional comments or instructions for
     * customs clearance.
     *
     * @return Option<MasterTradeComplianceDetails>
     */
    public function getTradeComplianceDetails(): Option
    {
        return $this->tradeComplianceDetails;
    }

    /**
     * The type of measurement used for the shipment. Imperial(lbs, in) & Metric(kgs, cm).
     *
     * Valid values are:
     *
     * - Imperial = This system of measurement uses units such as pounds (lbs) for weight and
     *   inches (in) for length.
     *
     * - Metric = This system of measurement uses units such as kilograms (kgs) for weight and
     *   centimeters (cm) for length.
     *
     * @return TradeDirectMasterUomType|UnknownEnumValue<string>
     */
    public function getUomType(): TradeDirectMasterUomType|UnknownEnumValue
    {
        return $this->uomType;
    }

    /**
     * Notification container for the before delivery notification.
     *
     * @return Option<TradeDirectNotificationBeforeDelivery>
     */
    public function getNotificationBeforeDelivery(): Option
    {
        return $this->notificationBeforeDelivery;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $soldToSameAsShipTo = None::create();
        $soldTo = None::create();
        $pickup = None::create();
        $tradeComplianceDetails = None::create();
        $uomType = null;
        $notificationBeforeDelivery = None::create();
        if (array_key_exists('SoldToSameAsShipTo', $data) && $data['SoldToSameAsShipTo'] !== null) {
            $soldToSameAsShipToRaw = $data['SoldToSameAsShipTo'];
            if (!is_string($soldToSameAsShipToRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "SoldToSameAsShipTo" must be string, got %s.',
                        get_debug_type($soldToSameAsShipToRaw),
                    ),
                );
            }
            $soldToSameAsShipTo = Some::create($soldToSameAsShipToRaw);
        }
        if (array_key_exists('SoldTo', $data) && $data['SoldTo'] !== null) {
            $soldToRaw = $data['SoldTo'];
            if (!is_array($soldToRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "SoldTo" must be object, got %s.', get_debug_type($soldToRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $soldToRawTyped */
            $soldToRawTyped = $soldToRaw;
            $soldTo = Some::create(MasterSoldTo::fromArray($soldToRawTyped));
        }
        if (array_key_exists('Pickup', $data) && $data['Pickup'] !== null) {
            $pickupRaw = $data['Pickup'];
            if (!is_array($pickupRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "Pickup" must be object, got %s.', get_debug_type($pickupRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $pickupRawTyped */
            $pickupRawTyped = $pickupRaw;
            $pickup = Some::create(MasterPickup::fromArray($pickupRawTyped));
        }
        if (array_key_exists('TradeComplianceDetails', $data) && $data['TradeComplianceDetails'] !== null) {
            $tradeComplianceDetailsRaw = $data['TradeComplianceDetails'];
            if (!is_array($tradeComplianceDetailsRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "TradeComplianceDetails" must be object, got %s.',
                        get_debug_type($tradeComplianceDetailsRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $tradeComplianceDetailsRawTyped */
            $tradeComplianceDetailsRawTyped = $tradeComplianceDetailsRaw;
            $tradeComplianceDetails = Some::create(
                MasterTradeComplianceDetails::fromArray($tradeComplianceDetailsRawTyped),
            );
        }
        if (array_key_exists('UomType', $data)) {
            $uomTypeRaw = $data['UomType'];
            if (!is_string($uomTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "UomType" must be string, got %s.', get_debug_type($uomTypeRaw)),
                );
            }
            $uomType = TradeDirectMasterUomType::tryFrom($uomTypeRaw) ?? UnknownEnumValue::of($uomTypeRaw);
        }
        if (array_key_exists('NotificationBeforeDelivery', $data) && $data['NotificationBeforeDelivery'] !== null) {
            $notificationBeforeDeliveryRaw = $data['NotificationBeforeDelivery'];
            if (!is_array($notificationBeforeDeliveryRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "NotificationBeforeDelivery" must be object, got %s.',
                        get_debug_type($notificationBeforeDeliveryRaw),
                    ),
                );
            }
            /** @var non-empty-array<string, mixed> $notificationBeforeDeliveryRawTyped */
            $notificationBeforeDeliveryRawTyped = $notificationBeforeDeliveryRaw;
            $notificationBeforeDelivery = Some::create(
                TradeDirectNotificationBeforeDelivery::fromArray($notificationBeforeDeliveryRawTyped),
            );
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'SoldToSameAsShipTo' => true,
                'SoldTo' => true,
                'Pickup' => true,
                'TradeComplianceDetails' => true,
                'UomType' => true,
                'NotificationBeforeDelivery' => true,
            ],
        );
        if ($uomType === null) {
            throw new MalformedDataException('Required property "UomType" is missing from the document.');
        }

        return new self(
            $uomType,
            $soldToSameAsShipTo,
            $soldTo,
            $pickup,
            $tradeComplianceDetails,
            $notificationBeforeDelivery,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $soldToSameAsShipToOption = $this->soldToSameAsShipTo;
        if ($soldToSameAsShipToOption->isDefined()) {
            $soldToSameAsShipTo = $soldToSameAsShipToOption->get();
            $dataArray['SoldToSameAsShipTo'] = $soldToSameAsShipTo;
        }
        $soldToOption = $this->soldTo;
        if ($soldToOption->isDefined()) {
            $soldTo = $soldToOption->get();
            $dataArray['SoldTo'] = $normalizationTarget->model($soldTo);
        }
        $pickupOption = $this->pickup;
        if ($pickupOption->isDefined()) {
            $pickup = $pickupOption->get();
            $dataArray['Pickup'] = $normalizationTarget->model($pickup);
        }
        $tradeComplianceDetailsOption = $this->tradeComplianceDetails;
        if ($tradeComplianceDetailsOption->isDefined()) {
            $tradeComplianceDetails = $tradeComplianceDetailsOption->get();
            $dataArray['TradeComplianceDetails'] = $normalizationTarget->model($tradeComplianceDetails);
        }
        $dataArray['UomType'] = $this->uomType->value;
        $notificationBeforeDeliveryOption = $this->notificationBeforeDelivery;
        if ($notificationBeforeDeliveryOption->isDefined()) {
            $notificationBeforeDelivery = $notificationBeforeDeliveryOption->get();
            $dataArray['NotificationBeforeDelivery'] = $normalizationTarget->model($notificationBeforeDelivery);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): TradeDirectMasterBuilder
    {
        return new TradeDirectMasterBuilder(
            $this->uomType,
            $this->soldToSameAsShipTo,
            $this->soldTo,
            $this->pickup,
            $this->tradeComplianceDetails,
            $this->notificationBeforeDelivery,
            $this->additionalProperties,
        );
    }
}
