<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see TradeDirectChild}.
 */
final class TradeDirectChildBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param TradeDirectChildType|UnknownEnumValue<string> $type
     * @param Option<string>                                $hazMatIndicator
     * @param Option<ChildLTLCharges>                       $ltlCharges
     * @param array<int|string, mixed>                      $additionalProperties
     */
    public function __construct(
        private string $uSI,
        private TradeDirectChildType|UnknownEnumValue $type,
        private ChildProduct $product,
        private ChildLTLPackage $ltlPackage,
        private Option $hazMatIndicator,
        private Option $ltlCharges,
        private array $additionalProperties,
    ) {
    }

    /**
     * The unique shipment identifier (USI) is used to create Master, LTL and Child shipments. Used
     * for Freight shipments.
     */
    public function setUSI(string $uSI): self
    {
        $this->uSI = $uSI;

        return $this;
    }

    /**
     * The type of shipment.
     *
     * Valid values:
     *
     * - LTL
     * - SMALLPACKAGE
     * - MI
     */
    public function setType(TradeDirectChildType $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * This variable represents the product details. It is used to provide information about the
     * product being shipped.
     */
    public function setProduct(ChildProduct $product): self
    {
        $this->product = $product;

        return $this;
    }

    /**
     * LTL package information. Applicable only for LTL child.
     */
    public function setLtlPackage(ChildLTLPackage $ltlPackage): self
    {
        $this->ltlPackage = $ltlPackage;

        return $this;
    }

    /**
     * Indicates the Presence/Absence of HazMat on the shipment.
     */
    public function setHazMatIndicator(string $hazMatIndicator): self
    {
        $this->hazMatIndicator = Some::create($hazMatIndicator);

        return $this;
    }

    /**
     * Represents transportation charges for child shipments categorized as "Less than Truck Load"
     * (LTL), including freight, fuel surcharges, and accessorial fees. These charges are calculated
     * based on shipment weight, volume, or distance. Applicable only for LTL child.
     */
    public function setLtlCharges(ChildLTLCharges $ltlCharges): self
    {
        $this->ltlCharges = Some::create($ltlCharges);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): TradeDirectChild
    {
        return new TradeDirectChild(
            $this->uSI,
            $this->type,
            $this->product,
            $this->ltlPackage,
            $this->hazMatIndicator,
            $this->ltlCharges,
            $this->additionalProperties,
        );
    }
}
