<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

/**
 * A value the API sent for an enum that has no case for it.
 *
 * An API adds a status, a service type, a reference kind, and the clients generated before that day
 * have no case to read it into. Refusing such a value would refuse the whole response for the sake
 * of one field, so a model reads it into this instead, and the enum property is typed
 * `SomeEnum|UnknownEnumValue`. Your code decides what a value it does not know means; a `match`
 * over the enum cases keeps its exhaustiveness check and gains a `default` arm.
 *
 * Only responses can hold one. With `ValidationMode::Lax`, the default, a response that carries an
 * unknown value is read; with `Strict` it is refused before it is read. A request can name only the
 * cases the enum has under either, and the builders take nothing else.
 *
 * `$value` has the same name as the backing value of an enum case, so logging `$property->value`
 * needs no `instanceof`.
 *
 * @template-covariant T of int|string
 */
final readonly class UnknownEnumValue
{
    /** @param T $value */
    private function __construct(public int|string $value)
    {
    }

    /**
     * @internal called by the generated models' `fromArray()`
     *
     * @template V of int|string
     *
     * @param V $value
     *
     * @return self<V>
     */
    public static function of(int|string $value): self
    {
        return new self($value);
    }
}
