<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

/**
 * Builds a {@see UPSPremierHandlingInstructions}.
 */
final class UPSPremierHandlingInstructionsBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private string $instruction, private array $additionalProperties)
    {
    }

    /**
     * Handling Instruction for UPS Premier package. Please refer Apendix UPS Premier Handling
     * Instructions.
     */
    public function setInstruction(string $instruction): self
    {
        $this->instruction = $instruction;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): UPSPremierHandlingInstructions
    {
        return new UPSPremierHandlingInstructions($this->instruction, $this->additionalProperties);
    }
}
