<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Override;
use Prefabcortex\UpsShip\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class VOIDSHIPMENTResponseWrapper implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(private VoidShipmentResponse $voidShipmentResponse, private array $additionalProperties)
    {
    }

    public static function builder(VoidShipmentResponse $voidShipmentResponse): VOIDSHIPMENTResponseWrapperBuilder
    {
        return new VOIDSHIPMENTResponseWrapperBuilder($voidShipmentResponse, []);
    }

    /**
     * Void Response Container.
     */
    public function getVoidShipmentResponse(): VoidShipmentResponse
    {
        return $this->voidShipmentResponse;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $voidShipmentResponse = null;
        if (array_key_exists('VoidShipmentResponse', $data)) {
            $voidShipmentResponseRaw = $data['VoidShipmentResponse'];
            if (!is_array($voidShipmentResponseRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "VoidShipmentResponse" must be object, got %s.',
                        get_debug_type($voidShipmentResponseRaw),
                    ),
                );
            }
            /** @var non-empty-array<string, mixed> $voidShipmentResponseRawTyped */
            $voidShipmentResponseRawTyped = $voidShipmentResponseRaw;
            $voidShipmentResponse = VoidShipmentResponse::fromArray($voidShipmentResponseRawTyped);
        }
        $additionalProperties = array_diff_key($data, ['VoidShipmentResponse' => true]);
        if ($voidShipmentResponse === null) {
            throw new MalformedDataException('Required property "VoidShipmentResponse" is missing from the document.');
        }

        return new self($voidShipmentResponse, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['VoidShipmentResponse'] = $normalizationTarget->model($this->voidShipmentResponse);
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): VOIDSHIPMENTResponseWrapperBuilder
    {
        return new VOIDSHIPMENTResponseWrapperBuilder($this->voidShipmentResponse, $this->additionalProperties);
    }
}
