<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Model;

use Prefabcortex\UpsShip\Optional\Option;
use Prefabcortex\UpsShip\Optional\Some;

/**
 * Builds a {@see VoidShipmentRequestVoidShipment}.
 */
final class VoidShipmentRequestVoidShipmentBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $shippingHistoryUserKey
     * @param Option<list<string>>     $trackingNumber
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $shipmentIdentificationNumber,
        private Option $shippingHistoryUserKey,
        private Option $trackingNumber,
        private array $additionalProperties,
    ) {
    }

    /**
     * The shipment's identification number Alpha-numeric. Must pass 1Z rules. Must be upper case.
     */
    public function setShipmentIdentificationNumber(string $shipmentIdentificationNumber): self
    {
        $this->shipmentIdentificationNumber = $shipmentIdentificationNumber;

        return $this;
    }

    /**
     * Unique key to tag shipments in shipping history. It could be MyUPS registration Number or any
     * unique identifier.
     */
    public function setShippingHistoryUserKey(string $shippingHistoryUserKey): self
    {
        $this->shippingHistoryUserKey = Some::create($shippingHistoryUserKey);

        return $this;
    }

    /**
     * The package's identification number Alpha-numeric. Must pass 1Z rules. Must be upper case.
     *
     * Package level Void is not applicable for return service.
     *
     * @param list<string> $trackingNumber
     */
    public function setTrackingNumber(array $trackingNumber): self
    {
        $this->trackingNumber = Some::create($trackingNumber);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): VoidShipmentRequestVoidShipment
    {
        return new VoidShipmentRequestVoidShipment(
            $this->shipmentIdentificationNumber,
            $this->shippingHistoryUserKey,
            $this->trackingNumber,
            $this->additionalProperties,
        );
    }
}
