<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Operation;

use Override;
use Prefabcortex\UpsShip\Exception\DeprecatedVoidShipmentBadRequestException;
use Prefabcortex\UpsShip\Exception\DeprecatedVoidShipmentForbiddenException;
use Prefabcortex\UpsShip\Exception\DeprecatedVoidShipmentTooManyRequestsException;
use Prefabcortex\UpsShip\Exception\DeprecatedVoidShipmentUnauthorizedException;
use Prefabcortex\UpsShip\Exception\MalformedDataException;
use Prefabcortex\UpsShip\Exception\MalformedResponseException;
use Prefabcortex\UpsShip\Exception\ResponseValidationException;
use Prefabcortex\UpsShip\Exception\UnexpectedContentTypeException;
use Prefabcortex\UpsShip\Exception\UnexpectedStatusCodeException;
use Prefabcortex\UpsShip\Http\BaseOperationTrait;
use Prefabcortex\UpsShip\Http\ContentType;
use Prefabcortex\UpsShip\Http\HeaderParameters;
use Prefabcortex\UpsShip\Http\JsonBody;
use Prefabcortex\UpsShip\Http\Operation;
use Prefabcortex\UpsShip\Http\OperationTrait;
use Prefabcortex\UpsShip\Http\Payload;
use Prefabcortex\UpsShip\Http\QueryParameters;
use Prefabcortex\UpsShip\Http\ValidationMode;
use Prefabcortex\UpsShip\Model\ErrorResponse;
use Prefabcortex\UpsShip\Model\VOIDSHIPMENTResponseWrapper;
use Prefabcortex\UpsShip\Parameter\DeprecatedVoidShipmentHeaderParameters;
use Prefabcortex\UpsShip\Parameter\DeprecatedVoidShipmentQueryParameters;
use Prefabcortex\UpsShip\Validation\ValidationException;
use Prefabcortex\UpsShip\Validation\ValidatorTrait;
use Prefabcortex\UpsShip\Validator\ErrorResponseConstraint;
use Prefabcortex\UpsShip\Validator\VOIDSHIPMENTResponseWrapperConstraint;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;

use function in_array;
use function str_replace;

/**
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 *
 * @implements Operation<VOIDSHIPMENTResponseWrapper>
 */
final class DeprecatedVoidShipment implements Operation
{
    use BaseOperationTrait;
    use OperationTrait;
    use ValidatorTrait;
    private readonly string $deprecatedVersion;
    private readonly string $shipmentidentificationnumber;
    private readonly DeprecatedVoidShipmentQueryParameters $queryParameters;
    private readonly DeprecatedVoidShipmentHeaderParameters $headerParameters;

    /**
     * The Void Shipping API is used to cancel the previously scheduled shipment.
     *
     * @param string $shipmentidentificationnumber The shipment's identification number
     *                                             Alpha-numeric. Must pass 1Z rules. Must be upper
     *                                             case. Length 18
     * @param string $deprecatedVersion            API Version. Valid values: - v1
     */
    public function __construct(
        string $shipmentidentificationnumber,
        string $deprecatedVersion,
        DeprecatedVoidShipmentQueryParameters $queryParameters,
        DeprecatedVoidShipmentHeaderParameters $headerParameters,
    ) {
        $this->deprecatedVersion = $deprecatedVersion;
        $this->shipmentidentificationnumber = $shipmentidentificationnumber;
        $this->queryParameters = $queryParameters;
        $this->headerParameters = $headerParameters;
    }

    #[Override]
    public function getMethod(): string
    {
        return 'DELETE';
    }

    #[Override]
    public function getUri(): string
    {
        return str_replace(
            ['{deprecatedVersion}', '{shipmentidentificationnumber}'],
            [self::pathValue($this->deprecatedVersion), self::pathValue($this->shipmentidentificationnumber)],
            '/shipments/{deprecatedVersion}/void/cancel/{shipmentidentificationnumber}',
        );
    }

    #[Override]
    public function getPayload(StreamFactoryInterface $streamFactory, ValidationMode $validation): Payload
    {
        return new Payload([], '');
    }

    /** @return array<string, list<string>> */
    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    protected function getQueryParameters(): QueryParameters
    {
        return $this->queryParameters->toQueryParameters();
    }

    protected function getHeaderParameters(): HeaderParameters
    {
        return $this->headerParameters->toHeaderParameters();
    }

    /**
     * {@inheritdoc}.
     *
     * @throws ValidationException
     * @throws MalformedDataException
     * @throws DeprecatedVoidShipmentBadRequestException
     * @throws DeprecatedVoidShipmentUnauthorizedException
     * @throws DeprecatedVoidShipmentForbiddenException
     * @throws DeprecatedVoidShipmentTooManyRequestsException
     * @throws UnexpectedContentTypeException
     * @throws UnexpectedStatusCodeException
     */
    #[Override]
    protected function transformResponseBody(
        ResponseInterface $response,
        ContentType $contentType,
        string $body,
        ValidationMode $validation,
    ): VOIDSHIPMENTResponseWrapper {
        $status = $response->getStatusCode();
        if (200 === $status && $contentType->is('application/json')) {
            $typedData = JsonBody::toArray($body);
            if (ValidationMode::Strict === $validation) {
                $this->validate($typedData, VOIDSHIPMENTResponseWrapperConstraint::constraints());
            }

            return VOIDSHIPMENTResponseWrapper::fromArray($typedData);
        }
        if (400 === $status && $contentType->is('application/json')) {
            $typedData = JsonBody::toArray($body);
            if (ValidationMode::Strict === $validation) {
                $this->validate($typedData, ErrorResponseConstraint::constraints());
            }
            throw new DeprecatedVoidShipmentBadRequestException(ErrorResponse::fromArray($typedData), $response, $body);
        }
        if (401 === $status && $contentType->is('application/json')) {
            $typedData = JsonBody::toArray($body);
            if (ValidationMode::Strict === $validation) {
                $this->validate($typedData, ErrorResponseConstraint::constraints());
            }
            throw new DeprecatedVoidShipmentUnauthorizedException(
                ErrorResponse::fromArray($typedData),
                $response,
                $body,
            );
        }
        if (403 === $status && $contentType->is('application/json')) {
            $typedData = JsonBody::toArray($body);
            if (ValidationMode::Strict === $validation) {
                $this->validate($typedData, ErrorResponseConstraint::constraints());
            }
            throw new DeprecatedVoidShipmentForbiddenException(ErrorResponse::fromArray($typedData), $response, $body);
        }
        if (429 === $status && $contentType->is('application/json')) {
            $typedData = JsonBody::toArray($body);
            if (ValidationMode::Strict === $validation) {
                $this->validate($typedData, ErrorResponseConstraint::constraints());
            }
            throw new DeprecatedVoidShipmentTooManyRequestsException(
                ErrorResponse::fromArray($typedData),
                $response,
                $body,
            );
        }
        if (in_array($status, [200, 400, 401, 403, 429], true)) {
            throw new UnexpectedContentTypeException($response, $body);
        }
        throw UnexpectedStatusCodeException::of($response, $body);
    }

    /**
     * @throws ResponseValidationException
     * @throws MalformedResponseException
     * @throws DeprecatedVoidShipmentBadRequestException
     * @throws DeprecatedVoidShipmentUnauthorizedException
     * @throws DeprecatedVoidShipmentForbiddenException
     * @throws DeprecatedVoidShipmentTooManyRequestsException
     * @throws UnexpectedContentTypeException
     * @throws UnexpectedStatusCodeException
     */
    #[Override]
    public function parseResponse(ResponseInterface $response, ValidationMode $validation): VOIDSHIPMENTResponseWrapper
    {
        $contentType = ContentType::fromHeader($response->getHeader('Content-Type')[0] ?? '');
        $body = self::readBody($response);
        try {
            return $this->transformResponseBody($response, $contentType, $body, $validation);
        } catch (ValidationException $exception) {
            if ($response->getStatusCode() >= 400) {
                throw UnexpectedStatusCodeException::ofUnreadableBody($response, $body, $exception);
            }
            throw new ResponseValidationException($exception, $response, $body);
        } catch (MalformedDataException $exception) {
            if ($response->getStatusCode() >= 400) {
                throw UnexpectedStatusCodeException::ofUnreadableBody($response, $body, $exception);
            }
            throw new MalformedResponseException($exception, $response, $body);
        }
    }

    /** @return list<list<string>> */
    #[Override]
    public function getSecurityRequirements(): array
    {
        return [['OAuth2']];
    }
}
