<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\BillShipperCreditCard;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see BillShipperCreditCard} has to satisfy.
 */
final class BillShipperCreditCardConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'Type' => new Required([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'Number' => new Required([
                    new Length(null, 9),
                    new NotBlank(null, null, null),
                    new Length(null, null, 16),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'ExpirationDate' => new Required([
                    new Length(null, 6),
                    new NotBlank(null, null, null),
                    new Length(null, null, 6),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'SecurityCode' => new Required([
                    new Length(null, 3),
                    new NotBlank(null, null, null),
                    new Length(null, null, 4),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'Address' => new Optional([new NotNull(), ...CreditCardAddressConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
