<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\ChildLTLPackage;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see ChildLTLPackage} has to satisfy.
 */
final class ChildLTLPackageConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'NumberOfIdenticalUnits' => new Required([new Type(['string']), new NotNull()]),
                'HandlingUnits' => new Required([new NotNull(), ...LTLHandlingUnitsConstraint::constraints()]),
                'ReferenceNumber' => new Optional([new NotNull(), ...LTLReferenceNumberConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
