<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\CODTurnInPageImage;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see CODTurnInPageImage} has to satisfy.
 */
final class CODTurnInPageImageConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'ImageFormat' => new Required([
                    new NotNull(),
                    ...CODTurnInPageImageImageFormatConstraint::constraints(),
                ]),
                'GraphicImage' => new Required([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
