<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\ContactsProducer;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see ContactsProducer} has to satisfy.
 */
final class ContactsProducerConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'Option' => new Optional([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'CompanyName' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'TaxIdentificationNumber' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 15),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'Address' => new Optional([new NotNull(), ...ProducerAddressConstraint::constraints()]),
                'AttentionName' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'Phone' => new Optional([new NotNull(), ...ProducerPhoneConstraint::constraints()]),
                'EMailAddress' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
            ], null, null, true),
        ];
    }
}
