<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\LABELRECOVERYResponseWrapper;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Required;

/**
 * The rules a document for {@see LABELRECOVERYResponseWrapper} has to satisfy.
 */
final class LABELRECOVERYResponseWrapperConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'LabelRecoveryResponse' => new Required([
                    new NotNull(),
                    ...LabelRecoveryResponseConstraint::constraints(),
                ]),
            ], null, null, true),
        ];
    }
}
