<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\LabelRecoveryResponseTrackingCandidate;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see LabelRecoveryResponseTrackingCandidate} has to satisfy.
 */
final class LabelRecoveryResponseTrackingCandidateConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'TrackingNumber' => new Required([
                    new Length(null, 18),
                    new NotBlank(null, null, null),
                    new Length(null, null, 18),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'DestinationPostalCode' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 9),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'DestinationCountryCode' => new Optional([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'PickupDateRange' => new Optional([
                    new NotNull(),
                    ...TrackingCandidatePickupDateRangeConstraint::constraints(),
                ]),
            ], null, null, true),
        ];
    }
}
