<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\LTLDimensions;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see LTLDimensions} has to satisfy.
 */
final class LTLDimensionsConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'Length' => new Required([new Type(['string']), new NotNull()]),
                'Width' => new Required([new Type(['string']), new NotNull()]),
                'Height' => new Required([new Type(['string']), new NotNull()]),
                'UnitOfMeasurement' => new Required([...LTLDimensionsUnitOfMeasurementConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
