<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\MasterPickup;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see MasterPickup} has to satisfy.
 */
final class MasterPickupConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'Name' => new Required([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Regex('#^(?!\s*$).{1,35}$#Du'),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'AttentionName' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Regex('#^.{0,35}$#Du'),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'Phone' => new Optional([new NotNull(), ...TradeDirectPhoneConstraint::constraints()]),
                'Address' => new Required([new NotNull(), ...TradeDirectAddressConstraint::constraints()]),
                'EMailAddress' => new Required([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
            ], null, null, true),
        ];
    }
}
