<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\PaymentInformationShipmentCharge;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see PaymentInformationShipmentCharge} has to satisfy.
 */
final class PaymentInformationShipmentChargeConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'Type' => new Required([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'BillShipper' => new Optional([new NotNull(), ...ShipmentChargeBillShipperConstraint::constraints()]),
                'BillReceiver' => new Optional([new NotNull(), ...ShipmentChargeBillReceiverConstraint::constraints()]),
                'BillThirdParty' => new Optional([
                    new NotNull(),
                    ...ShipmentChargeBillThirdPartyConstraint::constraints(),
                ]),
                'ConsigneeBilledIndicator' => new Optional([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
