<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\ShipmentServiceOptionsRestrictedArticles;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see ShipmentServiceOptionsRestrictedArticles} has to satisfy.
 */
final class ShipmentServiceOptionsRestrictedArticlesConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'DiagnosticSpecimensIndicator' => new Optional([new Type(['string']), new NotNull()]),
                'AlcoholicBeveragesIndicator' => new Optional([new Type(['string']), new NotNull()]),
                'PerishablesIndicator' => new Optional([new Type(['string']), new NotNull()]),
                'PlantsIndicator' => new Optional([new Type(['string']), new NotNull()]),
                'SeedsIndicator' => new Optional([new Type(['string']), new NotNull()]),
                'SpecialExceptionsIndicator' => new Optional([new Type(['string']), new NotNull()]),
                'TobaccoIndicator' => new Optional([new Type(['string']), new NotNull()]),
                'ECigarettesIndicator' => new Optional([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
