<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\ShipmentResultsFRSShipmentData;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see ShipmentResultsFRSShipmentData} has to satisfy.
 */
final class ShipmentResultsFRSShipmentDataConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'TransportationCharges' => new Required([
                    new NotNull(),
                    ...FRSShipmentDataTransportationChargesConstraint::constraints(),
                ]),
                'FreightDensityRate' => new Optional([
                    new NotNull(),
                    ...FRSShipmentDataFreightDensityRateConstraint::constraints(),
                ]),
                'HandlingUnits' => new Optional([
                    new All([...FRSShipmentDataHandlingUnitsConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
            ], null, null, true),
        ];
    }
}
