<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\ShipmentShipper;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see ShipmentShipper} has to satisfy.
 */
final class ShipmentShipperConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'Name' => new Required([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'AttentionName' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'CompanyDisplayableName' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'TaxIdentificationNumber' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 15),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'Phone' => new Optional([new NotNull(), ...ShipperPhoneConstraint::constraints()]),
                'ShipperNumber' => new Required([
                    new Length(null, 6),
                    new NotBlank(null, null, null),
                    new Length(null, null, 6),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'FaxNumber' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 14),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'EMailAddress' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'Address' => new Required([new NotNull(), ...ShipperAddressConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
