<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\ShipmentServiceOptionsInternationalForms;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see ShipmentServiceOptionsInternationalForms} has to satisfy.
 */
final class ShipmentServiceOptionsInternationalFormsConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'FormType' => new Required([new All([new Type(['string'])]), new Type(['array']), new NotNull()]),
                'UserCreatedForm' => new Optional([
                    new NotNull(),
                    ...InternationalFormsUserCreatedFormConstraint::constraints(),
                ]),
                'UPSPremiumCareForm' => new Optional([
                    new NotNull(),
                    ...InternationalFormsUPSPremiumCareFormConstraint::constraints(),
                ]),
                'CN22Form' => new Optional([new NotNull(), ...InternationalFormsCN22FormConstraint::constraints()]),
                'AdditionalDocumentIndicator' => new Optional([new Type(['string']), new NotNull()]),
                'FormGroupIdName' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'EEIFilingOption' => new Optional([
                    new NotNull(),
                    ...InternationalFormsEEIFilingOptionConstraint::constraints(),
                ]),
                'Contacts' => new Optional([new NotNull(), ...InternationalFormsContactsConstraint::constraints()]),
                'Product' => new Required([
                    new All([...InternationalFormsProductConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'InvoiceNumber' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'InvoiceDate' => new Optional([
                    new Length(null, 8),
                    new NotBlank(null, null, null),
                    new Length(null, null, 8),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'PurchaseOrderNumber' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'TermsOfShipment' => new Optional([
                    new Length(null, 3),
                    new NotBlank(null, null, null),
                    new Length(null, null, 3),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'ReasonForExport' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 20),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'Comments' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 150),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'DeclarationStatement' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 550),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'Discount' => new Optional([new NotNull(), ...InternationalFormsDiscountConstraint::constraints()]),
                'FreightCharges' => new Optional([
                    new NotNull(),
                    ...InternationalFormsFreightChargesConstraint::constraints(),
                ]),
                'InsuranceCharges' => new Optional([
                    new NotNull(),
                    ...InternationalFormsInsuranceChargesConstraint::constraints(),
                ]),
                'OtherCharges' => new Optional([
                    new NotNull(),
                    ...InternationalFormsOtherChargesConstraint::constraints(),
                ]),
                'CurrencyCode' => new Optional([
                    new Length(null, 3),
                    new NotBlank(null, null, null),
                    new Length(null, null, 3),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'BlanketPeriod' => new Optional([
                    new NotNull(),
                    ...InternationalFormsBlanketPeriodConstraint::constraints(),
                ]),
                'ExportDate' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'ExportingCarrier' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'CarrierID' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 17),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'InBondCode' => new Optional([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'EntryNumber' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 25),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'PointOfOrigin' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 5),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'PointOfOriginType' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 1),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'ModeOfTransport' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'PortOfExport' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'PortOfUnloading' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'LoadingPier' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'PartiesToTransaction' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 1),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'RoutedExportTransactionIndicator' => new Optional([new Type(['string']), new NotNull()]),
                'ContainerizedIndicator' => new Optional([new Type(['string']), new NotNull()]),
                'OverridePaperlessIndicator' => new Optional([new Type(['string']), new NotNull()]),
                'ShipperMemo' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 300),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'HazardousMaterialsIndicator' => new Optional([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
