<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\ShipmentPackage;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see ShipmentPackage} has to satisfy.
 */
final class ShipmentPackageConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'Description' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 35),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'PalletDescription' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 150),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'NumOfPieces' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 5),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'UnitPrice' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 12),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'Packaging' => new Required([new NotNull(), ...PackagePackagingConstraint::constraints()]),
                'Dimensions' => new Optional([new NotNull(), ...PackageDimensionsConstraint::constraints()]),
                'DimWeight' => new Optional([new NotNull(), ...PackageDimWeightConstraint::constraints()]),
                'PackageWeight' => new Optional([new NotNull(), ...PackagePackageWeightConstraint::constraints()]),
                'LargePackageIndicator' => new Optional([new Type(['string']), new NotNull()]),
                'OversizeIndicator' => new Optional([new Type(['string']), new NotNull()]),
                'MinimumBillableWeightIndicator' => new Optional([new Type(['string']), new NotNull()]),
                'ReferenceNumber' => new Optional([
                    new All([...PackageReferenceNumberConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'AdditionalHandlingIndicator' => new Optional([new Type(['string']), new NotNull()]),
                'SimpleRate' => new Optional([new NotNull(), ...PackageSimpleRateConstraint::constraints()]),
                'UPSPremier' => new Optional([new NotNull(), ...PackageUPSPremierConstraint::constraints()]),
                'PackageServiceOptions' => new Optional([
                    new NotNull(),
                    ...PackagePackageServiceOptionsConstraint::constraints(),
                ]),
                'Commodity' => new Optional([new NotNull(), ...PackageCommodityConstraint::constraints()]),
                'HazMatPackageInformation' => new Optional([
                    new NotNull(),
                    ...PackageHazMatPackageInformationConstraint::constraints(),
                ]),
            ], null, null, true),
        ];
    }
}
