<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\TradeDirectMaster;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see TradeDirectMaster} has to satisfy.
 */
final class TradeDirectMasterConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'SoldToSameAsShipTo' => new Optional([new Type(['string']), new NotNull()]),
                'SoldTo' => new Optional([new NotNull(), ...MasterSoldToConstraint::constraints()]),
                'Pickup' => new Optional([new NotNull(), ...MasterPickupConstraint::constraints()]),
                'TradeComplianceDetails' => new Optional([
                    new NotNull(),
                    ...MasterTradeComplianceDetailsConstraint::constraints(),
                ]),
                'UomType' => new Required([...TradeDirectMasterUomTypeConstraint::constraints()]),
                'NotificationBeforeDelivery' => new Optional([
                    new NotNull(),
                    ...TradeDirectNotificationBeforeDeliveryConstraint::constraints(),
                ]),
            ], null, null, true),
        ];
    }
}
