<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\TradeDirectNotificationBeforeDelivery;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see TradeDirectNotificationBeforeDelivery} has to satisfy.
 */
final class TradeDirectNotificationBeforeDeliveryConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'RequestType' => new Optional([
                    ...TradeDirectNotificationBeforeDeliveryRequestTypeConstraint::constraints(),
                ]),
                'MediaTypeCode' => new Optional([
                    ...TradeDirectNotificationBeforeDeliveryMediaTypeCodeConstraint::constraints(),
                ]),
                'Language' => new Optional([
                    new Regex('#^[A-Z]{3}$#Du'),
                    new NotBlank(null, null, null),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'Dialect' => new Optional([
                    new Regex('#^[A-Z0-9]{2}$#Du'),
                    new NotBlank(null, null, null),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'ShipFromCompanyName' => new Optional([
                    new Length(null, null, 35),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'CompanyName' => new Optional([new Length(null, null, 35), new Type(['string']), new NotNull()]),
                'Phone' => new Optional([new NotNull(), ...TradeDirectPhoneConstraint::constraints()]),
                'SubjectLine' => new Optional([new Length(null, null, 75), new Type(['string']), new NotNull()]),
                'Memo' => new Optional([new Length(null, null, 150), new Type(['string']), new NotNull()]),
                'Name' => new Optional([new Length(null, null, 35), new Type(['string']), new NotNull()]),
                'EMailAddress' => new Required([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Regex('#^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$#Du'),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'AlternateEmailAddress' => new Optional([
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
            ], null, null, true),
        ];
    }
}
