<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsShip\Validator;

use Override;
use Prefabcortex\UpsShip\Model\VoidShipmentResponseResponse;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;

/**
 * The rules a document for {@see VoidShipmentResponseResponse} has to satisfy.
 */
final class VoidShipmentResponseResponseConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'ResponseStatus' => new Required([
                    new NotNull(),
                    ...VoidResponseResponseStatusConstraint::constraints(),
                ]),
                'Alert' => new Optional([new NotNull(), ...ResponseAlertConstraint::constraints()]),
                'TransactionReference' => new Optional([
                    new NotNull(),
                    ...VoidResponseTransactionReferenceConstraint::constraints(),
                ]),
            ], null, null, true),
        ];
    }
}
